[pluto.yun] 로또 2단계
2023newkrew/java-lotto-kakao pull request #103
Opened 2023-01-09 02:56 UTC by tkaltk123

1단계 피드백을 적용했고 2단계 요구사항을 적용했습니다!

2023-01-09 08:42 UTC, sangnyyy requested changes
주신 PR 에 대한 몇가지 피드백 남겼습니다.

전반적으로 객체와 그 객체에 할당된 책임이 전반적으로 적절하지 못하다는 느낌이 들었습니다. 😥
([이 글을](https://incheol-jung.gitbook.io/docs/study/object/2020-03-10-object-chap3) 참고해보세요. 제 코멘트에 대한 디테일을 잘 설명하고 있습니다.)

관련해서 코멘트 남겨드렸으니 읽어보시고 이해 안가시거나 논의 나누고픈 부분이 있으시다면 편하게 추가 코멘트 남겨주세요. 감사합니다 :)

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/Application.java
> +        LottoSimulator simulator = LottoSimulator.create(lottoPrice, inputView, outputView);
훨씬 직관적으로 변했네요. input, output, simulator(controller) 가 생겨서 역할 분리도 잘 된 것 같습니다. 👍

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoMachine.java
> +        return money.divide(price).longValue();
money 가 바로 long 타입의 리턴을 가져도 되지 않을까요?

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoMachine.java
> +    public long getPurchasableCount(Money money) {
로또 기계가 구매 가능 갯수를 결정하는 것보다 로또 상점이 결정하는게 적절하단 생각이 드는데 어떻게 생각하세요?

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoMachine.java
> +    public LottoReceipt createReceipt(Money money, long count) {
영수증 또한 발급의 주체가 로또기계 보단 로또상점이 맞지않나라고 생각이 들어요.
한번 고민해봐주셨으면 합니다. (제 말이 꼭 전부 정답은 아니에요!)

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoReceipt.java
> +    public Money getChange() {
private-package 로 접근 수준을 변경하는게 좋겠군요.
(테스트에서 밖에 사용안하니..)

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoReceipt.java
> +    }
equals 와 hashCode 를 직접 정의하신듯 하네요. 이유가 있으실까요?

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoReceipt.java
> +public class LottoReceipt {
위에서도 계속해서 말씀드렸지만, 전반적으로 기능의 위임이 객체에 적절하게 이뤄지고 있지 않다는 느낌이 듭니다 🥲

객체를 정의할 때, 그 객체가 하는 일(책임)이 무엇인지 잘 고민해보세요.
객체는 필드값이 아닌 메서드(기능)이 우선적으로 고려되어야 합니다. 
메서드의 동작을 위해 필요로 하게 되는 것이 필드값들로 이것들은 후행적이라고 볼 수 있습니다.

해당 클래스의 메서드 시그니처는 다음과 같습니다.

- Money getChange()
- double calculateProfitRate(Money prize)

LottoReceipt 가 가져야 할 책임(기능)으로 볼 수 있을까요? 다시 한번 고민해보시기 바랍니다.
또는 객체의 네이밍이 적절하지 못한 것일수도 있습니다. 이 부분도 고민해보시기 바랍니다 :)

---

p.s. 가이드를 좀 더 드려보면, LottoReceipt 는 change 를 필드로 정의하고 내부적으로 사용할 뿐 아무것도 하지 않고 있습니다. 그리고, double 타입 ProfitRate을 객체 레벨로 끌어올려보세요. 그러면 LottoReceipt 는 자연스레 불필요한 클래스가 될 듯 합니다. ProfitRate 이 Change 에 의존하는 구조로 바뀌며 LottoReceipt 는 자연스레 하는 일이 없어질테니까요.

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/ranking/WinningNumbers.java
> +    private static void validate(LottoNumber winningNumber, SingleLottoNumber bonus) {
👍👍👍

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/Money.java
> +    public static boolean isNullOrZero(Money money) {
메서드의 위치가 호출하는 사용처의 하단에 위치하는 것이 좋겠습니다 :)

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoMachine.java
> +        if(count < 0){
리포맷팅 하면 좋겠네요. 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/24868642/211264871-56b5a961-b07e-4fdd-a5e1-2e161c9c5e42.png">

2023-01-09 08:42 UTC, sangnyyy commented on src/main/java/lotto/view/LottoOutputView.java
> +        System.out.printf("수동으로 %d장, 자동으로 %d개를 구매했습니다.\n",manualCount, ticket.count() -manualCount);
리포맷팅 부탁드립니다.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/24868642/211266436-694afdb7-73b3-49ab-a8d9-cb80a18e62cc.png">

2023-01-09 08:42 UTC, sangnyyy commented on src/test/java/lotto/model/ranking/RankingCountsTest.java
> +        @DisplayName("총 상금 계산")
총 상금을 계산하는 책임이 RankingCounts 에 있는게 적절한지 고민해보시면 좋을 것 같습니다 :)

2023-01-09 08:42 UTC, sangnyyy commented on src/test/java/lotto/model/store/LottoMachineTest.java
> +        @DisplayName("구입 가능한 로또 갯수 반환")
위에서 말씀드린 바와 같이 구입 가능 갯수에 대한 판단이 적절한 책임인지 고민해보시면 좋을 듯 합니다 :)

2023-01-09 08:42 UTC, sangnyyy commented on src/test/java/lotto/model/store/LottoReceiptTest.java
> +        @DisplayName("투자금이 1000, 총 가격이 1000일 때 총 상금을 받아 수익률 계산")
위에서 말씀드렸듯이 총 상금을 받아 수익률 계산하는 책임이 적절한지 고민해보시면 좋을 듯 합니다 :)

2023-01-09 14:32 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoMachine.java
> +        return money.divide(price).longValue();
수정했습니다.

2023-01-09 14:32 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoMachine.java
> +    public long getPurchasableCount(Money money) {
수정했습니다

2023-01-09 14:32 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoMachine.java
> +    public LottoReceipt createReceipt(Money money, long count) {
수정했습니다

2023-01-09 14:33 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoReceipt.java
> +    public Money getChange() {
LottoReceipt의 용도를 변경했습니다!

2023-01-09 14:33 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoReceipt.java
> +    }
테스트코드를 만들면서 추가한 것 같은데 사용하는 곳이 없어진 것 같아서 제거했습니다.

2023-01-09 14:34 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoReceipt.java
> +public class LottoReceipt {
피드백 주신것처럼 ProfitRate와 TotalPrize를 객체 레벨로 수정했습니다.

2023-01-09 14:35 UTC, tkaltk123 commented on src/main/java/lotto/model/store/Money.java
> +    public static boolean isNullOrZero(Money money) {
수정했습니다.

2023-01-09 14:36 UTC, tkaltk123 commented on src/test/java/lotto/model/ranking/RankingCountsTest.java
> +        @DisplayName("총 상금 계산")
TotalPrize를 추가해 전체 상금을 계산하는 책임을 이관했습니다.

2023-01-09 14:36 UTC, tkaltk123 commented on src/main/java/lotto/view/LottoOutputView.java
> +        System.out.printf("수동으로 %d장, 자동으로 %d개를 구매했습니다.\n",manualCount, ticket.count() -manualCount);
수정했습니다

2023-01-09 14:36 UTC, tkaltk123 commented on src/test/java/lotto/model/store/LottoMachineTest.java
> +        @DisplayName("구입 가능한 로또 갯수 반환")
LottoStore로 이관했습니다

2023-01-09 14:36 UTC, tkaltk123 commented on src/test/java/lotto/model/store/LottoReceiptTest.java
> +        @DisplayName("투자금이 1000, 총 가격이 1000일 때 총 상금을 받아 수익률 계산")
ProfitRate로 이관했습니다.

2023-01-09 14:39 UTC, tkaltk123 commented
피드백 반영했습니다!

2023-01-10 02:13 UTC, sangnyyy approved these changes
리뷰들 반영해주시느라 고생하셨습니다!! 
다음 미션으로 넘어가주세요.

2023-01-10 02:13 UTC, merged