[jade.xyz] 로또 과제 step2 제출
2023newkrew/java-lotto-kakao pull request #108
Opened 2023-01-11 05:29 UTC by mincastle98

안녕하세요 제이든! 2주차 과제 step2 리뷰 요청드립니다.

담당자분께서 남겨주신 리뷰 바탕으로 리팩토링 진행하였고 이 외에도 부족하다고 생각되는 부분 수정하였습니다. 추가로 step2 기능도 반영하였습니다. step1 기준으로 많은 부분이 변경되었습니다. 확인 후 리뷰 부탁드립니다!
감사합니다.

## 수정된 부분
### 리뷰 내용
- 일부 메서드가 getter를 통해 값을 꺼내 동작을 수행하여 해당 메서드를 적절한 역할에 맞게 수정하였습니다.
- 구현체로 직접 구현되던 부분을 인터페이스로 추상화하도록 수정하였습니다.
- 당첨 등수를 확인하는 로직을 Price Enum 클래스로 이동하고 이에 적절하게 수정하였습니다.
- List를 인자로 받는 생성자가 가변인자도 받을 수 있도록 추가하였습니다.
### 추가 수정
- Integer로 다루던 로또 숫자를 LottoNumber로 다룰 수 있도록 변경하였습니다.
- Lotto 클래스와 WinningLotto 클래스 사이에 중복 및 유사성이 있다고 판단하여 WinningLotto가 Lotto를 상속하도록 수정하였습니다.
- 요구사항에 맞지 않게 출력되는 부분을 일부 수정하였습니다.

* LottoService 내에 purchaseCost 필드가 불필요하다는 피드백을 받았는데 해당 값은 이후에 수익률을 계산하는 데에도 다시 활용되기 때문에 삭제하지 않고 유지하였습니다.

## 추가된 부분
- 기존에는 자동으로 로또의 숫자를 생성할 수 있었는데 수동으로도 직접 로또의 숫자를 입력할 수 있도록 수정
- 금액에 따른 구매 장수에서 수동 로또 개수를 제외한 만큼만 자동으로 숫자 생성

2023-01-16 13:53 UTC, jinuk17 requested changes
구조적으로 많이 개선 되었네요 ~ 고생 많으셨습니다 👏 
몇가지 피드백 남겨두었습니다. 
확인 후 요청주세요 ~

2023-01-16 13:53 UTC, jinuk17 commented on src/main/java/lotto/controller/LottoController.java
>          LottoService lottoService = new LottoService(purchaseCost);
LottoService 가 판매 금액, 수동 번호를 갖고 자동 / 수동 로또를 생성해 주면 어떨까요 ? 
그러면 `LottoService.LOTTO_COST` 같이 LottoService 도메인이 외부에 노출되지 않아도 될 것 같습니다.

2023-01-16 13:53 UTC, jayden-17 commented on src/main/java/lotto/model/Lotto.java
> +    public Lotto(Integer... numbers) {
Lotto 는 6개의 숫자로만 생성되어야 하는데 이 부분도 validation 으로 추가해보면 어떨까요 ?

2023-01-16 13:53 UTC, jayden-17 commented on src/main/java/lotto/model/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> lottoNumbers = new HashMap<>();
불변객체 활용을 위한 캐시 사용 👍

2023-01-16 13:53 UTC, jayden-17 commented on src/main/java/lotto/model/WinningLotto.java
> +public class WinningLotto extends Lotto {
상속 보다는 조합을 사용하는게 어떨까요 ?

2023-01-16 13:53 UTC, jinuk17 commented on src/main/java/lotto/model/Price.java
> +                    .findFirst().get();
`findFirst()` 의 경우 return 값이 `Optional` 타입인데요 ~ 
`Optional` 의 경우 값이 없음을 인지하고 바로 `get()` 을 호출하는건 위험합니다. 
`orElse~` 관련 메소드들을 이용해서 처리해보면 어떨까요 ?

2023-01-18 07:33 UTC, mincastle98 commented on src/main/java/lotto/model/Price.java
> +                    .findFirst().get();
32번 줄로 해당 경우에 들어오는 경우 결과값이 존재할 수 밖에 없기 때문에 get()을 바로 호출했는데 이런 경우에는 orElse를 어떤 식으로 처리하는게 좋을까요? 우선 다른 값을 넘기는 것은 비정상적인 수행이라서 예외를 발생하도록 하였는데 더 좋은 방법이 있을까요?

2023-01-18 07:46 UTC, mincastle98 commented
###수정된 부분
- LottoService 객체를 미리 생성 후 입력된 값에 따라 수동 로또 숫자 List, 자동 로또 개수를 입력으로 받는 메서드 호출을 통해 Lotto 객체를 생성하던 방식에서 **LottoService 객체 생성 시 구매 가격과 수동 로또 숫자 List를 넘기도록 하여 내부에서 Lotto 객체를 생성하도록 수정**하였습니다.
- InputView에서만 이루어지던 숫자 개수 유효성 검사를 Lotto 생성 시에도 수행하도록 추가하였습니다.
- 상속으로 구현되었던 WinningLotto를 조합을 통해 구현되도록 수정하였습니다.
- Optional 값에서 null 체크를 하지 않고 값을 가져오던 코드를 수정했습니다.
- 수동 입력 시 중복된 숫자가 입력되던 오류를 수정하였습니다.

### 질문 사항
- Optional 값에 대한 예외처리에 대한 질문을 해당 코멘트에 남겨두었습니다. 답변주시면 감사하겠습니다!

2023-01-18 12:17 UTC, jinuk17 commented on src/main/java/lotto/model/Price.java
> +                    .findFirst().get();
이런 경우 저는 `orElse(Price.NOTHING)` 이 더 적절해 보이네요 ~ 

실제로 내부 구현으로만 보았을 땐 `orElse~` 구문이 타지 않는다고 확신을 하지만 일부 구현의 변경으로 어떻게 동작할지 예상할 수 없으므로 안전하게 구문을 처리하는게 좋을 것 같습니다. (하지만 이미 unit test 가 있기 때문에 이런 일은 더더욱 없을 것 같아요~)

`get()` 과 `orElseThrow()` 의 경우 NPE 이냐 custom exception 이냐의 차이로 볼 수 있지만 사용자가 인지한 exception 이냐 아니냐의 차이는 크게 느껴질 수 있습니다.  java 에서 custom exception 은 하나의 응답으로 볼 수 있기 때문에 인지하고 명확하게 처리하는게 어떨까요 ?

2023-01-18 13:02 UTC, jayden-17 approved these changes
피드백 남긴 부분 모두 잘 반영해주셨네요, 고생하셨습니다 👍 
질문 주신 부분도 의견 남겨 놓았습니다. 
이번 PR 머지하도록 할게요 ~

2023-01-28 05:44 UTC, merged