[asher.an] lotto미션 Step1
2023newkrew/java-lotto-kakao pull request #13
Opened 2023-01-03 06:00 UTC by mkom76

리팩터링 할 부분은 아직 눈에 보이지만, 기한 맞춰서 PR드립니다.
MVC패턴에 맞추어 구현하였습니다.

Model: Lotto, Lottos, Winner, Ranking(enum)
View: InputView, OutputView
Controller: LottoController

<Model>
로또번호를 int리스트로 가지는 일급객체 개념의 Lotto
Lotto객체들을 관리하는 Lottos
당첨여부와 수익률을 계산하여 컨트롤러에 넘겨주는 Winner(서비스 레이어에 가깝다고 생각합니다)
로또 결과 case별로 정보를 모아둔 Ranking enum

생각하는 개선방향: 
Winner, Lottos객체를 지금 컨트롤러에서 사용중인데, 컨트롤러는 Winner하고만 통신하도록 구현이 가능할 것 같습니다.
Validation logic을 각 모델에 추가할 수 있을 것 같습니다.

<View>
User input을 받고 컨트롤러에 넘겨주는 InputView
컨트롤러에게서 받은 데이터를 토대로 정보를 출력하는 OutputView

특이사항:
이번에는 Validation logic을 InputView에서 진행하였습니다.

감사합니다!!

2023-01-04 03:01 UTC, scolleck requested changes
몇가지 리뷰사항을 남겨드렸습니다. 전반적으로 지난번 과제보다 발전하고 있는것이 느껴집니다 고생많으셨습니다 ^^!

기재해주신 생각하고있는 개선방향도 추후에는 적용하여 리뷰 요청 부탁드릴게요 ~ :D

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(money / 1000);
1000 단위의 기준은 상수화 하여 재사용을 하면 어떨까요?
inputView 내에서도 사용되는 것 같습니다.

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/view/InputView.java
> +    }
[Nit]
Apache Commons의 NumberUtils 에는
이와같이 숫자값인 문자를 숫자로 변환하는 다양한 API가 존재합니다 :)
참고해주세요

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/math/NumberUtils.html

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/view/InputView.java
> +        catch(Exception e){
전반적으로 코드 컨벤션에 맞추어 정리가 될 필요가 있을 것 같습니다.

catch (Exception e)
if (blabla...)

처럼 예약어 다음 공백 다음 괄호가 나오도록 정리해주시면 좋을 것 같아요 :)
인텔리제이를 사용하신다면 reformat code 기능을 활용하시면 되겠습니다.

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/view/InputView.java
> +        return input.replaceAll("\\s", "").split(",");
마찬가지로 상수화 되면 좋을것 같아요 ^^..

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/view/InputView.java
> +        }
Set Collection의 특징을 활용하여 중복제거를 진행하셨네요 :)
좋은 코드인것 같습니다 💯

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/view/InputView.java
> +    }
[Nit]
범위 체크에는 다양한 라이브러리가 존재합니다. 예를들어 
Apache Commons 의 Range 에는 between 이 있습니다.

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/Range.html

현재는 직접 구현하는것이 좋지만 현업에서는 이러한 라이브러리 사용도 고려하시면 추후 좋을 것 같아요 :)

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/controller/LottoController.java
> +        Map<Ranking, Integer> rankingResult = winner.rankingCount(rankings);
rankResult를 unmodified 처리 한것은 좋은것 같아요

다만. java.util.List, java.util.Map와 같은 collection을 외부에 노출하는 경우 사용자는 너무 많은 인터페이스에 노출하게 될 수 도 있습니다.

rankingResult 모델을 따로 만들어서 그 안에 Map을 private 접근 제한하고
rankingResult.getStatistic() 과 같이 구현하는 것은 어떨까요?

(일급 콜렉션을 사용)

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/utils/RandomNumbersGenerator.java
> +        }
[Nit]
매번 루프를 돌아서 번호를 생성 후 담은 다음 셔플 리턴 vs 고정된 리스트 를 deepCopy 후 셔플 리턴

장단이 있을텐데 한번 생각해보셔요 ^^..

2023-01-04 03:01 UTC, scolleck commented on src/test/java/lotto/model/LottoTest.java
> +            "8,9,10,11,12,13;DEFAULT"}, delimiter = ';')
테스트에 CsvSource를 활용하셨군요. 💯

2023-01-04 03:01 UTC, scolleck commented on src/test/java/lotto/model/WinnerTest.java
> +        }};
rankingResult를 만드는 부분은 메소드추출 하는것이 어떨까요?

2023-01-04 03:01 UTC, scolleck commented on src/main/java/lotto/model/Lottos.java
> +    }
unmodified(Immutable) 처리 해야되지 않을까요 ^^?

2023-01-04 07:19 UTC, mkom76 commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(money / 1000);
Constants 클래스에서 상수를 관리하도록 변경하였습니다.
이제부터는 시작 전에 Constants 클래스를 만들어두어야겠다는 생각이 드네요ㅎㅎ.. 자꾸 놓치는 것 같습니다.
감사합니다!

2023-01-04 07:20 UTC, mkom76 commented on src/main/java/lotto/view/InputView.java
> +    }
오.. try catch문 없이도 변환이 가능하겠네요. 좋은 기능 알려주셔서 감사합니다!!

2023-01-04 07:21 UTC, mkom76 commented on src/main/java/lotto/view/InputView.java
> +        catch(Exception e){
변경하였습니다.
option + command + L로 간편하게 리포맷이 되네요.. 신세계입니다. 
컨벤션에 맞추어 작성하되 혹시모르니 마지막에 단축키 사용하는 습관도 가지겠습니다!

2023-01-04 07:22 UTC, mkom76 commented on src/main/java/lotto/view/InputView.java
> +        return input.replaceAll("\\s", "").split(",");
전부 상수화하여 Constants 클래스에서 관리하도록 변경하였습니다.

2023-01-04 07:22 UTC, mkom76 commented on src/main/java/lotto/view/InputView.java
> +        }
👏👏👏👏

2023-01-04 07:25 UTC, mkom76 commented on src/main/java/lotto/view/InputView.java
> +    }
자바도 유용한 라이브러리가 굉장히 많네요,, 좋은 기능들 알려주셔서 감사합니다!!

2023-01-04 07:34 UTC, mkom76 commented on src/test/java/lotto/model/WinnerTest.java
> +        }};
멤버변수와 셋업코드로 해결했습니다!
Q. TDD에서 사용자가 테스트를 쉽게 할 수 있게 input 변경이 쉽게 만드는 것도 고려대상인가요? 아니면 테스트코드는 개발자의 편의대로 만들어도 상관없는걸까요?

2023-01-04 07:34 UTC, mkom76 commented on src/main/java/lotto/model/Lottos.java
> +    }
변경했습니다! 중요한 걸 놓쳤네요.. 꼼꼼하게 봐주셔서 감사합니다!!

2023-01-04 07:35 UTC, mkom76 commented on src/test/java/lotto/model/LottoTest.java
> +            "8,9,10,11,12,13;DEFAULT"}, delimiter = ';')
👍👍👍👍👍

2023-01-04 08:12 UTC, mkom76 commented on src/main/java/lotto/utils/RandomNumbersGenerator.java
> +        }
상수 리스트를 하드코딩으로 초기화하고 해당 로직으로 구현해보았습니다ㅎㅎ
메소드는 가독성이 확실히 좋아졌는데 상수 리스트가 하드코딩인게 마음에 걸리네요.. util성 클래스라 생성자를 사용하기도 애매하다고 생각하고요. 방법이 잘 안떠오릅니다..ㅠㅠ

2023-01-05 00:26 UTC, scolleck commented on src/test/java/lotto/model/WinnerTest.java
> +        }};
고정된 단일 값으로 충분히 검증이 되는 경우는 편의대로 하드코딩해도 무방합니다.

다만, 여러개의 값을 지속적으로 변경해가면서 테스트 해야하는경우 재사용이 용이하게 말씀하신대로 input 변경이 쉽게 염두하여 제작하면 좋습니다

상황에 따라 다른관계로 정답은 없습니다 :)

2023-01-05 02:49 UTC, mkom76 commented
Model: Lotto, Lottos, WinLotto, BonusNumber, RankingResult, Ranking(enum)
View: InputView, OutputView
Controller: LottoController

**Model**

- 로또번호를 int리스트로 가지는 일급객체 개념의 Lotto(validation 추가)

- Lotto객체들을 관리하는 Lottos

- 당첨번호 정보를 담아둔 WinLotto

- 보너스 번호를 감싸는 일급객체 개념의 BonusNumber

- Ranking(enum)을 key로, 각 랭킹에 해당하는 로또의 개수를 value로 만든 해시맵 RankingResult

- 로또 결과 case별로 정보를 모아둔 Ranking enum

수정사항:

- Winner 클래스를 삭제하고 컨트롤러가 모델들과 직접 통신하도록 구현하였습니다. 프로그램 구조가 사용자 입력 -> 출력 -> 사용자 입력 -> 출력 이렇게 4단계로 이루어져 있어 서비스 클래스 하나로는 구현이 불가능하다고 판단했습니다.

- 당첨번호, 보너스번호, 랭킹 결과 해시맵을 클래스로 관리하도록 변경하였습니다. 각 모델에 validation 로직을 추가하였습니다.

**View**

- 사소한 리팩토링만 진행했습니다.

**Controller**

- 모델들과 직접 통신합니다. View객체를 멤버변수로 가지고, Lottos, WinLotto, RankingResult 객체를 메소드에서 선언하여 사용합니다.


**그 외 수정사항**

- 상수들을 패키지로 관리하도록 변경하였습니다.

- 인텔리제이 기능을 사용해 컨벤션에 맞도록 리포맷했습니다.

- 메소드 이름은 가급적 동사부터 시작하도록 변경하였습니다.

2023-01-05 02:50 UTC, mkom76 commented on src/main/java/lotto/controller/LottoController.java
> +        Map<Ranking, Integer> rankingResult = winner.rankingCount(rankings);
반영하였습니다. 다른 로컬 변수들도 최소화하기 위해 클래스 구조 변경을 진행했습니다!

2023-01-05 07:22 UTC, scolleck requested changes
몇가지 간단한 리뷰를 남겨드렸습니다 해당 부분만 반영되면 될 만큼 완성도가 높아졌네요 ^^ 고생하셨습니다.

2023-01-05 07:22 UTC, scolleck commented on src/main/java/lotto/constant/Constants.java
> +    public static final int THOUSAND = 1000;
해당 상수의 명칭은 입력한 금액의 단위를 지칭하는것이 좋지 않을까요?
변수명의경우 가장 적절한 부여는 명칭을 보고 사용성을 알 수 있는것이라고 합니다.

LOTTO_MAX_NUM 의 경우 명칭만 보더라도 해당 값이 로또의 최대 값이라고 알 수 있는것 처럼요 ^^..

2023-01-05 07:22 UTC, scolleck commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(money / Constants.THOUSAND);
receiveMoneyUserInput() 메소드에서 입력된 금액과 단위를 적용해 최종 값을 리턴하고
new lottos(money) 로 간결화 하는게 좋지 않을까 싶습니다 :)

2023-01-05 07:22 UTC, scolleck commented on src/main/java/lotto/controller/LottoController.java
> +        RankingResult rankingResult = new RankingResult(lottos.getRankings(winLotto));
lottos.getRankings 의 경우 불변 리스트 객체를 반환하는데요,
해당 불변객체는 RankingResult 객체를 생성하는 용도로만 사용되는것 같습니다.

이 경우 아에 불변 리스트 객체가 아닌 RankingResult를 생성하여 리턴한다면 어떨까요?

2023-01-05 07:22 UTC, scolleck commented on src/main/java/lotto/model/BonusNumber.java
> +public class BonusNumber {
전반적으로 일급컬렉션을 사용하여 분리할 수있는 모델들을 잘 분리 해주셨습니다 💯

2023-01-05 07:22 UTC, scolleck commented on src/main/java/lotto/model/Lotto.java
> +        return Collections.unmodifiableList(lottoReadOnly);
unmodifiable 과 immutable의 특성을 인지하시고 복사 후 반환을 하셨군요 :)
많이 헷갈리는 내용일텐데 잘 숙지하여 적용해 주셨습니다 💯

2023-01-05 07:22 UTC, scolleck commented on src/main/java/lotto/model/Ranking.java
> +                .filter(ranking -> ranking.count == cnt && ranking.hasBonusNumber == hasBonusNumber)
filter 조건이 두가지가 들어가는 상황으로
필터를 두번 분리하거나, 조건을 메소드 추출하여 보다 직관적이게 알 수 있도록 조치하는것은 어떨까 싶습니다 ~

2023-01-05 07:22 UTC, scolleck commented on src/test/java/lotto/model/LottosTest.java
> +class LottosTest {
getLottos 와 같이 불변객체를 리턴하였다면, 해당 불변객체가 수정이 되지 않는지에 대한 테스트를 추가하는것은 어떨까요?

2023-01-05 07:34 UTC, mkom76 commented on src/main/java/lotto/constant/Constants.java
> +    public static final int THOUSAND = 1000;
2단계 구현하면서 바꿔야되나 고민하던 부분인데 바로 짚어주셔서.. 놀랐습니다!ㅎㅎㅎ
PRICE_OF_LOTTO로 변경하였습니다.
추가: 정확히 1000단위로 입력해야되는게 아니고 되는 만큼 구매가 되는거여서 해당 로직도 수정하였습니다. 요구사항을 오해했네요..

2023-01-05 07:45 UTC, mkom76 commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(money / Constants.THOUSAND);
컨트롤러 마지막 부분에 money를 사용하는 부분이 있어서 Lottos 클래스 생성자에서 연산하는 방식으로 변경하였습니다!

2023-01-05 08:40 UTC, mkom76 commented on src/main/java/lotto/controller/LottoController.java
> +        RankingResult rankingResult = new RankingResult(lottos.getRankings(winLotto));
와우.. 그렇네요. 괜히 한번 더 넘겨주었군요,, 변경하고 테스트코드도 변경하였습니다.

2023-01-05 08:59 UTC, mkom76 commented on src/main/java/lotto/model/Ranking.java
> +                .filter(ranking -> ranking.count == cnt && ranking.hasBonusNumber == hasBonusNumber)
필터를 두번 사용하여 해결했습니다! 스트림 정말 신기하네요ㅎㅎ 많이 공부해보겠습니다ㅎㅎㅎ

2023-01-05 09:11 UTC, mkom76 commented on src/test/java/lotto/model/LottosTest.java
> +class LottosTest {
list add funtion에서 에러가 나는지 판단하도록 하였습니다!
다른 모델들의 테스트에도 추가하였습니다. 불변성 테스트도 잊지 말아야겠네요ㅎㅎ

2023-01-05 09:20 UTC, mkom76 commented
피드백 내용들 반영하고 댓글도 달아두었습니다. 감사합니다!!

2023-01-09 01:58 UTC, javajigi approved these changes
1단계 피드백을 충분히 주고 받은 것으로 파악되어 다음 단계 미션 진행을 위해 대신 merge합니다. 
미션 진행하느라 수고했어요. 💯

2023-01-09 01:59 UTC, merged