[pluto.yun] 로또 1단계
2023newkrew/java-lotto-kakao pull request #14
Opened 2023-01-03 06:00 UTC by tkaltk123

2023-01-05 05:39 UTC, sangnyyy requested changes
이번 미션도 고생하셨습니다!!
코멘트들 달아두었으니 한번 확인 해보시고 반영 부탁드릴게요 :)
제가 코멘트 드린 것들이 꼭 정답은 아니니 고민해보시고 궁금하신 부분 있다면 
추가 코멘트 혹은 DM 으로 언제든 여쭤봐주세요.

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/controller/LottoSimulator.java
> +    private final LottoOutputView outputView = new LottoOutputView();
유연성 또는 테스트 용이성 등을 위해 생성자를 통해서 전달할 수 있도록 하는 것이 좋아보여요!

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/vo/Money.java
> +    }
로또를 사기위한 Count 체크를 Money 객체가 해주는 것이 적절한 책임인지 잘 모르겠습니다.

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/generator/LottoGenerator.java
> +public interface LottoGenerator {
LottoGenerator 라는 인터페이스로 추상화한 부분 좋습니다!

다만, Lotto 생성 시 LottoGenerator 또는 그 구현체인 RandomLottoGenerator 가 왜 필요한지 잘 모르겠습니다.

Lotto 가 생성 시점에 자신만의 LottoNumber 를 만들어서 들고 있으면 좀 더 객체지향적인 코드가 만들어지지 않을까요? LottoGenerator 의 도움을 받을 필요는 없어보입니다.

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/lotto/Lotto.java
> +    public static final int SIZE = 6;
Lotto 의 SIZE 가 전역상수로 여기저기서 의존성을 갖는것은 좋지 못해보입니다.
나중에 값이 변경되어 예기치 못한 사이드이펙트가 이뤄질 수 있어서 private 으로 변경의 여파를 클래스 내부로 줄여주세요.

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/vo/LottoNumber.java
> +    }
위에서 LottoGenerator 부분에 코멘트 드렸듯이 LottoNumber 가 자신의 값을 직접 생성하도록 한다면 
해당 메서드는 필요하지 않을 듯 합니다. 생성시점에 값을 정하도록 변경해보시죠!

p.s. 만약 이 메서드를 사용하는 코드를 유지한다면, NumberPool 은 사실상 1 ~ 45 의 LottoNumber 를 갖는 pool 뿐인데 호출될 떄마다 계속해서 만들어내기보단 캐싱을 해놓는게 성능 상 유리할 것입니다.
원래 pool 이라는 개념이 값비싼 리소스들을 매번 만들기 위한 비용을 줄이기 위해 미리 생성해서 pool 에 담아두고 필요할 때 꺼내쓰는 개념이니까요 ㅎㅎ

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/LottoAnalyzer.java
> +public class LottoAnalyzer {
해당 객체도 유사하게 WinningNumber 가 하는 일(책임)들로 대체할 수 있을 것 같아요.
WinningNumber 가 당첨번호를 알고 있고, LottoBundle 객체가 랜덤으로 생성된 로또들을 알고 있으니 LottoAnalyzer 에서 하는 일들을 대체할 수 있을 것 같아요. 굳이 LottoAnalyzer 라는 중간객체가 있어야 할 이유가 있을까(그정도로 로직이 복잡한가?) 하는 의문이 듭니다.

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/LottoAnalyzer.java
> +                .collect(Collectors.toList());
WinningNumber 가 judge 의 파라미터로 lottoBundle 을 받아서 처리하는 것이 어떨까요?

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/LottoStore.java
> +        Money totalPrice = Money.valueOf(LOTTO_PRICE.longValue() * lottoCount);
LOTTO_PRICE 를 Money 타입으로 정의했는데, 굳이 다시 longValue() 로 값을 뽑아서 생성하는게 어색해보입니다. LOTTO_PRICE 를 long 타입의 상수로 정의해놓던지 혹은 Money 객체에 lottoCount 만큼을 곱하는 연산이 있으면 좋을거 같아요.

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/WinningStatistics.java
> +public class WinningStatistics {
로또 결과를 담기위한 객체 좋네요 👏

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/lotto/LottoBundle.java
> +public class LottoBundle {
일급 컬렉션 사용 👍

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/prize/PrizeMap.java
> +public class PrizeMap {
해당 객체가 어떤 객체인지 네이밍이 너무 추상적이어서 이해하는데 좀 힘들었습니다..
Prize에 해당되는 카운트를 갖는 객체인거죠? 한번 고민하셔서 다시 네이밍을 지어보면 어떨까 싶습니다.
(테스트코드의 설명도 조금 더 친절하게 작성해주시면 리뷰어가 이해하는데 도움이 됩니다.)

2023-01-05 05:39 UTC, sangnyyy commented on src/main/java/lotto/model/prize/PrizeMap.java
> +    }
요런 값은 캐싱해놓아도 좋겠네요. 
(더더욱 Map 이라는 클래스 네이밍과는 안어울리는 기능이긴 하네요 .. ㅠ)

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/LottoAnalyzerTest.java
> +class LottoAnalyzerTest {
analyze() 의 검증 기능은 빠진건가요?

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/LottoAnalyzerTest.java
> +        @DisplayName("당첨 번호가 없을 경우 예외 발생")
예외 케이스에 대한 생성 테스트가 있다면, 정상 케이스에 대한 생성 테스트 또한 존재하면 좋을 것 같아요.

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/LottoStoreTest.java
> +        @DisplayName("로또 생성기가 없을 경우 예외 발생")
예외 케이스에 대한 생성 테스트가 있다면, 정상 케이스에 대한 생성 테스트 또한 존재하면 좋을 것 같아요.

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/WinningNumberTest.java
> +        @DisplayName("당첨 번호와 보너스가 중복될 경우 예외 발생")
예외 케이스에 대한 생성 테스트가 있다면, 정상 케이스에 대한 생성 테스트 또한 존재하면 좋을 것 같아요.

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/WinningStatisticsTest.java
> +        @DisplayName("단일 수익률 확인")
수익률이라고 한다면 % 이지 일텐데 expected 값이 맞는지 궁금합니다.

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/WinningStatisticsTest.java
> +        @DisplayName("종합 수익률 확인")
수익률이라고 한다면 % 이지 일텐데 expected 값이 맞는지 궁금합니다.

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/prize/PrizeMapTest.java
> +        @DisplayName("Prize의 갯수 반환")
테스트가 다소 복잡하여 의도한 바를 파악하기 어렵습니다. @DisplayName 에 좀 더 디테일한 설명이 들어가면 좋겠습니다.

테스트 코드는 해당 객체(SW) 동작의 명세서이기도 하기 때문에 api 문서와 같다고 생각하고 
동작의 디테일을 기재하면 협업자로서 이해에 큰 도움이 됩니다.

2023-01-05 05:39 UTC, sangnyyy commented on src/test/java/lotto/model/vo/MoneyTest.java
> +    }
위에서도 말씀드렸지만 해당 기능의 책임이 Money 에 있는게 합리적인지 다시 한번 고민해보시면 좋겠습니다.

2023-01-05 13:58 UTC, tkaltk123 reviewed
처음부터 다시 작성하는 연습을 하는 도중에 피드백 해주신 내용 반영했습니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/controller/LottoSimulator.java
> +    private final LottoOutputView outputView = new LottoOutputView();
LottoGenerator 제거했습니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/LottoAnalyzer.java
> +public class LottoAnalyzer {
말씀하신것처럼 LottoAnalyzer, WinningNumber를 LottoCompany로 통합했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/LottoAnalyzer.java
> +                .collect(Collectors.toList());
수정했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/LottoStore.java
> +        Money totalPrice = Money.valueOf(LOTTO_PRICE.longValue() * lottoCount);
수정했습니다. Money 객체에 사칙연산을 추가했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/WinningStatistics.java
> +public class WinningStatistics {
감사합니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/generator/LottoGenerator.java
> +public interface LottoGenerator {
랜덤으로 생성하는 부분을 Lotto로 이동했고 LottoGenerator는 제거했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/lotto/Lotto.java
> +    public static final int SIZE = 6;
수정했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/prize/PrizeMap.java
> +public class PrizeMap {
Prize를 LottoRanking으로 수정했고 PrizeMap을 LottoStats로 수정했습니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/prize/PrizeMap.java
> +    }
캐싱하도록 수정했습니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/vo/LottoNumber.java
> +    }
수정했습니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/main/java/lotto/model/vo/Money.java
> +    }
LottoStore로 이관했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/test/java/lotto/model/WinningNumberTest.java
> +        @DisplayName("당첨 번호와 보너스가 중복될 경우 예외 발생")
추가했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/test/java/lotto/model/WinningStatisticsTest.java
> +        @DisplayName("단일 수익률 확인")
수정했습니다!

2023-01-05 13:58 UTC, tkaltk123 commented on src/test/java/lotto/model/prize/PrizeMapTest.java
> +        @DisplayName("Prize의 갯수 반환")
수정했습니다.

2023-01-05 13:58 UTC, tkaltk123 commented on src/test/java/lotto/model/vo/MoneyTest.java
> +    }
수정했습니다!

2023-01-05 14:42 UTC, sangnyyy requested changes
추가 코멘트 작성합니다. 확인 부탁드릴게요!

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/controller/LottoSimulator.java
> +public class LottoSimulator {
거의 전면 쇄신되었군요 ㅎ

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/controller/LottoSimulator.java
> +        return wallet.getTicket();
느낌 상 Store 에 Wallet 을 전달해서 Ticket 을 반환되는게 좀 더 자연스러워 보입니다.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/controller/LottoSimulator.java
> +    private LottoStats createLottoCompanyAndAnalyze(LottoTicket ticket) {
메서드에 명확하게 동작을 표기하는 것은 좋은 습관이라고 생각됩니다.
다만, 한 메서드가 2개의 동작을 하는 것 보다는 한 메서드가 한개의 동작을 하도록 하여 2개의 메서드를 쓰는 것이 좀 더 
클린코드에 가깝다고 생각합니다.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/controller/LottoSimulator.java
> +        return wallet.getProfitRate(totalPrize);
저는 개인적으로 Wallet 보단 이전의 WinningStatics 가 좀 더 와닿는거 같습니다.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/company/LottoCompany.java
> +        }
validate 와 같은 메서드로 추출하면 좋을 것 같아요. 유효성 검사로직이 코드라인의 대부분을 차지하고 있어서 ㅎ

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/company/LottoCompany.java
> +    }
LottoTicket(구 LottoBundle) 객체 내부로 로직이 들어갈 수 있을 것 같아요. 
그러면, LottoCompany 객체와 analyze 기능은 필요하지 않게 됩니다. (앞서 말씀드린 중간객체가 되겠네요)

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/company/LottoRanking.java
> +public enum LottoRanking {
좀 더 직관적인 네이밍이 되어서 좋네요.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/company/LottoStats.java
> +    private final Map<LottoRanking, Long> rankingCounts;
네이밍이 훨씬 직관적이라 좋아요. 고생하셨습니다!
더 나아가서는 일급 컬렉션으로 뽑아낼 수 있겠군요.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/company/LottoStats.java
> +    private final Money totalPrize;
여기도 TotalPrize 객체로 만들어내게 되면 calculate 하는 부분이 TotalPrize 로 이관되겠네요.
그러면 RankingCounts 로부터 TotalPrize를 계산해내는 부분에 대한 테스트 추가도 가능하겠군요.
(현재는 private 으로 막혀있으니..)

검증하고자 하는 부분(테스트)가 private 이라면 객체를 분리하는 것을 고려해보세요. 
객체를 분리해야 하는 시그널이 될 수 있습니다. (SRP)

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoStore.java
> +    }
여기로 이관되었군요 👍

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/LottoWallet.java
> +    private LottoTicket ticket = LottoTicket.of();
Ticket  이 LottoWallet에 굳이 위치해야 하는 이유를 모르겠습니다.
Ticket 이 LottoWallet에 있게됨으로써 해당 객체가 애매모호해지는 것 같아요.
또한, 최초에 생성자 주입이 불가하여 Null객체를 만들어 append 하는 방식을 사용해야 하는데 이부분 또한 찝찝하구요.
Ticket 을 밖으로 뺴고 위에서 말씀드린 바와 같이 LottoStore에 LottoWallet을 제공하여 Ticket 을 받는 플로우로 변경해보시기 바랍니다.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/Money.java
> +    }
연산들을 Immutable 하게 작성하는 습관은 좋습니다. (병렬처리 안정성 등)
다만, 새로 값을 할당하는 등의 이슈가 있어서 필드 값을 final 로 정의하지 못하는 등의 불편함 또한 있습니다.
정답은 없고 트레이드 오프가 있으니 이런 부분도 잘 고민해보시기 바랍니다.

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/store/Money.java
> +    }
divide 연산만 BigDecimal 로 반환형을 갖는 이유가 있으실까요?
일관성이 좀 떨어져보여서요!

2023-01-05 14:42 UTC, sangnyyy commented on src/main/java/lotto/model/ticket/SingleLottoNumber.java
> +public class SingleLottoNumber implements Comparable<SingleLottoNumber>{
Comparable 을 구현했다는 것은 정렬을 써먹기 위함인데, 저는 정렬 관련된 사용처를 보지 못했습니다.
혹시 이유가 있으실까요? (제가 잘못보았을 수도 있습니다 ㅠ)

2023-01-05 14:46 UTC, sangnyyy approved these changes
리뷰가 다소 사소한 듯 하여, 일단 머지하겠습니다. 다음 미션에서 마저 반영 부탁드릴게요.
이번 미션도 고생 많으셨습니다!! 첫 미션 진행때보다 실력이 많이 일취월장 하신 듯 하네요 👏👏👏

2023-01-05 14:46 UTC, merged

2023-01-08 15:09 UTC, tkaltk123 reviewed
피드백은 step2에 반영했습니다!

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/company/LottoCompany.java
> +        }
수정했습니다

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/company/LottoCompany.java
> +    }
analyze를 LottoTicket으로 이관했고 LottoCompany를 WinningNumber로 다시 수정했습니다.

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/ticket/SingleLottoNumber.java
> +public class SingleLottoNumber implements Comparable<SingleLottoNumber>{
로또 번호를 출력할때 정렬이 안되있어서 정렬 후 출력하려고 구현했습니다!

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/controller/LottoSimulator.java
> +        return wallet.getTicket();
수정하다보니 Wallet이 애매해져서 제거하고 Store가 Money를 직접 받는 것으로 변경했습니다.

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/controller/LottoSimulator.java
> +    private LottoStats createLottoCompanyAndAnalyze(LottoTicket ticket) {
수정했습니다.

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/controller/LottoSimulator.java
> +        return wallet.getProfitRate(totalPrize);
LottoReceipt라는 객체를 추가해 ProfitRate를 계산하는 부분을 이관했습니다.

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/company/LottoStats.java
> +    private final Map<LottoRanking, Long> rankingCounts;
수정했습니다!

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/company/LottoStats.java
> +    private final Money totalPrize;
RankingCounts를 일급 컬랙션으로 분리해 totalPrize를 계산하는 코드를 이관했습니다.

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/store/LottoWallet.java
> +    private LottoTicket ticket = LottoTicket.of();
LottoStore가 LottoTicket과 LottoReceipt를 가지는 PurchaseResult를 반환하도록 수정했습니다.

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/store/Money.java
> +    }
Money를 수정하는 부분을 제거하고 Immutable 연산을 유지하는 것으로 결정했습니다. 조언 감사합니다!

2023-01-08 15:09 UTC, tkaltk123 commented on src/main/java/lotto/model/store/Money.java
> +    }
돈을 돈으로 나누면 단위가 없는 수치만 나오는 것이 적절하다고 판단했습니다!
(ex: 2000원 / 1000원 = 2)