[red.is] Step1
2023newkrew/java-lotto-kakao pull request #15
Opened 2023-01-03 06:00 UTC by coolofficials

에디, 잘 부탁드립니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/controller/LottoController.java
> +    private final OutputView outputView = new OutputView();
👍

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/Issuer.java
> +    }
IntStream.range 를 활용하면 좋을 것 같습니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/Issuer.java
> +        List<Integer> numbers = new ArrayList<>(numberPool.subList(0, LottoSettings.MAX_LENGTH.getValue()));
subList를 바로 사용하지 않으신 점 좋네요.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/Lotto.java
> +                .size() == numbers.size();
numbers.stream().allMatch() 를 활용하면 좋을 것 같습니다.

stream 코드를 읽지 않고도, 무엇을 검사했다라는 것을 알기 쉽게 result가 보다 더 의미있는 변수명이면 좋을 것 같습니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/Lotto.java
> +    }
취향)
저는
```java
LottoSettings.MIN_RANGE.getValue() <= number && 
number <= LottoSettings.MAX_RANGE.getValue()
```
로 적으면 읽기 쉬운것같더라고요. 개인취향입니다 ㅎ

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/LottoList.java
> +    }
nit: LottoList와 LottoList의 union은 LottoList여야할 것 같다고 생각이 들었어요.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/LottoSettings.java
> +}
Settings를 별도의 클래스로 뺴주신 건 아주 좋습니다.

다만 enum 보다는 일반적인 클래스면 어떨까하는 생각이 들어요.
지금은 모든 Setting 값이 숫자여서 하나의 enum에 담을 수 있지만, 그렇지 않은 경우도 많을 것 같습니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/LottoStatistics.java
> +    }
nit

일급컬렉션을 사용하는 것의 장점 중 하나가 생성자 및 put, get 등에서 0으로 초기화 및 getOrDefault의 사용을 강제할 수 있는 것이라고 생각합니다.
생성자에서 전부 0으로 초기화를 강제했다면 put get 에서는 OrDefault를 체크하지 않아도 될 것 같고, 그 반대도 가능할 것 같습니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/MatchedResult.java
> +    }
nit : 

자바의 equals 는 제대로 구현하기 까다롭기로 악명높은데요,
일반적으로 getClass()를 통한 equals 비교보다는 instaceof를 사용하는 것이 선호됩니다.
(자동생성하신 거라면 아마 instaceof를 사용하는 옵션이 있었던 걸로 압니다)

참고)
https://stackoverflow.com/questions/596462/any-reason-to-prefer-getclass-over-instanceof-when-generating-equals

https://stackoverflow.com/questions/27581/what-issues-should-be-considered-when-overriding-equals-and-hashcode-in-java/32223#32223

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/WinningNumbers.java
> +    }
MainNumbers는 안 만들어도 괜찮지 않을까하는 생각이 듭니다.

WinningNumbers 클래스 밖으로 나가지 않는 것 같아요.
그리고 WinningNumbers라는 일급컬렉션안에서만 처리해주면 checkRange도 재활용할 수 있고, 좋을 것 같습니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/view/OutputView.java
> +                );
nit

LOSE 아닐 경우, 결과를 출력한다라는 로직도 테스트되면 좋을 것 같아요.
LottoStatistics에서 getWInningResult 같은 메소드를 제공해주면 어떨까 싶습니다.

2023-01-03 09:06 UTC, eddy-oum commented on src/main/java/lotto/model/LottoResult.java
> +    LOSE(List.of(0, 1, 2), List.of(true, false), 0);
LottoResult를 이넘으로 관리하는 것은 일반적인 로또게임에서라면 아주 좋은 것 같아요.
다만 LottoSettings로 MAX_LENGTH를 변경할 수 있는 환경에서는 이넘의 장점보다는 단점이 더 커질 것 같습니다.

setting에 따라서는 ```new MatchedResult(100, true)```도 가능할텐데요, 이 enum과 match 해보면 익셉션이 발생할 것 같습니다.

LottoResult와 MatchedResult가 합쳐지면 좋을 것 같아요. 유동적으로 결과를 생성할 수도 있고, LottoResult에서 MatchedResult의 내부 상태에 많이 의존하고 있기때문입니다.

```LottoResult::match``` 내부에서
```java
.filter(lottoResult -> lottoResult.mainMatchCountCase.contains(matchedResult.getMatchedCount()))
.filter(lottoResult -> lottoResult.bonusMatched.contains(matchedResult.getBonusNumberMatched()))
```
등으로 matchedResult의 내부상태를 getter로 많이 읽어오고 있는데요, 이건 두 클래스가 하나로 합쳐지면 좋다는 의미라는 생각도 들어요.

2023-01-04 02:53 UTC, coolofficials commented
@eddy-oum 혹시 어느 정도까지 review address하고 step2를 진행하는게 좋을까요? 모두 address 하고 진행하는지, 일단 merge 하고 step2에서 해당 리뷰들을 address 하는게 좋을지 궁금합니다. [이 리뷰](https://github.com/next-step/java-lotto-kakao/pull/15#discussion_r1060384035) 외에는 다 작은 변경사항인 것 같습니다.

2023-01-04 06:50 UTC, eddy-oum commented
@coolofficials step 2의 요구사항을 제가 잘 몰라서, red 편하신 방법을 알려주시면 좋겠습니다.
step 2에서 작업하면서 자연스럽게 적용할 수 있는 부분은 step 2에서 해주시고, step 2 가기 전에 금방 작업하실 수 있는 부분이 있다면 이 pr에서 해주시면 좋겠습니다. (request change는 하지 않을게요)

2023-01-04 11:29 UTC, eddy-oum commented on src/main/java/lotto/controller/LottoController.java
> +        }
lottoList의 두 가지 상태 (length, get(i))를 읽어서 하는 작업이네요.

LottoList를 일급컬렉션으로 만들었으나 동작자체는 일반적인 리스트랑 크게 차이가 없다고 느껴집니다.
저라도 이렇게 구현할 것 같긴 합니다만, getter로 상태 조회하는 것을 지양하는 만큼,
```
List<LottoResult> results = LottoList.getResult(winningNumbers)
``` 
같이 LottoList에게 명령을 보내는 방식이 되면 어떨까 생각이듭니다.

2023-01-04 11:31 UTC, eddy-oum reviewed
LottoList의 기능에 대해서 간단한 코멘트를 추가하였습니다.

2023-01-04 11:35 UTC, eddy-oum requested changes

2023-01-04 11:35 UTC, eddy-oum commented on src/main/java/lotto/controller/LottoController.java
> +
lottoList의 두 가지 상태 (length, get(i))를 읽어서 하는 작업이네요.

LottoList를 일급컬렉션으로 만들었으나 동작자체는 일반적인 리스트랑 크게 차이가 없다고 느껴집니다.
저라도 이렇게 구현할 것 같긴 합니다만, getter로 상태 조회하는 것을 지양하는 만큼,

List<LottoResult> results = LottoList.getResult(winningNumbers)

같이 LottoList에게 명령을 보내는 방식이 되면 어떨까 생각이듭니다.

2023-01-04 11:35 UTC, eddy-oum commented on src/main/java/lotto/model/LottoResult.java
> +    LOSE(List.of(0, 1, 2), List.of(true, false), 0);
LottoResult를 이넘으로 관리하는 것은 일반적인 로또게임에서라면 아주 좋은 것 같아요.
다만 LottoSettings로 MAX_LENGTH를 변경할 수 있는 환경에서는 이넘의 장점보다는 단점이 더 커질 것 같습니다.

setting에 따라서는 new MatchedResult(100, true)도 가능할텐데요, 이 enum과 match 해보면 익셉션이 발생할 것 같습니다.

LottoResult와 MatchedResult가 합쳐지면 좋을 것 같아요. 유동적으로 결과를 생성할 수도 있고, LottoResult에서 MatchedResult의 내부 상태에 많이 의존하고 있기때문입니다.

LottoResult::match 내부에서

.filter(lottoResult -> lottoResult.mainMatchCountCase.contains(matchedResult.getMatchedCount()))
.filter(lottoResult -> lottoResult.bonusMatched.contains(matchedResult.getBonusNumberMatched()))

등으로 matchedResult의 내부상태를 getter로 많이 읽어오고 있는데요, 이건 두 클래스가 하나로 합쳐지면 좋다는 의미라는 생각도 들어요.

2023-01-04 11:38 UTC, merged

2023-01-05 02:08 UTC, coolofficials commented on src/main/java/lotto/model/Lotto.java
> +    }
반영 완료했습니다