[russell.yoo] 로또 1단계 제출
2023newkrew/java-lotto-kakao pull request #17
Opened 2023-01-03 06:04 UTC by yooj929

안녕하세요 마리벨! 러셀입니다.

약간 늦게 제출하여 죄송합니다. 금일 화요일 오후 3시까지 제출이 원칙이라 지금 제출하겠습니다.
고칠게 많을 것으로 생각되고, 지속적으로 고치고 있습니다. 저번에도 좋은 피드백 해주셔서 감사합니다.
오늘 좋은하루 되세요!!

2023-01-03 10:37 UTC, Hyunji-Yoo commented on src/main/java/lotto/view/OutputMessage.java
> +public enum OutputMessage {
대칭되는 상수집합을 이늄으로 정의하니 역할이 명확하고 좋네요 👍

2023-01-03 10:39 UTC, Hyunji-Yoo commented on src/main/java/lotto/view/OutputMessage.java
> +    PRINT_READ_PRICE("구입금액을 입력해 주세요."),
이늄 식별자는 명사형으로 명명하는게 더 적합할 것 같습니다.

2023-01-03 10:46 UTC, Hyunji-Yoo commented on src/main/java/lotto/view/OutputView.java
> +    public void printReadLottoAnswerNumbers() {
메서드명을 보다 명시적으로 명명하면 좋겠어요.
해당 메서드는 "지난 주 당첨 번호를 입력해 주세요."를 출력하는 것 같은데, 매서드명만 보고는 유추가 안되네요.
`printInputRequestOfWinningNumber`처럼 메서드명만 보고도 해당 메서드의 기능을 이해할 수 있도록 명명하면 어떨까요?
(프로그래밍에서 가장 어려운 것 중 하나가 네이밍이라고 하는만큼 항상 어려운 일이지만요 😂)

2023-01-03 10:48 UTC, Hyunji-Yoo commented on src/main/java/lotto/controller/LottoController.java
> +    private void setLottoAnswer() {
네이밍이 부적합한 것 같아요.
get/set으로 시작하는 함수는 자바빈의 getter/setter를 연상시키는 컨벤션입니다.
메서드명만 보면 LottoController 내에 `lottoAnswer` 필드가 있어야 할 것 같아보여요.

2023-01-03 10:48 UTC, Hyunji-Yoo commented on src/main/java/lotto/controller/LottoController.java
> +    private int getLottoCount() {
이 메서드와 위와 동일합니다.
보다 구체적으로 메서드의 역할을 유추할 수 있도록 네이밍 해보면 어떨까요?

2023-01-03 10:53 UTC, Hyunji-Yoo commented on src/main/java/lotto/domain/LottoConstants.java
> +public enum LottoConstants {
음 이늄은 일반적으로 동일한 위상을 가진 상수를 정의할 때 적합합니다.
`enum Color { RED, ORANGE, GREEN }`처럼요.
로또와 연관이 있다는 공통점이 있지만 위상이 동일하지 않은 경우는 일반 상수로 정의하는게 더 적합하지 않을까 싶어요.

2023-01-03 11:02 UTC, Hyunji-Yoo commented on src/main/java/lotto/rankingpolicy/DefaultRankingPolicy.java
> +    private final Map<DefaultLottoResult, LottoRank> lottoResultLottoRankMap = new HashMap<>();
변수 선언 시에는 구체타입보다 추상타입을 사용하는게 보다 유연합니다. 
- 구체타입: DefaultLottoResult
- 추상타입: LottoResult

2023-01-03 11:04 UTC, Hyunji-Yoo commented on src/main/java/lotto/rankingpolicy/DefaultRankingPolicy.java
> +        return lottoResultLottoRankMap.getOrDefault(lottoResult, SIXTH);
`getOrDefault()`를 사용해서 버그를 줄일 수 있겠네요 👍

2023-01-03 11:58 UTC, Hyunji-Yoo requested changes
러셀 안녕하세요.
이전 과제보다 전반적인 구성과 코드가 더 깔끔해진 것 같아요 👍
몇가지 코멘트 남겼는데요, 반영하고 재리뷰 요청 주시면 확인 하겠습니다.
(PR메인 화면에서 제 이름 옆에 있는 re-request review 버튼 눌러서 재요청하시면 되요!)

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/main/java/lotto/domain/DefaultLottoResult.java
> +            throw new IllegalArgumentException(INVALID_LOTTO_RESULT_INPUT_EXCEPTION);
💬 NIT
`Lotto result에 잘못된 입력이 주어졌습니다.` 메세지도 좋은데,
예외처리 시 메세지는 EXPECTED, ACTUAL, CONTEXT로 구성하여 보여주면 정보가 더 명확합니다.

ex) 
> EXPECTED: 0보다 크거나 같은 수
> ACTUAL: 음수
> CONTEXT: matchCount

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/main/java/lotto/domain/LottoNumbers.java
> +        lottoNumbers = new ArrayList<>(lottoNumbers);
혹시 line 19에서 매개변수 lottoNumbers를 다시 ArrayList로 만들어서 넣은 이유가 있을까요?
defensive copying을 의도한거라면 line 22에서 해도 될 것 같아서요ㅎㅎ

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/main/java/lotto/domain/LottoNumbers.java
> +        validateCount(lottoNumbers);
밸리데이션 항목별로 메서드를 분리하니 의도가 명확해서 좋네요 👏

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/main/java/lotto/domain/LottoRank.java
> +    public boolean isRequiredBonus() {
불타입의 getter는 get 대신 is로 시작한다는 컨벤션에 맞게 명명해주셨네요 👍

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/main/java/lotto/domain/LottoResultMessage.java
> +    public static String hasBonusString(LottoRank lottoRank, int count) {
내부에서만 사용한다면 접근제어자가 public일 필요는 없을 것 같아요.

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/main/java/lotto/view/InputView.java
> +            throw new IllegalArgumentException(REQUIRED_NUMBER_EXCEPTION_MESSAGE.getMessage());
💬 NIT
: 예외를 던질 때는 cause-chain를 고려하면 좋아요ㅎㅎ
위에서 처럼 NumberFormatException을 받고 그냥 IllegalArgumentException을 대신 던지면, 예외스택추적에서 NumberFormatException는 제외가 됩니다. 
`throw new IllegalArgumentException(REQUIRED_NUMBER_EXCEPTION_MESSAGE.getMessage(), e);`
요렇게 하면 스택추적에 NumberFormatException가 포함되서 원인파악에 더 용이합니다.

2023-01-03 11:58 UTC, Hyunji-Yoo commented on src/test/java/lotto/domain/LottoTest.java
> +        LottoNumbers lottoAnswerNumbers = new LottoNumbers(List.of(1,2,3,4,5,6));
💬 NIT
: 테스트 코드가 길고 복잡해질 경우에는 명시적으로 구조를 잡아주면 좋아요.
일반적으로 아래와 같은 구조로 테스트코드를 가독성있게 바꿀 수 있어요.
```
// given
LottoNumbers lottoAnswerNumbers = new LottoNumbers(List.of(1,2,3,4,5,6));
Lotto lotto = new Lotto(lottoAnswerNumbers);
LottoAnswer lottoAnswer = new LottoAnswer(lottoAnswerNumbers, 7);
Method getMatchCount = Lotto.class.getDeclaredMethod("getMatchCount", LottoNumbers.class);
getMatchCount.setAccessible(true);

// when
int matchCount = (int) getMatchCount.invoke(lotto, lottoAnswer.getLottoNumbers());

// then
assertThat(matchCount).isEqualTo(6);
```

2023-01-04 04:08 UTC, yooj929 commented
안녕하세요 마리벨!

리뷰 반영하여 다시 리뷰요청 드립니다.

과제를 진행하면서 궁금한 사항이 있어 남깁니다.
- 해당 과제에서 DefaultLottoResult에서 boilerplate code인 equals와 hashCode를 상황에 맞게 변경하여  과제를 진행하였는데 이러한 방법이 적절한지 궁금합니다.

꼼꼼한 리뷰 감사합니다! 마리벨

2023-01-04 07:02 UTC, Hyunji-Yoo approved these changes
질문주신 내용에 대해 답변을 드리면 실무에서는 어노테이션프로세서를 이용해서 보일러플레이트 코드 작업에 들어가는 노력을 최소화하고 있습니다. 😉
다만 과제에서는 외부 라이브러리나 프레임워크의 도움 없이 순수자바로 MVC 앱을 구현하는 만큼 노가다(?)성이라도 정석대로 작업하시는게 더 좋을 것 같아요ㅎㅎ
코멘트 반영하시느라 고생하셨습니다👏 머지할게요!

2023-01-04 07:03 UTC, merged