[baker.gus] 로또 1단계
2023newkrew/java-lotto-kakao pull request #18
Opened 2023-01-03 06:04 UTC by jgus52

nio 안녕하세요, 새해 복 많이 받으세요~
로또 1단계 PR 요청드려요.

일급컬렉션을 이용하는 걸 신경썼습니다.
LotteryMatch에서 5개 매칭에서만 bonusNumber을 체크해서 생성자에서 5개 매칭일 때만 처리했는데, 괜찮은 방법인지 조언 좀 부탁드려요.
리뷰 항상 감사합니다.

2023-01-03 08:31 UTC, jgus52 reviewed
하다보니 자꾸 수정하게 되네요 죄송해요 여기까지만 하겠습니다

2023-01-03 15:13 UTC, sehan requested changes
안녕하세요. baker 😊

객체역할 분리를 위해 일급객체, 일급컬랙션을 적극적으로 적용한 부분들이 인상적입니다. 
그래서 이번에는 객체지향설계 관점에서 개선해보면 좋을거 같은 코드들에 코멘트를 남겼습니다. 객체들의 내부 상태를 꺼내어 로직을 풀어나가는 대신 객체에게 도움을 요청하는 관점으로  개선해보면 좋겠습니다. 

좀 더 객체지향적인 코드를 위해 개선요청 드립니다. 😊

2023-01-03 15:13 UTC, sehan commented on src/main/java/lotto/LotteryNumbers.java
> +    }
로또번호 중복을 체크할 수 있는 또다른 방법으로 뭐가 있을까요?
numbers 의 Collection 타입으로 중복을 허용하지 않는 타입을 사용해보는 것도 생각해 볼 수 있습니다. Collection 타입의 속성을 사용할때는 List 외에 더 적합한 것도 있는지 고려해보면 좋을거 같아요 😊

2023-01-03 15:13 UTC, sehan commented on src/main/java/lotto/LotteryGenerator.java
> +}
autoGenerate 의 매소드의 역할이 많습니다. 
매소드명으로 역할을 추측해보면 자동으로 로또번호를 생성해서 로또 객체 하나를  return 해줄 것으로 기대 했습니다.

하지만, 실제로는 
1. 추첨할 로또공(1~46) 생성
2. buyer 가 로또를 살 돈이 있으면 로또생성
3. 생성한 로또는 buyer 객체에 추가
4. 돈이 부족할때 까지 로또 생성

(개선요쳥) 
autoGenerate() 메소드의 역할을 분리해서 자동로또 생성 역할에 집중할 수 있게 개선해보면 좋겠습니다.  
이런 개선작업을 시도해보는건 객체지향원칙 SOLID 중 SRP 에 대한 고려를 해보기 위함입니다.

2023-01-03 15:13 UTC, sehan commented on src/main/java/lotto/LotteryResult.java
> +    }
lottery 의 번호를 getLotteryNumber() 로 꺼내서 bonusNumber 가 포함되어 있는지  확인할 수도 있지만 좀 더 객체지향적인 접근은 lottery 객체에게 bonusNumber 와 일치하는 번호가 있는지 물어보는 것입니다.  

(개선요청)
lottery 가 가진 번호를 꺼내 볼 필요 없이 lottery 객체에게 요청하는 방향으로 개선해 보면 좋겠습니다.

2023-01-03 15:13 UTC, sehan commented on src/main/java/lotto/LotteryResult.java
> +        }
lottery 에게 당첨번호를 알려주고 일치하는 번호 갯수를 알려달라고 해보는건 어떨까요?

2023-01-03 15:13 UTC, sehan commented on src/main/java/buyer/Buyer.java
> +    }
Buyer 가 구매한 로또들을 getter 로 제공하게 되면 Buyer 외부에서 Lotteries.addLottery() 메소드를 호출하여 구매한 로또가 변경될 위험이 있습니다. 가지고 있는 budget 보다 더 많은 로또를 가질 수 도 있기 때문입니다. 

(개선요청)
buyLottery() 매소드를 통해서 구매하지 않는 로또가 추가될 수 없도록 개선해 주세요

2023-01-03 15:13 UTC, sehan commented on src/main/java/buyer/BuyerResult.java
> +    }
BuyerResultTest 에서만 사용되고 있습니다. 테스트작성을 위해 추가된 메소드 라면 삭제하는것이 좋습니다.

2023-01-03 15:13 UTC, sehan commented on src/test/java/buyer/BuyerProfitTest.java
> +    }
수익률 테스트를 위해 Buyer, LotteryResult, BuyerResult 객체가 사용되고 있습니다.

수익률을 계산하는데 필요한 입력을 생각해보면 구매금액, 순위별 당첨된 로또수, 순위별 당첨금 을 입력으로 주면 수익률을 계산할 수 있을거 같습니다.  각 객체간 책임이 잘 나누어져 있는지 고민해 봐야합니다. 여기서도 SRP 관점에서의 고민이 필요해 보입니다.

2023-01-03 15:21 UTC, sehan commented
> nio 안녕하세요, 새해 복 많이 받으세요~ 로또 1단계 PR 요청드려요.
> 
> 일급컬렉션을 이용하는 걸 신경썼습니다. LotteryMatch에서 5개 매칭에서만 bonusNumber을 체크해서 생성자에서 5개 매칭일 때만 처리했는데, 괜찮은 방법인지 조언 좀 부탁드려요. 리뷰 항상 감사합니다.

제가 이해한 바로는 LotteryMatch 는 로또순위를 결정하는 조건을 명세하기 위한 객체로 이해하고 있습니다.  그렇기 때문에 bonusMatch = true 를 설정할수 있는 상황을 matchCount = 5 인 경우로 제한하는 로직은 불필요해 보입니다. 
즉,  LotteryMatch 를 사용하는 Rank 객체에서 로또순위 결정조건에 따라 LotteryMatch 를 생성해서 사용하면 되기 때문입니다.  로또순위 결정조건에 4개의 번호가 일치하고 보너스 번호가 일치하는 순위가 추가되면 LotteryMatch 코드는 수정없이 Rank 에 enum 만 추가하면 되기 때문입니다.

2023-01-04 01:00 UTC, jgus52 commented
개선사항 참고해서 진행해봤습니다.

2023-01-04 03:44 UTC, sehan approved these changes
개선요청내용을 잘 반영해주셔 고맙습니다.
테스트코드 리팩토링을 통해 displayName 도 더 명확해지고 비지니스 로직들도 도메인객체들에게 위임되어 보다 객체지향적인 개선이 이루어 졌습니다.  👏👏👏

로또 1단계 미션은 여기서 merge 하도록 하겠습니다. 2단계에서도 지속적인 리팩토링 기대하겠습니다.
고생하셨습니다.

2023-01-04 03:44 UTC, sehan commented on src/main/java/lotto/LotteryResult.java
> +    }
로또 순위를 결정하는 로직이 각 객체로 역할분담되었네요 👍

2023-01-04 03:44 UTC, sehan commented on src/main/java/lotto/Lottery.java
> +    }
SRP 측면에서 로또번호를 자동생성해주는 로직을 기본생성자에 추가하는 것보다는 로또번호 자동생성 객체를 별도로 유지하는것이 더 좋지 않을까요?

별도로 분리하면 로또번호 자동생성 로직 변경시 변경해야 하는 영향범위가 로또번호자동생성기로 제한 되기 때문입니다.

2023-01-04 03:44 UTC, sehan commented on src/main/java/buyer/BuyerProfit.java
> +    }
테스트코드에서만 사용되고 있습니다. 혹 테스트를 위한 생성자라면 삭제하는게 좋습니다.

2023-01-04 03:44 UTC, sehan commented on src/test/java/buyer/BuyerProfitTest.java
> +    }
lotteryCount 가 0 이 되면 구매자의 수익률이 정상적으로 나올까요?
구입금액이 로또가격보다 작으면 lotteryCount 가 0 이 되는 상황이 발생합니다.
임계치 값 테스트로 작성 해주세요

2023-01-04 03:45 UTC, merged