[Ayaan.jun] 1단계 - 로또 자동, 리뷰 요청드립니다!
2023newkrew/java-lotto-kakao pull request #25
Opened 2023-01-03 06:41 UTC by Neurumaru

1단계 - 로또 자동, 리뷰 요청드립니다!

2023-01-03 09:26 UTC, hayden-ii requested changes
지난 리뷰 놓쳐서 죄송합니다 ㅠㅠ;; 로또 과제 수고하셨습니다. 몇 가지만 확인 부탁드립니다

2023-01-03 09:26 UTC, hayden-ii commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
LottoNumber과 LottoNumbers 클래스 이름이 좀 더 명확하게 구별가능하면 혼동을 줄일 수 있을것 같은데 어떻게 생각하시나요? (LottoTicket 과 LottoTickets 도...)

2023-01-03 09:26 UTC, hayden-ii commented on README.md
> +## 기능 목록
기능 목록 잘 적어주셨는데, 좀 더 보기 쉽게 구조화시킬 수 있지 않을까요? 예를 들면 예외처리에 대한 항목은 한 칸 옆으로 민다거나... 😄

2023-01-03 09:26 UTC, hayden-ii commented on src/main/java/lotto/domain/LottoResult.java
> +
엔터가 하나 더 들어가있네요

2023-01-03 09:26 UTC, hayden-ii commented on src/main/java/lotto/domain/NumberSelectStrategy.java
> +public interface NumberSelectStrategy {
strategy interface와 strategy는 별도의 디렉토리로 분류하는게 더 깔끔하지 않을까요?

2023-01-03 09:26 UTC, hayden-ii commented on src/test/java/lotto/LottoDispenserTest.java
> +    public void issue_lotto_ticket_by_price(int price, int number) {
snake case 로 함수명 작성하신 이유가 있으실까요?

2023-01-03 09:26 UTC, hayden-ii commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static final int LOTTO_TICKET_PRICE = 1000;
상수를 변수로 만들어서 사용 👍

2023-01-03 09:26 UTC, hayden-ii commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
view 분리 👍

2023-01-03 09:26 UTC, hayden-ii commented on src/test/java/lotto/LottoNumbersTest.java
> +    @DisplayName("6개의 중복되지 않은 숫자 배열 생성")
테스트 케이스에 대한 설명 좋네요! 👍

2023-01-03 09:46 UTC, Neurumaru commented on src/test/java/lotto/LottoDispenserTest.java
> +    public void issue_lotto_ticket_by_price(int price, int number) {
코딩 중에 습관적으로 언더바를 사용했었습니다. 중간에 알아채서 일단은 일관성있게 해두고 추후에 리펙토링 하려했었는데 놓쳤었네요... 바로 수정하겠습니다!

2023-01-03 09:48 UTC, Neurumaru commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
복수형으로 사용하니 과제를 진행하면서도 조금 혼동이 되었던것 같습니다. 바꾸는게 더 좋은 방법 같습니다. 혹시 복수형 대신 ~List와 같은 형태로 접미사를 붙이는 것은 괜찮을까요?

2023-01-03 09:55 UTC, Neurumaru commented
재 리뷰 요청 드립니다!
코멘트 보면서 대부분 수정해야될것 같아서 말씀하신 부분 수정했습니다!!

- 복수형 이름 대신 List접미사 사용
- README 구조화
- 필요없는 엔터 삭제
- 숫자 선택 전략을 별도의 디렉토리로 리펙토링

2023-01-04 02:17 UTC, hayden-ii approved these changes
수고하셨습니다 각 요청을 담당하는 클래스를 잘 구분해서 작성해주셨고 README 도 깔끔하게 정리해주셨습니다 다음도 잘 부탁드려요 👍

2023-01-04 02:17 UTC, merged

2023-01-04 04:27 UTC, Neurumaru commented
리뷰 해주셔서 감사합니다~! 새해 복 많이 받으세요!