[bryan.ko] 로또 1단계
2023newkrew/java-lotto-kakao pull request #28
Opened 2023-01-03 06:56 UTC by SJGeeKo

- 현실 세계에서 일어나는 실제 로또 구매 과정을 떠올리며 도메인 설계를 진행하였습니다.
- 시간에 쫓겨 변수나 메서드의 이름을 완전히 만족스럽게 정하지 못해 가독성이 다소 떨어지는 부분도 존재한다고 생각합니다.
- 2단계를 진행하며 좀 더 나은 네이밍으로 변경해보도록 하겠습니다.
- TDD를 연습해보고자 하는 마음에 최초에는 getter를 최대한 열지 않으면서 개발을 진행했습니다만 마지막으로 사용자 입력 및 출력을 담당하는 LottoView 클래스를 구현하는 과정에서 getter들을 다수 열게 되었습니다.

리뷰 잘 부탁드립니다. 항상 감사드립니다!

2023-01-04 00:55 UTC, matt-jylee requested changes
로또 1단계를 하시느라 수고하셨습니다.
역시 이전보다 훨씬 좋은 코드를 작성하신것 같습니다.
(혹시 사용한 스캐너를 닫는 부분은 리팩토링 시 사라진 걸까요?)

제가 작성한 리뷰를 보시고 조금만 더 개선하는 연습을 해볼까요?!

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/lotto/view/LottoView.java
> +        System.out.println(message);
에러의 경우 선택적으로 System.err.println 을 이용할 수 있습니다.

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/lotto/domain/LottoBall.java
> +    public static final int MAXIMUM_VALUE = 45;
공개/비공개 가시성에 대해 한번 더 생각해보시면 좋겠습니다.

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/lotto/domain/LottoNumberPicker.java
> +    }
자바의 스트림을 연습하고 싶으시다면
이 부분을 간결하게 표한할 수 있는 방법을 찾아보세요~
즐거움 + 1이 될것 같네요!

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/lotto/domain/LottoTicket.java
> +public class LottoTicket {
LottoTicket을 개선해 볼까요?!
이 개선은 많은 부분의 변화를 가져옵니다.

중요하게 생각하는 것은 lottoBalls입니다.

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/lotto/domain/Money.java
> +public class Money {
혹시 Money 클래스 내의 코드에 오류가 없을까요?

2023-01-04 00:55 UTC, matt-jylee commented on README.md
> +총 수익률은 0.35입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)
이것은 아마 문제(요구사항)가 1을 기준으로 가이드 되었기 때문인 것 같은데요.
가능하면 이 부분도 개선해 볼까요?

2023-01-04 00:55 UTC, matt-jylee commented on src/test/java/lotto/domain/LottoTicketTest.java
> +        //given
사람에 따라서는 given when then 또는 arrange assert act 등의 구문을 굳이 주석으로 남기는 것을 권장하지 않을 수 있습니다.
선택적인 문제이고, 줄 바꿈으로 영역을 구분한다던가 하는 방법도 가능합니다.

결론적으로, 보기가 한 결 수월해졌습니다!

2023-01-04 07:17 UTC, SJGeeKo commented on src/main/java/lotto/domain/LottoNumberPicker.java
> +    }
stream api 중 limit을 사용하는 방식으로 보다 간결하게 수정해보겠습니다!

2023-01-04 07:18 UTC, SJGeeKo commented on src/main/java/lotto/domain/LottoBall.java
> +    public static final int MAXIMUM_VALUE = 45;
public으로 할 이유가 없는데 저나 페어나 모두 실수한 것 같습니다ㅠㅠ 이 부분 접근제어자는 private으로 변경하겠습니다.

2023-01-04 07:28 UTC, SJGeeKo commented on src/main/java/lotto/view/LottoView.java
> +        System.out.println(message);
피드백 감사합니다.
- `out` 대신 `err`를 사용하는 경우 붉은색으로 메시지가 표시되어 콘솔에서 더욱 도드라지는 효과가 있음을 확인했습니다.
- 그러나 해당 메서드는 주로 사용자가 잘못된 입력값을 넣은 경우(ex: 구매금액에 대한 입력으로 "abc"입력)에 해당 입력값이 왜 잘못됐는지에 대한 정보를 주기 위해 작성하였습니다. 해당 메서드가 호출된 이후에는 정확한 값을 받기 위해 값 입력을 다시 요청하게 됩니다.
- 그런데 `System.out`과 `System.err`를 혼용하는 경우 둘의 출력 순서가 보장되지 않는 문제가 있습니다(원인 파악 필요). 두 메시지의 출력 순서가 보장되지 않는다면 사용자가 혼란스러울 것 같다는 생각이 들었습니다.
- 따라서 이번에는 `System.err`을 사용하지 않고 기존 `System.out`으로 하고자 합니다.
- 다음 번에 적절한 상황을 만나면 `System.err`를 사용해보도록 하겠습니다. 감사합니다 :)

2023-01-04 07:30 UTC, SJGeeKo commented on src/test/java/lotto/domain/LottoTicketTest.java
> +        //given
감사합니다 :)

2023-01-04 08:21 UTC, SJGeeKo commented on src/main/java/lotto/domain/LottoTicket.java
> +public class LottoTicket {
List 대신 Set을 활용하여 중복제거가 자동으로 되도록 변경해보겠습니다.

2023-01-04 08:22 UTC, SJGeeKo commented on README.md
> +총 수익률은 0.35입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)
조금 더 사람이 이해하기 쉬운 방식으로 변경해보겠습니다.

2023-01-05 06:12 UTC, matt-jylee approved these changes
고생하셨습니다.
2단계에서 뵙겟습니다.

2023-01-05 06:12 UTC, merged