[kayla.park] 로또 1차 pr드립니다!
2023newkrew/java-lotto-kakao pull request #29
Opened 2023-01-03 06:58 UTC by kokomo0

안녕하세요 헨리.. 기능을 마감기한까지 다 완성을 하지 못해서, 완성 하느라 늦었습니다.. 죄송합니다.
이번 과제의 추가된 기능 요구사항은 다음과 같습니다.

- 배열 대신 ArrayList를 사용한다.
- java enum을 적용해 프로그래밍을 구현한다.
- 규칙 3: 모든 원시값과 문자열을 포장한다.
- 규칙 5: 줄여쓰지 않는다(축약 금지).
- 규칙 8: 일급 콜렉션을 쓴다.

리팩토링을 다 하지 못하였습니다.. 부족하지만 잘 부탁드립니다.

2023-01-03 09:53 UTC, topjung3 requested changes
수정하시는데 도움이 되시라고 가볍게 리뷰하였습니다. 차근차근 같이 고쳐나가면 좋을 것 같습니다.

고생하셨습니다~!

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lotto.java
> +        if (matchCount == 6) return 2000000000;
과제에 enum을 사용하는 내용이 있으니 해당 상수 값을 LottoInfo로 옮기면 어떨까요? 혹은 상수 값을 들고 있는 class를 만들어 사용해도 좋을 것 같네요.

```
public class LottoPrizeMoney {
  public static final FIRST_PRIZE_MONEY = 2 * 1000 * 1000 * 1000;
}
```

그리고 큰 값을 사용했을 때 한눈에 숫자가 맞는지 판단하기 어려운데 저같은경우 주석에는 일상생활에서 표기하듯이 콤마로 1000자리씩 분리해주구요. 상수를 넣을 때 연산자를 사용해서 넣어두는 편입니다. LottoInfo의 enum을 예로들면 아래와 같이 구현이 되겠네요.

```
// LottoInfo
...
// 6개 일치 (2,000,000,000)
FIRST_PRIZE_MONEY(2 * 1000 * 1000 * 1000)
...

// Lotto
...
if (matchCount == 6) return LottoInfo.FIRST_PRIZE_MONEY.getValue();
...
```

이렇게 사용해도 되는 이유는 enum은 코드가 실행될 때 단 한번 실행되는게 보장이 되며 위의 곱하기 연산은 연산이 수행된 결과값이 메모리에 올라가서 연산이 다시 일어나지 않거든요. 즉 `FIRST_PRIZE_MONEY(2000000000)` 와 같습니다.

위의 static final 필드도 마찬가지입니다.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lottos.java
> +public class Lottos {
Lottos 는 안에 들어있는 기능 대비 이름이 명확하지 않은 것 같네요.

유저가 지불한 금액 그리고 로또 개수가 들어가 있는데 LottoTicket, LottoReceipt 같은 이름들이 되거나 혹은 현재 Lotto가 LottoLine 이 되고 Lottos가 Lotto가 되거나 해야 좀 더 명확할 것 같네요. 좋은 이름으로 한번 고민해서 변경해주시면 좋아 보입니다.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lottos.java
> +    public List<Lotto> getLottoList() {
getLottoList는 제거해야 할 필요가 있습니다. lottoList를 final로 하셨지만 List안의 내용은 계속 추가 혹은 변경 될 수 있습니다.
https://richardworld.tistory.com/entry/List-%EA%B0%9D%EC%B2%B4%EC%9D%98-final-%ED%95%9C%EC%A0%95%EC%9E%90%EA%B0%80-%EA%B0%96%EB%8A%94-%EC%9D%98%EB%AF%B8

즉 외부에서 getLottoList를 이용해서 lottoList를 받아 add 나 remove를 수행할경우 count와 실제 lottoList 개수가 맞지 않는 상황이 발생할 수 있습니다.

외부에서 수정하지 못하게 getter를 삭제 하셔야 합니다. 확인해보니 test 코드에서 사용하셔서 작성하신 메소드 같은데 test를 수정하는 방식으로 수정해야 할 것 같네요.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/View.java
> +    private static final Scanner scanner = new Scanner(System.in);
레이싱 2차 PR에 리뷰 올린 것처럼 input 관련을 View에서 분리하는게 좋아 보여요. MVC 패턴 기반으로 작업하실 땐 View는 정말 보여주는 것만 하는게 좋습니다. 혹은 View를 CommandLineComponent 같은 다른 이름으로 변경하시는게 좋아보입니다. 하지만 여전히 안에 비지니스 로직 및 여러가지 기능이 들어가 있기 때문에 SRP에 적합한 스타일은 아닙니다.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lottos.java
> +    public double getTotalLotteryAmount(final WinLottoNumbers winNumbers) {
double을 long으로 변경하는게 좋아보입니다. double을 사용하신 이유가 getTotalLotteryRate 때문에 사용하신 것 같은데 해당 rate를 계산 및 출력할 때 double로 캐스팅하여 사용하시는게 더 명확한 사용법으로 보입니다.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lottos.java
> +        return amount/purchaseAmount;
위의 코멘트 처럼 amount와 purchageAmount를 정수형으로 받고 (double) amout /purcahgeAmount 로 캐스팅하여 double로 반환하는게 더 좋아 보입니다.

그리고 amount가 무엇의 amount인지 모호하네요. 이름 수정이 필요할 것 같습니다.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lotto.java
> +    public static int getLotteryAmount(final int matchCount, boolean isBonusMatch) {
외부에서 사용할 때 getMatchCount를 써서 일치한 개수와 isMatchBonusNumber를 통해 보너스가 맞았는지 확인하여 그 값들을 각각 기억했다가 getLotteryAmount를 통해 호출하는것 보다 Lotto API 사용자(개발자)는 당첨 숫자(객체)만 넣으면 즉각적으로 상금이 얼마인지 나오는게 사용하기 편해보이네요. SRP원칙에 의거하여 getMatchCount와 isMatchBonusNumber를 분리하신건 잘하셨습니다.

즉 static은 제거하시고 getMatchCount 함수와 isMatchBonusNumber 함수를 private로 변경한 후 외부에서 getLotterAmount를 호출할 때 WinLottoNumbers 인스턴스를 매개변수로 받아 내부(private)함수인 getMatchCount와 isMatchBonusNumber를 이용하여 계산 및 처리 후 바로 상금을 반환하는게 좋아 보입니다.

추가로 당첨을 확인하는 로직이 Lotto 클래스가 아니라 WinLottoNumbers에 있는게 더 자연스럽지 않나 그런 생각이 드네요. 그리고 WinLottoNumbers를 보았는데 내부 기능상으로는 LottoWinner 나 LottoWinningNumber가 더 좋지 않나 생각이 듭니다. class이름에 동사는 쓰지 않습니다.

작성해주신 이번 과제의 목표를 참고해보았을 때는 당첨금에 관련된 class도 분리하는게 좋아 보입니다. enum을 적용해서 구현하라는 목표에서 요구하는 바는 각각의 다른 클래스가 같은 상태값을 공유하면서 책임을 분산시키는 방식으로 작성하도록 유도하기 위한 목표라고 생각이 되어집니다. 아래와 같이 구현하는게 좀 더 목표에 부합할 것 같습니다. 네이밍은 더 멋진 이름으로 한번 고민해주세요.

```
public enum LottoPlace {
   FIRST_PLACE, SECOND_PLACE, ..., LOSE
}

public class LottoWinner {
  ...
  public LottoPlace isWinnerNumber(Lotto lotto) {
     ...
     if ...
     else if ...

     return LottoPlace.FIRST_PLACE;
  }
  ...
}

public class LottoPrizeMoney {
  ...
  public Long getLottoPrizeMoney(LottoPlace lottoPlace) {
    if (lottoPlace == LottoPlace.FIRST_PLACE) {
       return 2000000000;
    }
  }
  ...
}

```

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lotto.java
> +    public long getMatchCount(final List<LottoNumber> winNumbers) {
반환 타입이 long이 될 필요가 없어보입니다. int도 충분할 것 같네요. 금액부분이 long이 되는게 더 좋아보입니다.

2023-01-03 09:53 UTC, topjung3 commented on src/main/java/Lottos.java
> +            int lotteryResult = lotto.getLotteryResult((int)lotto.getMatchCount(winNumbers.getNumbers()), lotto.isMatchBonusNumber(winNumbers.getBonusNumber()));
static method를 아래와 같이 사용하는건 좋지 않습니다. 이는 Lotto class에 코멘트 달아드린 내용을 수정하시면 자연스럽게 수정이 될 것이구요. 나중에 static method를 사용할때는 아래와 같이 사용하시는게 맞습니다.

```
  // 클래스의 static 함수이므로 instance에서 접근하는게 아니라 Class를 사용하여 호출하셔야합니다. 
  // 두가지 방식으로 접근 할 수 있는 상태의 class 는 일반적으로 문제가 있을 확률이 높기 때문에 지양하셔야 합니다.
  Lotto.getLotteryResult(...)
```

2023-01-05 01:24 UTC, kokomo0 commented on src/main/java/Lotto.java
> +        if (matchCount == 6) return 2000000000;
넵, 조언 감사드립니다! 1000씩 분리하는 것 정말 꿀팁이네요..!! enum으로 관리하도록 수정했습니다.

추가로, LottoInfo에서 기타 상수값을 관리하고 있는데요(로또 가격, 로또 숫자 범위 등등..) 이 부분을 LottoInfo로 관리하는 것 vs 실제 사용하는 클래스에서 static 변수로 관리하는 것(예: LottoNumber에 로또 범위 관리, Lotto에 로또 번호 개수 관리 등..)
코드 유지보수 측면에서 어디서 상수를 관리하는 것이 더 읽기 좋을까요? 헨리의 조언을 듣고 싶습니다!

2023-01-05 01:25 UTC, kokomo0 commented on src/main/java/Lottos.java
> +public class Lottos {
넵 여러가지 생각을 해봤는데.. 실제 로또를 구매하면 티켓 한장에 5개의 로또 게임이 들어 있으니, 추천 해주신 이름 중 로또 티켓으로 수정하였습니다!(Lotto는 그대로 유지, Lottos -> LottoTicket 으로 변경하였습니다.)

2023-01-05 01:27 UTC, kokomo0 commented on src/main/java/Lottos.java
> +    public double getTotalLotteryAmount(final WinLottoNumbers winNumbers) {
넵, 급하게 코드 작성하면서 놓친 부분이네요..! 함수 기능에 맞도록, 반환형을 long으로 변경하였습니다!

2023-01-05 01:28 UTC, kokomo0 commented on src/main/java/Lotto.java
> +    public long getMatchCount(final List<LottoNumber> winNumbers) {
넵, int로 수정하였습니다!

2023-01-05 01:44 UTC, topjung3 commented on src/main/java/Lotto.java
> +        if (matchCount == 6) return 2000000000;
코드 스타일에 따라 다른데요. 저는 class에서 하는 편을 선호합니다.

2023-01-05 02:39 UTC, kokomo0 commented on src/main/java/Lottos.java
> +    public List<Lotto> getLottoList() {
이 부분 처리에서 많은 고민을 했습니다..!
자동으로 로또를 만든 다음, view에 보내서 생성된 로또를 유저한테 보여줘야 하는 기능이 있는데, getter 없이 처리하기가 어려웠습니다..!
혹시, 생성자/getter에서 방어적 복사를 사용하도록 수정했는데, (return ArrayList<>lottoList) 이렇게 처리하면 말씀하신 문제를 완전히 방지할 수 있을까요?!

2023-01-05 05:27 UTC, kokomo0 commented on src/main/java/Lotto.java
> +        if (matchCount == 6) return 2000000000;
네, 답변 감사드립니다!

2023-01-05 05:30 UTC, kokomo0 commented on src/main/java/Lottos.java
> +    public List<Lotto> getLottoList() {
이 부분과 관련하여 고민을 많이 해보았습니다.. 자동으로 생성된 로또를 view로 보내서 사용자에게 출력하여 보여주는 로직이 필요한데요, 여기서 getter없이 구현하는 방법이 잘 떠오르지 않았습니다..

기존 코드에서 생성자 / getter를 방어적 복사를 사용하도록 수정을 했는데, 이렇게 수정하면 말씀하신 문제점을 잘 방지할 수 있을까요?!

2023-01-05 05:30 UTC, kokomo0 commented on src/main/java/View.java
> +    private static final Scanner scanner = new Scanner(System.in);
넵, 그때 주신 내용 참고에서 mvc로 분리하였습니다!

2023-01-05 05:32 UTC, kokomo0 commented on src/main/java/Lottos.java
> +        return amount/purchaseAmount;
넵 말씀하신대로 파라미터와 반환값 자료형 수정하였습니다, 모호한 파라미터명은 전체적으로 이렇게 수정했습니다! (purchaseAmount -> purchaseMoney, amount -> winningMoney)

2023-01-05 05:46 UTC, kokomo0 commented on src/main/java/Lotto.java
> +    public static int getLotteryAmount(final int matchCount, boolean isBonusMatch) {
1. 말씀해주신 것 처럼 WinLottoNumber -> LottoWinner로 클래스명 변경하였습니다.

2. LottoWinner 클래스로 당첨결과를 확인하는 로직을 이동하였는데요, 제 생각에는 Lotto가 당첨 로직(Lotto Winner를 받아서)확인하는 것과 LottoWinner가 당첨 로직(Lotto를 받아서) 확인하는 것 모두 자연스럽게 느껴집니다! LottoWinner가 당첨로직을 확인하는 것이 더 자연스럽다고 생각하신 이유가 있으실까요?!
 
3. getMatchCount와 isMatchBonusNumber를 private로 변경하고, 당첨 확인하는 메서드의 인자를 Lotto로 변경하였습니다. 처음 작성할때는 getLotteryAmount와 getMatchCount, isMatchBonusNumber의 의존성을 끊기 위해 저렇게 구현한 것인데.. 뭔가 잘못생각하고 있었네요 ㅎㅎ,,
 
4. 당첨등수 enum클래스 -> LottoPlace, 당첨금 enum클래스 -> LottoPrizeMoney, 당첨등수가 주어졌을 때 당첨금을 반환하는 역할을 하는 클래스 ->Banker(좋은 이름이 떠오르지 않았네요....) 로 분리하여 구현하였습니다.
이렇게 분리하고 보니 복잡도가 너무 올라가는 느낌이 드는데, LottoPlace, LottoPrizeMoney, Banker를 하나로 합쳐서 enum클래스를 만드는 것은 어떻게 생각하시는지 궁금합니다!

2023-01-05 05:47 UTC, kokomo0 commented on src/main/java/Lottos.java
> +            int lotteryResult = lotto.getLotteryResult((int)lotto.getMatchCount(winNumbers.getNumbers()), lotto.isMatchBonusNumber(winNumbers.getBonusNumber()));
넵, 현재 static method를 제거하였습니다. 말씀해주신 부분 앞으로 유의하도록 하겠습니다!

2023-01-05 05:48 UTC, javajigi approved these changes
@topjung3 
1단계 피드백 반영 진행한 것으로 파악되어 다음 단계 진행을 위해 제가 대신 merge해요.
다음 단계 리뷰도 잘 부탁드려요.

2023-01-05 05:48 UTC, merged

2023-01-05 06:15 UTC, topjung3 commented on src/main/java/Lottos.java
> +    public List<Lotto> getLottoList() {
아하 view에서 사용하고 있었군요. 복사를 하여 출력하도록 수정하신 부분 좋다고 생각합니다. totalPay가 없다면 count 멤버 변수를 삭제하고 getCount 에서 lottoList.size()를 반환하게 해주면 좋은데 totalPay 때문에 애로사항이 있네요. 수정하신 방법이 최선의 방법이라고 생각 됩니다~! 잘하셨습니다!

2023-01-05 06:55 UTC, topjung3 commented on src/main/java/Lotto.java
> +    public static int getLotteryAmount(final int matchCount, boolean isBonusMatch) {
2. 사실 정답은 없다고 생각하는데요, 제가 LottoWinner가 좀 더 자연스럽게 여기는 이유가 Lotto는 사실 일급 컬렉션으로 구현하여 번호를 저장하는 기능 하나만 수행해도 괜찮다고 생각했기 때문입니다. (Lotto 이름이 좀 포괄적이지만 현재 번호를 저장하는 게 주 역할로 보여서요) 실생활에서 생각해보았을 때도 로또 영수증은 종이일 뿐이잖아요?  그리고 이를 농협에 가져가면 등수를 확인해서 돈을 주는 거고요. 그래서 당첨을 확인하는 주체는 Lotto보단 LottoWinner가 되는게 좀 더 자연스럽지 않나 라고 생각했습니다.

좀 더 세분화 하자면 LottoWinner와 Lotto를 받아서 당첨을 확인하는 Service 역할을 하는 class가 있으면 역할을 명확하게 구분 할 수 있습니다.

Lotto (로또 번호 = 로또 판매점에서 산 영수증)
LottoWinner (로또 당첨 번호 = 매주 발생하는 당첨 번호)
LottoWinnerChecker 혹은 Banker (Lotto와 LottoWinner을 가지고 등수를 확인하여 상금을 지불하는 Service = QR 찍을 수 잇는 핸드폰, 당첨을 확인하는 나 자신)

4. enum으로 LottoPlace, LottoPrizeMoney 합치는 건 좋아 보입니다. Banker 까지 합치는건 약간 너무 많은 책임을 갖을 것 같네요.