[william.watson] 로또 1단계
2023newkrew/java-lotto-kakao pull request #30
Opened 2023-01-03 07:02 UTC by gkwodn1044

2023-01-04 02:49 UTC, parksjin01 requested changes
안녕하세요 윌리엄, 로또 1단계 미션 진행으로 고생 많으셨습니다. 
지난번 미션보다 읽기 쉽게 코드가 작성된 것 같습니다. 👍 
작성해주신 코드와 관련하여 몇가지 코멘트를 남겨두었는데요, 참고하셔서 코드에 반영해주시면 좋을것 같아요

2023-01-04 02:49 UTC, parksjin01 commented on README.md
> +* 두 번째 소수점에서 반올림하는 것?
README에서 요구사항을 정리한 내용이 먼저 오면 좋을것 같아요
구현이 필요한 기능들도 잘 정리되어 있으면 프로그램의 목적을 파악하는데 도움이 될 것 같습니다.

2023-01-04 02:49 UTC, parksjin01 commented on src/main/java/lotto/Main.java
> +    }
지금은 Main 클래스가 컨트롤러의 역할을 하고 있는것으로 보이는데요, 
컨트롤러의 역할을 하는 클래스를 Main에서 분리해보는 것은 어떨까요?

2023-01-04 02:49 UTC, parksjin01 commented on src/main/java/lotto/model/Cash.java
> +    }
`equals()` 메소드와 `hashCode()` 메소드를 오버라이딩 해주셨네요. 👍

2023-01-04 02:49 UTC, parksjin01 commented on src/main/java/lotto/model/Cash.java
> +    }
`plus()` 메소드들은 사용되는 곳을 찾지 못했는데요, 만약 사용하지 않는 메소드라면 삭제하는 것은 어떨까요?

2023-01-04 02:49 UTC, parksjin01 commented on src/main/java/lotto/model/LottoConstants.java
> +}
로또와 관련된 상수들을 모아서 별도의 클래스로 모은 것은 좋은 방법인것 같아요 👍 
로또와 관련된 정보를 찾아야하는 경우 위 클래스에서 쉽게 파악할 수 있을것 같아요

소소한 내용이지만 `LOTTO_RPICE` 상수만 `public final static` 이고 다른 상수들은 `public static final`이네요 😄 
`LOTTO_PRICE`도 다른 상수들과 동일하게 맞춰주시면 좋을것 같아요

2023-01-04 02:49 UTC, parksjin01 commented on src/test/java/lotto/model/LottoCountTest.java
> +    }
위 테스트 코드에서 실패하는 테스트 케이스가 있는 것 같은데요, 확인해주시면 좋을것 같아요

2023-01-04 06:07 UTC, gkwodn1044 commented on src/main/java/lotto/model/LottoConstants.java
> +}
헉 이런 실수를...!

2023-01-04 06:12 UTC, gkwodn1044 commented on src/main/java/lotto/model/Cash.java
> +    }
해당 메소드는 인자를 Cash 객체를 받는 경우에 TotalResult 클래스의 addPrize 메소드에서 총 상금을 계산하기 위해 사용하고 있습니다! 다만 밑에 long 인자를 받도록 오버라이딩한 plus 메소드의 경우 메소드 사용을 편리하게 하기 위해 추가한 메소드인데 단위 테스트에서 사용하려고 했던 것을 빼먹은 것 같습니다!

2023-01-04 06:13 UTC, gkwodn1044 commented on src/main/java/lotto/model/Cash.java
> +    }
감사합니다!

2023-01-04 06:26 UTC, gkwodn1044 commented on src/test/java/lotto/model/LottoCountTest.java
> +    }
앗 해당 부분은 처음에는 0을 `LottoCount` 클래스의 생성자의 인자로 허용했다가 후에 프로그래밍 요구 조건을 다시 확인하면서 변경되면서 테스트 코드는 이를 반영하지 않았던 것 같습니다! 해당 부분 수정과 동시에 LottoCount 클래스의 생성자를 생성자 체이닝으로 구현해보도록 하겠습니다!

2023-01-04 06:36 UTC, gkwodn1044 commented on src/main/java/lotto/Main.java
> +    }
확실히 Main 클래스에는 main 함수만 존재하는 것이 이상적일 것 같습니다! 분리해보도록 하겠습니다!

2023-01-04 07:37 UTC, gkwodn1044 commented on README.md
> +* 두 번째 소수점에서 반올림하는 것?
좀 더 정리해볼 수 있도록 하겠습니다!

2023-01-04 09:52 UTC, parksjin01 approved these changes
코멘트 바탕으로 코드 개선해주신것 확인했습니다.
이번에 PR 주신 코드를 바탕으로 추가로 코멘트를 남겨두기는 했는데요, 
2단계 미션 진행시 참고해주시면 좋을것 같아요
(이번에는 이름과 관련된 코멘트를 많이 드리게 됐네요 🙂 )

1단계 미션 진행하시느라 고생하셨습니다 👏  👏

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/controller/Controller.java
> +        for (int i = 0; i < lottoCount.getCount(); i++){
현재는 로또를 구매한 장수를 바탕으로 컨트롤러에서 for문을 통해 로또를 생성하고 있는데요,
컨트롤러에서 로또를 생성하는 것이 아니라 별도 클래스에서 로또를 생성해보면 어떨까요?

새로운 클래스를 만들어서 `Cash`를 전달하면 로또를 발급해주는 것도 좋고, 기존 클래스들 중 적절한 클래스를 찾아서 역할을 맡겨보는 것도 좋을것 같아요

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/controller/Controller.java
> +            LottoTrial lottoTrial = new LottoTrialRandom(new LottoPickerRandom());
로또 숫자를 랜덤하게 만들어주는 역할을 `interface`로 추상화하고, 생성자를 통해 `interface` 구현체를 전달해주셨네요 👍 
이후 로또 숫자를 생성하는 규칙이 변경될 때 `LottoTrialRandom` 클래스 변경 없이 전달되는 `interface` 구현체만 변경하면 될 것 같아서 기능 추가에도 대응하기 좋은 코드인 것 같아요

지금은 `for` 문이 반복될 때 마다 `LottoPickerRandom` 객체를 새로 생성하고 있는데 해당 객체를 매번 생성하지 않고 한번 만든 객체를 재사용해보는 것은 어떨까요?

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/controller/Controller.java
> +                .collect(Collectors.toList());
`Stream`을 사용하셨네요 👍 
`Stream`을 적절히 활용하면 코드 가독성을 향상시켜준다고 생각합니다

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/Cash.java
> +    }
제가 사용하는 곳을 놓쳤었네요 😅

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/Cash.java
> +    }
통화 정보인 `원`은 추후에 변경될 수도 있고, Cash가 가지고 있는 정보보다는 출력을 위한 값으로 생각되는데요
출력을 위한 값을 `toString()`에 포함하는 것보다는 Output View에서 해당 정보를 추가해서 출력하는 것이 좋을 것 같아요.

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/LottoCount.java
> +        }
사용자가 지불한 금액으로 로또를 한장도 살수 없을 때 예외가 발생하도록 처리하신 이유가 있으실까요?

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/LottoPickerRandom.java
> +    }
로또의 번호를 1개씩 가져오도록 되어 있는데요, 6개 숫자를 한번에 가져오는 것은 어떨까요?
`pickOne` 메소드를 6번 호출하지 않고 한번의 메소드 호출로 로또 1장의 숫자를 얻어올 수 있을 것 같아서 의견 드려봅니다.

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/LottoResult.java
> +    }
`Cash`와 동일하게 화면 출력을 위한 문구는 `toString()` 보다는 Output view에서 추가되도록 변경되면 좋을 것 같아요.

view에서 모든 문구가 처리된다면 객체의 데이터가 아닌 화면 출력용 문구 변경이 필요한 경우에도 view에서만 변경하면 되고,
실제 데이터를 갖는 클래스 코드는 수정이 필요 없어질 것 같아요

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/LottoTrial.java
> +public abstract class LottoTrial {
사용자가 구매한 로또가 `LottoTrial`이 되는 것으로 이해했는데요.
로또라는 의미를 잘 전달하기 위해서 `Lotto`라는 이름도 제안드려봅니다.

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/LottoTrialRandom.java
> +public class LottoTrialRandom extends LottoTrial {
수동구매한 로또를 `LottoTrialManual`로 해주셔서, 자동구매한 로또는 `LottoTrialAuto`라는 이름도 잘 어울릴것 같네요 🙂

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/TotalResult.java
> +    }
`TotalResult` 클래스에 대한 테스트코드도 있으면 좋을것 같아요 🙂

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/WinNumber.java
> +    private final LottoBallNumber bonusNumber;
로또 당첨 번호를 `LottoTrial`로 사용하신 이유가 있으실까요?
`LottoTrial`이 로또를 나타내는 객체로 사용되는 것 같아서 로또 당첨 번호를 함께 저장하다보니 햇갈리는 느낌이 들어서요
사용자가 입력한 당첨 번호를 `LottoBallNumber`의 컬렉션으로 저장해두는 것은 어떨까요?

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/WinningCondition.java
> +    private final int printOrder;
여기서 `LottoResult` 변수는 등수를 확인하기 위해서 사용되는 것으로 이해했어요
등수를 확인하기 위해서 `LottoResult`가 사용된다면 `lottoResult` 보다 의미를 잘 전달할 수 있는 이름은 없을까요?

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/WinningCondition.java
> +    }
등수를 체크하는 로직이 포함되어 있어, 이부분도 테스트 코드가 있으면 좋을 것 같습니다. 🙂

2023-01-04 09:52 UTC, parksjin01 commented on src/main/java/lotto/model/WinNumber.java
> +        }
로또 숫자가 당첨번호와 5개 일치하지 않는 경우 보너스 번호 일치 여부를 무시하기 위해서 코드를 추가해주신 것 같아요
별도로 `matchBonus`를 변경하기 보다는 등수를 체크하는 과정에서 5개의 번호가 일치한 경우에만 보너스볼 일치 여부를 확인해보는 것은 어떨까요?

WinNumber에서 직접 matchBonus를 수정해주지 않아도 되고, 등수를 체크하는 코드를 보며 보너스볼은 2등과 3등을 구분하기 위해서만 사용된다는 것을 파악할 수 있을 것 같아요

2023-01-04 09:52 UTC, merged

2023-01-07 17:10 UTC, gkwodn1044 commented on src/main/java/lotto/model/LottoCount.java
> +        }
해당 부분은 강의의 로또 피드백 부분에 500원 입력시 에러 발생이라는 문구에서 명시된 대로 한장도 살 수 없을때 예외 처리를 하였습니다!

2023-01-07 17:36 UTC, gkwodn1044 commented on src/main/java/lotto/model/WinNumber.java
> +    private final LottoBallNumber bonusNumber;
해당 부분의 경우, 당첨 번호도 일종의 로또와 같고, 다만 보너스 숫자의 여부가 다르기 때문에 완전한 상위-하위호환 관계라고 하기 어려워 상속이 아닌 포함 관계를 이용해 구현하였습니다. 다만 `LottoTrial`이라는 클래스명이 당첨 번호를 저장하기에는 적합하지 않다고 생각하기 때문에 해당 클래스명을 `Lotto`로 변경하도록 해보겠습니다!

2023-01-07 18:42 UTC, gkwodn1044 commented on src/main/java/lotto/model/WinningCondition.java
> +    private final int printOrder;
LottoResult는 등수를 의미하는 것이 아니라, 해당 등수의 조건을 의미하고 있습니다! 예를 들어 FIRST_PRIZE의 조건으로 6개의 숫자 일치와 보너스 숫자의 불일치라는 뜻입니다! 해당 클래스는 당첨 번호와 구매한 로또간의 비교 결과를 담는 클래스로, LottoResult라는 클래스명을 유지하는 것이 더 좋다고 생각합니다!