[jayden.v] 로또게임 step1
2023newkrew/java-lotto-kakao pull request #32
Opened 2023-01-03 07:06 UTC by Tarakyu

로또게임 과제 제출합니다.

시간이 부족해 설계를 깊게 고민하고 고칠 여유가 없었는데, 
부족한 부분들을 알려주시면 설계를 더 최적화해보겠습니다 🥲

2023-01-03 09:37 UTC, gogyzzz commented on src/main/java/lotto/domain/LottoStatistics.java
> +    private final Map<LottoResult, Integer> lottoStatistics = new HashMap<>();
LottoStatistics 내에 lottoStatistics 라는 이름을 가지는 변수가 있어서 처음 읽을 때 헷갈릴 수 있을 것 같아요!
타입을 보고 용도를 이해했는데 항목 별 빈도를 나타내므로 'lottoHistogram'이 어떨지 제안드립니다~

2023-01-03 09:40 UTC, gogyzzz commented on src/main/java/lotto/domain/LottoTicket.java
> +    public String getDetail() {
LottoTicket, LottoNumberList의 getString, getDetail 대신 이미 있는 toString을 오버라이딩해서 쓰는건 어떨까요? 
비
저도 잘 몰라서 toString으로 오버라이딩해서 쓰면 안되는 건지 가이드가 되었다면 그대로 쓰셔도 될 것 같습니다~

2023-01-03 09:41 UTC, gogyzzz commented on src/main/java/lotto/domain/Lotto.java
> +public class Lotto {
'Lotto' 라는 클래스 이름이 다른 클래스의 접미어로 계속 쓰이고 있어서 추상적인 의미라 느껴집니다~
LottoService, LottoController 등이 적절할 것 같은데 어떠실까요?

2023-01-03 09:43 UTC, gogyzzz commented on src/main/java/lotto/LottoMain.java
> +        int money = InputView.getMoney();
음수 값이 없는 숫자타입(money, count, number 등) 은 long을 쓰는게 validation에도 잘 걸려서 좋을 것 같습니다~

2023-01-03 09:43 UTC, gogyzzz commented on src/main/java/lotto/domain/LottoTicket.java
> +        boolean bonusNumber = lotto.checkBonusNumberInNumberList(lottoNumberList);
boolean bonusNumber 인 것과 int bonusNumber 가 있는데 이 경우는 isBonusNumberIn으로 주는게 가독성에 좋아보입니다~

2023-01-03 09:44 UTC, gogyzzz commented on src/main/java/lotto/domain/enumeration/LottoResult.java
> +    public static LottoResult getLottoResultOf(int numberCount, boolean bonusNumber) {
이 경우 bonusNumber 인자는 의미상 useBonusNumber가 되는게 적절해보이는데 맞을까요?

2023-01-03 09:45 UTC, gogyzzz requested changes
고생 많으셨습니다~ 자잘한 것만 같이 보면 좋을 것 같아요!

2023-01-05 06:24 UTC, Tarakyu commented on src/main/java/lotto/domain/LottoStatistics.java
> +    private final Map<LottoResult, Integer> lottoStatistics = new HashMap<>();
그렇군요!! lottoHistogram으로 수정하였습니다 .

2023-01-05 06:24 UTC, Tarakyu commented on src/main/java/lotto/domain/LottoTicket.java
> +    public String getDetail() {
toString을 오버라이드하는 방법도 고민했었는데, toString을 디버깅 용도가 아닌 비즈니스 로직에 사용되도록 해도 되는지가 고민됐었어요! 만약 문제가 없다면 toString이라는 이름이 더 직관적인 것 같아서, 그렇게 바꾸었습니다!

2023-01-05 06:24 UTC, Tarakyu commented on src/main/java/lotto/domain/Lotto.java
> +public class Lotto {
그렇네요.. 당첨 로또 번호라는 것을 명확하게 하기 위해 WinningLotto라는 이름으로 수정했습니다!

2023-01-05 06:24 UTC, Tarakyu commented on src/main/java/lotto/LottoMain.java
> +        int money = InputView.getMoney();
잘 몰랐던 내용이네요! long으로 바꾸었습니다.

2023-01-05 06:24 UTC, Tarakyu commented on src/main/java/lotto/domain/LottoTicket.java
> +        boolean bonusNumber = lotto.checkBonusNumberInNumberList(lottoNumberList);
앗 네이밍을 실수했네요.. isBonusNumberIn으로 수정하였습니다.

2023-01-05 06:24 UTC, Tarakyu commented on src/main/java/lotto/domain/enumeration/LottoResult.java
> +    public static LottoResult getLottoResultOf(int numberCount, boolean bonusNumber) {
여기서도 네이밍을 실수했네요.. hasBonusNumber로 수정하였습니다!

2023-01-09 01:58 UTC, javajigi approved these changes
1단계 피드백을 충분히 주고 받은 것으로 파악되어 다음 단계 미션 진행을 위해 대신 merge합니다. 
미션 진행하느라 수고했어요. 💯

2023-01-09 01:58 UTC, merged