[sienna.o
2023newkrew/java-lotto-kakao pull request #35
Opened 2023-01-03 07:28 UTC by binimini

2023-01-04 00:55 UTC, matt-jylee requested changes
로또 1단계를 하시느라 수고하셨습니다.
역시 이전보다 훨씬 좋은 코드를 작성하신것 같습니다.
(혹시 사용한 스캐너를 닫는 부분은 리팩토링 시 사라진 걸까요?)

제가 작성한 리뷰를 보시고 조금만 더 개선하는 연습을 해볼까요?!

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/controller/LottoApplication.java
> +            System.out.println(exception);
예외를 출력할 때에는 스택 트레이스를 출력하는 방법과 system.err를 사용하는 방법도 있습니다~!

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/controller/LottoApplication.java
> +public class LottoApplication {
전반적으로 이전 미션보다 훨씬 이해하기 좋아졌습니다!

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/domain/LottoGenerator.java
> +    }
이부분을 개선하면 많은 부분의 변화가 일어날텐데요. 혹시 다른 코드에서 사용하기 힘든 변화일까요?
한번 고민해보시면 좋을것 같아요

2023-01-04 00:55 UTC, matt-jylee commented on src/main/java/view/OutputView.java
> +        System.out.print("(기준이 1이기 때문에 결과적으로 ");
이 부분은 문제(요구사항)가 1을 기준으로 정의되었기 때문으로 보이는데요.
가능하다면 이 부분도 개선해 볼까요?

2023-01-04 00:55 UTC, matt-jylee commented on src/test/java/domain/LottoBuyerTest.java
> +        // when, then
사람에 따라서는 given when then 또는 arrange assert act 등의 구문을 굳이 주석으로 남기는 것을  권장하지 않을 수 있습니다.
선택적인 문제이고, 줄 바꿈으로 영역을 구분한다던가 하는 방법도 가능합니다.

결론적으로, 보기가 한 결 수월해졌습니다!

2023-01-04 01:43 UTC, binimini commented on src/main/java/controller/LottoApplication.java
> +            System.out.println(exception);
급하게 마무리하다보니 신경을 못썼네요🥲 스택 트레이스 출력 시도해보겠습니다!

2023-01-04 01:45 UTC, binimini commented on src/main/java/controller/LottoApplication.java
> +            System.out.println(exception);
추가적으로 스캐너를 닫는 부분은 페어와 닫는 방식을 논의하다가 구현을 마무리하고 처리하기로 했는데 
시간이 촉박해서 넘어가버렸네요ㅠ 리팩토링에서 추가해보겠습니다 🙃

2023-01-04 02:28 UTC, binimini commented on src/main/java/view/OutputView.java
> +        System.out.print("(기준이 1이기 때문에 결과적으로 ");
놓친 부분이네요! 개선해보겠습니다!

2023-01-04 02:58 UTC, binimini commented on src/test/java/domain/LottoBuyerTest.java
> +        // when, then
오 arrange-assert-act 방식도 있군요. 새로운 걸 알았네요! 
저번 테스트는 개행으로 구분해서 다른 방식을 적용해봤는데,  
확실히 구분이 간다는 점이 좋은데 테스트의 크기가 커지는 부분은 아쉬운 것 같아요 🤔

2023-01-04 03:20 UTC, binimini commented on src/main/java/domain/LottoGenerator.java
> +    }
맷이 말씀해주신대로 LottoGenerator에서 변경이 일어날 수 있는 여지가 많은 것 같아서
기존 코드를 다시 한 번 확인해보고 어떻게 개선할 수 있을지 고민해보겠습니다!

2023-01-04 09:14 UTC, binimini commented
### 수정사항
- LottoGenerator 삭제 (Lotto 자동 생성 로직 -> Lotto, LottoNumber 목록 처리 -> LottoNumber)
- LottoBuyer 로직 수정 (생성시 받은 금액으로 로또 구매 -> 생성시 금액을 받고, 구매하는 함수 호출시 구매)
- InputView 닫기 처리
- OutputView 출력 형식 수정 및 LottoBuyer 수익률 계산시 100% 대비 수익률 계산하도록 변경

2023-01-05 05:42 UTC, matt-jylee approved these changes
고생하셨습니다!
2단계에서 뵙겠습니다~!

2023-01-05 05:42 UTC, merged