[leo.pss] 로또 1단계 코드 리뷰 요청드립니다.
2023newkrew/java-lotto-kakao pull request #36
Opened 2023-01-03 07:31 UTC by HolywaterPark

안녕하세요 캐니!
새로운 과제 [로또 자동] 1단계 리뷰 요청드립니다.
항상 감사드립니다!

2023-01-03 15:28 UTC, allstarkenny requested changes
안녕하세요 레오~
항상 최선을 다하고 계신 모습이 보여 언제나 든든합니다.

미리 공유주시긴 했지만 기존 과제들과 스타일이 확 달라져 조금 놀랐네요 😮 😄 
개인적으로 주신 질문 주신 내용에 대한 답변을 드리자면..
1. Service나 Repository에 대한 내용을 사실 기존 Spring에서 많이 사용하고 있고 현재 팀에서도 사용하고 있는 구조 입니다. 생각해보면 이전 과제에서도 Racing 객체가 엄밀히 이야기 하면 비지니스 로직이 녹아있는 Service Layer 였다고 생각합니다. (Controller에 녹아있던 비지니스 로직은 전부 넘겨버렸으니까요 ㅎㅎ) 그래서 이전 구조와 크게 달라졌다고 생각하지 않습니다. [참고 관련 블로그 링크](https://velog.io/@jybin96/Controller-Service-Repository-%EA%B0%80-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C)
2. View에서 Model을 아예 참조하지 않도록 구현했다는 점은 어떤 부분에 있어서 이야기 주셨는지 정확하게 이해가 잘 가지 않았습니다. 😢 아마 리뷰 드린 부분에 답변이 있긴 할 것 같은데 답변이 되셨으면 좋겠네요. 만일 아니라면 톡이나 댓글로 언제든 말씀주세요.

추가적으로 생각해볼만한 내용들을 좀 적어봤어요.
아래 내용들 좀 고민해보시고 언제든 리뷰 요청 주세요. 화이팅입니다 💪

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoTicket.java
> +    public String toString() {
p3; 도메인과 뷰가 연관되어 있지 않은것 처럼 보이지만 도메인에 뷰를 위한 로직이 있네요 😢 
해당 로직은 여기 있기보다는 뷰에 있는것이 더 좋아보입니다.

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/exception/ErrorCode.java
> +public enum ErrorCode {
오 ErrorCode를 별도로 정의해둔 내용 좋네요. 👍 👍

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/LottoSimulationApplication.java
> +                lottoController.startLottoGame();
p2; 이렇게 while문을 돌리면 정상적으로 완료 되어도 계속 실행 되겠네요.
문제가 발생했을때만 재시도 하고 정상적으로 완료되면 종료되면 더 좋을거 같습니다.

p5; 지난번에는 while 문으로 만들어봤으니 재귀로 한번 만들어 보시는건 어떠신가요? 😄

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/exception/ErrorCode.java
> +    INVALID_PURCHASE_AMOUNT("구매 금액은 0원 보다 커야합니다.");
p3; 만일 구매 금액에 숫자가 아닌 문자열이 들어올경우 이곳에 없는 예외가 발생할 것 같네요.
이외에 발생할 수 있는 에러가 있을지 고민해보면 좋을거 같습니다 😄

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoNumber.java
> +    public boolean equals(Object o) {
p3; equals hashcode는 어떤 기준으로 재정의 하고 계신가요?

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
p3; 이렇게 LottoNumber를 사용하면 추후에 큰 금액으로 Lotto를 샀을 경우 LottoNumber 객체가 매번 생성되어 메모리를 많이 사용할 것 같은데요.
미리 1~45까지 숫자를 생성해두고 사용할 수 있는 방법은 없을까요?

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoRank.java
> +                .orElse(RANK6);
매우 깔끔하네요 👍

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoResult.java
> +    public boolean equals(Object o) {
p3; 동일하게 hashcode에 대한 내용이 필요할거 같네요. 😢

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoResult.java
> +    public LottoResult(List<Integer> rankList) {
테스트 용도로 만들어두신 생성자 너무 좋네요 👍

2023-01-03 15:28 UTC, kenny-kim2 commented on src/main/java/lotto/model/LottoTicket.java
> +    private static final Integer LOTTO_NUMBER_LOWER_BOUNDARY = 1;
p3; 이렇게 사용되는 변수가 LottoNumber 객체에도 있는데 추후에 로또 번호가 46번까지로 늘어난다면 모두를 바꿔줘야 할 것 같네요.
위에 LottoNumber 와 관련된 캐싱 내용을 적용하다 보면 자연스럽게 합쳐질거 같아요 😄

2023-01-03 15:28 UTC, allstarkenny commented on src/main/java/lotto/view/LottoInputTemplate.java
> +    }
p4; 오호 모델로 있지 않은 변수는 이곳에서 Validation 체크를 하고 있군요.
간단한 체크는 좋지만 추후에 Input이 다양해 지거나 Validation 과정이 많아지면 어떻게 될까요? 😢

2023-01-03 15:28 UTC, allstarkenny commented on src/main/java/lotto/view/LottoInputTemplate.java
> +                .map(num -> Integer.parseInt(num.trim()))
p3; 이때 문자열이 들어갔다면 어떻게 될까요?

2023-01-03 15:28 UTC, allstarkenny commented on src/main/java/LottoSimulationApplication.java
> +                lottoController.startLottoGame();
\+ 이렇게 동작하면 첫 로또에 5000을 구매하고 다시 시작할때 5000원을 구매하면 이전과 겹쳐져서 10개가 구매됩니다 🐶 🍯

2023-01-03 15:28 UTC, allstarkenny commented on src/test/java/lottoTest/service/LottoServiceTest.java
> +    }
p4; 구매 금액에 따라 발급되는 로또 갯수 계산도 테스트에 들어가면 좋을거 같네요 😄

2023-01-03 15:28 UTC, allstarkenny commented on README.md
> +- 로또 구입 금액에 대한 당첨 상금의 수익률을 알려준다. 이득인지 손해인지 또한 알려준다.
상세한 문제 정의 좋네요 👍

2023-01-04 04:04 UTC, HolywaterPark commented on src/main/java/lotto/model/LottoNumber.java
> +    public boolean equals(Object o) {
객체 간에 비교 연산이 필요한 경우 추가하고 있습니다. hashcode의 역할을 명확히 이해 못하고 사용하지 않을 메소드라고 생각되어 재정의하지 않았는데, equals를 재정의하려면 hashcode도 재정의 해야한다는 사실을 알고 공부하고 있습니다!

2023-01-04 04:15 UTC, HolywaterPark commented on src/main/java/lotto/model/LottoResult.java
> +    public LottoResult(List<Integer> rankList) {
저는 이번에 테스트 코드가 너무 복잡해져서 이런 생성자를 추가했는데, 테스트를 용이하게 하기 위한 생성자를 추가하는 것이 맞는지 궁금했습니다..!
만약 이런 테스트 용도의 생성자를 사용한다면 비지니스 로직에 영향을 주지 않는다던가 하는 기준이 있을까요?

2023-01-04 06:21 UTC, HolywaterPark commented on src/main/java/lotto/model/LottoTicket.java
> +    private static final Integer LOTTO_NUMBER_LOWER_BOUNDARY = 1;
이 부분은 어떻게 변경할지 잘 모르겠습니다..중복되는 상수는 따로 공통으로 관리하는 것이 더 좋을까요??

2023-01-04 10:27 UTC, HolywaterPark commented
안녕하세요 캐니! 자꾸 늦은 시간에 리뷰 요청 드리는 것 같아 죄송합니다..😢
피드백 주신 내용 바탕으로 수정했고 그 외에 로직을 좀 더 명확히 구분하는 과정을 거쳤습니다!
위에 댓글로 남긴 질문 외에 궁금한 점이 몇 가지 있는데
- 재시도 시 Repository에 저장된 값들이 초기화가 되지 않는 문제가 있어 초기화로 해결했는데, 다른 방법으로도 해결할 수 있을까요?
- 어떤 로직의 결과를 변수에 할당할 필요 없이 바로 다른 함수에 전달 가능한 경우(예시 : 현재 코드에서 LottoService - getLottoResult) 바로 할당하게 되면 불필요한 변수 할당은 없어지지만 가독성이 많이 떨어지는 것 같은데, 이런 경우는 어떤 쪽이 더 좋을까요?

항상 감사합니다! 😄

2023-01-04 15:26 UTC, allstarkenny approved these changes
아하 언제든 리뷰 주셔도 좋습니다 😄
우선 주신 질문에 답변을 드려보자면

> * 재시도 시 Repository에 저장된 값들이 초기화가 되지 않는 문제가 있어 초기화로 해결했는데, 다른 방법으로도 해결할 수 있을까요?

오 초기화 하는 방법도 있겠군요. 다른 방법을 생각해보자면 현재는 재시도 로직이 main 문에 들어있는데 이걸 Controller로 내려서 분리 할 수 있을거 같아요.
현재 문제가 되는 경우는 로또를 구매하고 나서 당첨 번호와 보너스 번호 입력 시 에러가 나면 처음으로 돌아가면서 발생할테니 당첨번호와 보너스 번호를 잘못 입력하면 당첨 번호와 보너스 번호만 다시 물어보도록 하면 되지 않을까요?

> * 어떤 로직의 결과를 변수에 할당할 필요 없이 바로 다른 함수에 전달 가능한 경우(예시 : 현재 코드에서 LottoService - getLottoResult) 바로 할당하게 되면 불필요한 변수 할당은 없어지지만 가독성이 많이 떨어지는 것 같은데, 이런 경우는 어떤 쪽이 더 좋을까요?

개인적으로는 불필요한 변수가 조금 생기더라도 성능과 로직에 문제가 없다면 가독성이 더 높은 방식으로 진행하시는 것이 더 맞다고 생각합니다. :)

코드의 많은 부분이 좋아진게 보이네요 😄 레오의 노력이 여기까지 느껴지는것 같습니다 💯 💯 
아래 추가적인 리뷰 드렸으니 조금 생각해보시고 다음 과제에서 수정해보시면 좋을거 같습니다.
PR은 머지하도록 하겠습니다 너무 고생하셨어요~

2023-01-04 15:26 UTC, allstarkenny commented on src/main/java/lotto/model/LottoTicket.java
> +    private static final Integer LOTTO_NUMBER_LOWER_BOUNDARY = 1;
아하 만일 중복되는 상수가 있다면 공통으로 관리하는게 추후 관리 측면에서 더 좋을 것 같습니다.

다만 현재 lottoTicket를 생성하는 방식이 1~45숫자를 List로 만들어두고 shuffle한 후 자르는데, 그것보다는 LottoNumber 객체 내부에 있는 LottoNumbers를 별도의 객체로 빼내어 key값만 shuffle 해서 뽑아내면 되지 않을까요? 그렇게 되면 겸사겸사 이곳에서 체크하던 Validation 코드도 자연스럽게 사라질 것 같은데요. (Map 의 키범위가 넘어가는 값은 키가 없음 에러로 처리)

2023-01-04 15:26 UTC, allstarkenny commented on src/main/java/lotto/model/LottoResult.java
> +    public LottoResult(List<Integer> rankList) {
네네 비지니스 로직에 영향을 주지 않는 선에서 테스트 코드를 위한 생성자 사용은 좋다고 생각합니다 👍

2023-01-04 15:26 UTC, allstarkenny commented on src/main/java/LottoSimulationApplication.java
> +            main(args);
p4; ㅎㅎ 이정도면 메소드를 분리하는게 낫지 않을까요?
메인문을 재귀하는 형태는 많이 사용하지 않습니다

2023-01-04 15:26 UTC, merged