[Tank.500m] Step1 PR요청 드립니다.
2023newkrew/java-lotto-kakao pull request #37
Opened 2023-01-03 07:31 UTC by fbgnwhife1

이전 과제에서 들었던 피드백들을 주의하면서 과제를 진행하였습니다.
비슷한 클래스끼리 디렉토리를 나누었고 MVC 패턴을 적용시켜 보았습니다.
감사합니다.

2023-01-03 09:39 UTC, hayden-ii requested changes
지난 리뷰 놓쳐서 죄송합니다 ㅠㅠ;; 로또 과제 수고하셨습니다. 몇 가지만 확인 부탁드립니다

2023-01-03 09:39 UTC, hayden-ii commented on src/main/java/domain/lotto/LottoChecker.java
> +        if (size < 3) return LottoResultType.FAIL;
else 예약어 사용하지 않으시고 구현 👍

2023-01-03 09:39 UTC, hayden-ii commented on src/main/java/domain/lotto/LottoMetaData.java
> +    public static final Integer MIN_LOTTO_NUMBER = 1;
상수의 변수화 👍 클래스 이름이 LottoMetaData 인데 코드만 보면 constant 를 저장하는 용도로 보이네요. 이렇게 네이밍하신 이유가 있으실까요?

2023-01-03 09:39 UTC, hayden-ii commented on src/main/java/domain/lotto/ticket/LottoTicket.java
> +public class LottoTicket {
LottoNumber과 LottoNumbers 클래스 이름이 좀 더 명확하게 구별가능하면 혼동을 줄일 수 있을것 같은데 어떻게 생각하시나요?

2023-01-03 09:39 UTC, hayden-ii commented on src/test/java/LottoCheckerTest.java
> +    @DisplayName("로또 꽝 당첨 테스트")
테스트에 대한 설명 👍

2023-01-03 09:39 UTC, hayden-ii commented on src/main/java/domain/lotto/result/LottoResultType.java
> +    FAIL(0, "꽝 (3개 미만) (0원)"),
type에 대해 깔끔한 enum 정리 좋습니다 👍

2023-01-03 09:39 UTC, hayden-ii commented on src/main/java/domain/lotto/number/NumberGeneratable.java
> +package domain.lotto.number;
디렉토리 이름이 number 인데 number에 관련된 변수가 다른 파일에 있는 케이스도 있어서 디렉토리 분류 기준이 조금 광범위하게 느껴질수도 있을것 같습니다. 해당 디렉토리의 클래스들이 제공하는 공통적인 기능으로 구체화시키면 어떨까요?

2023-01-03 09:49 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/LottoMetaData.java
> +    public static final Integer MIN_LOTTO_NUMBER = 1;
마땅한 이름이 생각나지 않아서 이렇게 지었는데 이름을 바꿔보았는데 LottoConstantData 는 어떨까요?

2023-01-03 09:50 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/ticket/LottoTicket.java
> +public class LottoTicket {
혹시 LottoNumber 와 LottoNumbers 클래스가 어떤 것을 말씀하시는 걸까요? ㅠㅠ

2023-01-03 09:51 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/number/NumberGeneratable.java
> +package domain.lotto.number;
makingnumbers 로 바꾸어 보았는데 아직도 뭔가가 좀 부족한 느낌입니다...

2023-01-03 09:52 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/ticket/LottoTicket.java
> +public class LottoTicket {
LottoTicket 과 LottoTickets 일까요...?

2023-01-04 01:42 UTC, hayden-ii commented on src/main/java/domain/lotto/ticket/LottoTicket.java
> +public class LottoTicket {
아이고 ㅠㅠ 죄송합니다 다른 분 코드랑 헷갈려서 ㅠㅠㅠㅠ LottoTicket과 LottoTickets 맞습니다

2023-01-04 02:00 UTC, hayden-ii commented on src/main/java/domain/lotto/LottoMetaData.java
> +    public static final Integer MIN_LOTTO_NUMBER = 1;
좋네요! 저는 LottoConstantVariable 이나 LottoConstant 도 좋을 것 같습니다 👍

2023-01-04 02:11 UTC, hayden-ii commented on src/main/java/domain/lotto/number/NumberGeneratable.java
> +package domain.lotto.number;
지금은 RandomNumberGenerator 밖에 없지만 Generator를 위한 interface 를 추가해두신 걸로 봐서 다른 Generator 도 추가가 될 것으로 예상이 되는데요, generator를 묶어둔 디렉토리이니 generator로 네이밍해도 괜찮을 것 같습니다. number를 그대로 두고 LottoNumberMaker를 LottoNumber 로 변경한 뒤, Generator 관련 함수만 generator 디렉토리 안에 두는 방식으로 변경을 하는 식으로도 가능할것 같구요. 저도 네이밍은 젬병이라 참고만 해주세요 ^_^)...

2023-01-04 04:37 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/ticket/LottoTicket.java
> +public class LottoTicket {
LottoTickets 를 LottoTicketList로 바꾸어 보았는데 이렇게 변경하면
이름이 조금 더 명확해졌을까요?!

2023-01-04 04:37 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/LottoMetaData.java
> +    public static final Integer MIN_LOTTO_NUMBER = 1;
LottoConstant 이렇게 수정했습니다!

2023-01-04 04:39 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/number/NumberGeneratable.java
> +package domain.lotto.number;
generator 와 number로 디렉토리를 나누었습니다!
그런데 제가 LottoNumber로 클래스 이름을 정했는데 이런 이름이면 마치 로또 티켓의 6자리중 한 자리를 뜻하는 느낌이기도한데
이 부분도 문제가 될 여지가 있을까요?

2023-01-04 04:54 UTC, hayden-ii commented on src/main/java/domain/lotto/ticket/LottoTicket.java
> +public class LottoTicket {
전 좋네요 ^_^ 👍

2023-01-04 04:58 UTC, hayden-ii commented on src/main/java/domain/lotto/number/NumberGeneratable.java
> +package domain.lotto.number;
그럴수도 있겠네요. LottoNumberMaker로 두는 편이 더 나으려나요... 🤔 LottoNumberMaker... LottoNumberGenerator... LottoNumberBuilder... LottoNumberMaker로 두고 lotto 디렉토리로 내려두는 것도 괜찮을 것 같고... 보시고 적절한 이름으로 편하게 수정해주셔도 됩니다!

2023-01-04 05:06 UTC, fbgnwhife1 commented on src/main/java/domain/lotto/number/NumberGeneratable.java
> +package domain.lotto.number;
LottoNumberGenerator을 보니까 이름을 수정하고 디렉토리도 이 쪽으로 옮기는 편이 깔끔한 것 같습니다! 감사합니다!

2023-01-04 05:15 UTC, hayden-ii approved these changes
수고하셨습니다 용도에 맞춰서 클래스 분리하고 사용하시는 작업 잘 해주셨습니다. 다음 과제도 잘 부탁드릴게요 ^_^ 👍

2023-01-04 05:16 UTC, merged