[Marcus.min] 로또 게임 Step1 리뷰 요청 드립니다.
2023newkrew/java-lotto-kakao pull request #38
Opened 2023-01-03 08:54 UTC by ekzm8523

안녕하세요. 이번주부터는 데드라인이 생겼네요!! 
## 1단계 리뷰 요청 마감 시간
- 놀금이 있는 경우: 화 오후 3시까지
- 놀금이 없는 경우: 수 오전 11시 59분까지
## 2단계 리뷰 요청 마감 시간
- 놀금이 있는 경우: 목 오후 3시까지
- 놀금이 없는 경우: 금 오전 11시 59분까지

하지만 저는 지키지 못했어요 😭 초반에 제대로 TDD를 해보고자 생성자부터 진짜 세밀한 TDD를 진행했는데 속도가 너무 느려 중간에는 기능개발을 중심으로 변질이 되었습니다..
완벽해서 제출하기보단 제출하고 완벽해지자는 마인드를 가지기로 했답니다🫠

### 특이 사항
- View를 Static Handling Method로 만들었습니다.
- Controller의 기능이 몇개 없어서 Application을 Controller로 보기로 하였습니다.
- LottoNumber는 Int와도 같고 사용되는 숫자 (1~45)를 캐싱하도록 구성하였습니다.

### 예상 리팩토링 지점
- Lotto 클래스의 LottoNumber가 List로 되어있다.
  - 현재 로또 숫자에 대한 비교를 위해서 Set으로 변환하고 비교를 하는데 이 부분을 LinkedHashMap 자료구조를 Wrapping해서 사용 할 예정입니다.
- indent는 1개까지 허용합니다.
- Stream으로 변경 가능한 for문 변경
- LottoGame.getResult 메서드 다이어트

2023-01-04 08:56 UTC, wade-lim requested changes
고생하셨습니다~

TDD 나 단위 테스트에 대한 적용 범위에 대해서는 말이 많은데요.

단순한 getter, setter 까지 모두 단위 테스트를 생성해야 한다는 의견도 있고, 반면에 현실적으로 적당히 복잡해질 것 같은 로직들만 테스트 해도 된다는 의견도 있습니다.

저는 테스트 작성 범위와 개발 리소스 간의 tradeoff 를 생각해서 적절히 각자 철학에 따라 범위를 조절해도 된다는 입장인데, 아무래도 너무 작은 단위(getter, setter)까지 테스트를 작성하면 추후 기능 확장이나 리팩토링 과정에서도 많은 리소스가 필요하다 보니 적당히 타협하는게 좋다고 생각하기 때문입니다.

오히려 사소한 부분에 대한 테스트에 집중하기 보다는 좀 더 테스트 하기 좋은 구조를 만드는데 집중을 하는게 좋다고 생각합니다.

ex)
- LottoView 에 InputStream 레이어를 추가해서 입출력에 대한 테스트 확장
- 1주차 레이싱카 random generator 를 외부에서 주입 받도록 하여 랜덤값에 의존하는 move 함수를 테스트 할 수 있게 설계

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/LottoGradeEnum.java
> +public enum LottoGradeEnum {
[의견]
enum 객체 이용하신거 깔끔하고 좋은 것 같네요~

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/LottoGradeEnum.java
> +            throw new IllegalArgumentException(INVALID_MATCH_COUNT_RANGE);
[의견]
에러 메세지를 따로 분리하는 것 보다 0, 6 을 상수로 만들고 메세지 쪽에서 이 상수를 이용해 범위를 출력하도록 하는게 좋을 것 같아요~

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/Lotto.java
> +    }
[의견]
클래스의 필드를 외부로 노출 시킬 때는 immutable 하게 노출 시키는게 좋을 것 같아요~

```java
return Collections.unmodifiableSet(lottoNumbers)
```

요런식으로 반환을 하면 외부에서 Set.add, Set.remove 와 같은 리스트를 수정하는 메소드 호출 시 Exception 이 발생하게 할 수 있습니다.

또한 원본 Set 을 전부 복사하는 것이 아닌, Set 에 대한 레퍼런스만 보관해두고 사용하는 식으로 구현되어 있기 때문에 성능 오버헤드가 그렇게 크지 않습니다.
   - 객체 1개 생성 비용 + 객체 내부 원본 List 에 대한 reference

위 함수가 어떻게 구현됐는지 직접 확인해보는 것도 Java 에서 추구하는 철학을 알 수 있는 방법 중 하나라 좋을것 같습니다 😄
   - 지난주 코멘트 드렸던 ImmutableCar 과 비슷합니다

[(참고) 객체 불변성이 필요한 이유](https://steady-coding.tistory.com/559)

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGenerator.java
> +        IntStream.range(0, lottoCount).forEach((i) -> lottos.add(generateLotto()));
[의견]
`map` 과 `collect` 를 사용하면 `lottos` 없이 구현할 수 있을거 같아요~

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGenerator.java
> +    static public List<Lotto> generateLottos(int price) {
[의견]
키워드 순서에 정해진 규칙은 없지만, 아래와 같이 정렬하는걸 권장한다고 하네요~

https://johngrib.github.io/wiki/java-modifier-order-with-jls-suggestion/

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGenerator.java
> +        Collections.shuffle(fullNumbers);
[확인]
`Collections.shuffle` 은 thread safe 하지 않아서 공유 변수로 사용되는 `fullNubers` 를 곧바로 수정해버리는건 위험할거 같아요~
메모리가 조금 더 소모되더라도 함수 내에서 `fullNumbers` 를 생성하는건 어떨까요?

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/LottoGradeEnum.java
> +    public final int price;
[의견]
enum 이고 상수값이지만 private 후 getter 를 사용하는게 좋을거 같아요!
Java 에서는 필드에 직접 접근하는걸 꺼려하고, 함수형으로 사용할 때 `LottoGradeEnum::getMatchCount` 와 같은 문법을 사용할 수 없어서 불편할 때가 있거든요~

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGradeCounter.java
> +                .collect(Collectors.toMap(LottoGradeEnum::getGrade, i -> 0));
[의견]
Enum.values() 를 사용하면 좀 더 쉽게 Map 을 만들 수 있을거 같아요~

```java
Arrays.stream(LottoGradeEnum.values())
  .collect(Collectors.toMap(Function.identity(), grade -> 0));
```

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
[의견]
`map` 과 `toArray` 를 사용하면 static initializer 를 사용하지 않아도 될거 같아요~

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/view/LottoView.java
> +}
[의견]
모든 로직을 static 하게 작성해도 현재는 문제가 없지만, 추후 확장성이 제한될 수 있습니다.

예를 들어 입력 소스를 표준 입력 외에도 네트워크, 파일 등을 사용하도록 확장해야 하는 경우 메소드들이 static 하지 않다면 `LottoView` 생성자에서 `InputStream` 을 주입받도록 간단하게 변경하는 식으로 기능을 쉽게 확장할 수 있습니다.

```java
class LottoView {
  private final Scanner scanner;

  private LottoView(Scanner scanner) { 
    this.inputStream = inputStream;
  }

  public static LottoView create() {
    return LottoView.create(System.in);
  }

  public static LottoView create(InputStream is) {
    return new LottoView(is);
  }
}
```

```java
LottoView.create(); // 기본값 - stdin
LottoView.create(new FileInputStream("file")); // 파일 사용

// (deprecated) 입력된 String 을 그대로 사용 
// 테스트에 사용하면 유용한 방법
LottoView.create(new StringBufferInputStream("14000\n1, 2, 3, 4, 5, 6\n7"));
```

static 메소드는 가능하면 범용적으로 사용되고 의존 관계가 적은 유틸성 로직에만 사용하는게 좋습니다.

2023-01-04 08:56 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGame.java
> +        return new ArrayList<>(lottos);
[질문]
ArrayList 로 포장하여 반환하는 이유가 있을까요?
Collections.unmodifiableList() 로 반환하는건 어떨까요?

2023-01-04 09:37 UTC, ekzm8523 commented on src/main/java/lotto/LottoGradeEnum.java
> +            throw new IllegalArgumentException(INVALID_MATCH_COUNT_RANGE);
``` suggestion
            throw new IllegalArgumentException(String.format("%d에서 %d사이의 값을 입력해야 합니다." MIN_COUNT, MAX_COUNT));
```
이런 형태를 말씀하신게 맞나요?

2023-01-04 09:37 UTC, ekzm8523 commented on src/main/java/lotto/domain/LottoGenerator.java
> +        Collections.shuffle(fullNumbers);
thread safe까지는 고려를 못했네요!! 찾아보니 shuffle 내부의 Random이 Non-Thread-safe 인 것 같은데 ThreadLocalRandom으로 변경해주어 사용하면 어떨까요?

https://stackoverflow.com/questions/40840421/calling-java-util-collections-shuffle-from-multiple-threads

2023-01-04 09:59 UTC, ekzm8523 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
선언과 동시에 stream을 이용해 static initializer를 사용하지 않는 방법은 찾았는데요!
``` Java
private static final LottoNumber[] CACHED_LOTTO_NUMBER = IntStream
            .range(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER + 1)
            .mapToObj(LottoNumber::new)
            .toArray(LottoNumber[]::new)
```
위와 같은 방식으로 선언하면 되긴 하지만 배열로 되어있기 때문에 인덱스가 하나씩 댕겨지는 문제가 있습니다
ex) CACHED_LOTTO_NUMBER[44] == Number(45)
잔머리를 굴리면 range에서 MIN_LOTTO_NUMBER - 1 부터 시작하도록 하는 방법이 있고 return 할 때 number-1 인덱스를 사용하는 방법이 있을 것 같아요. (사실 어차피 Validation에서 0은 걸리긴 합니다... ㅎㅎ)
선언을 하면서 CACHED_LOTTO_NUMBER[0]에는 null이 들어가게 하는 방법은 없을까요?

2023-01-04 10:01 UTC, ekzm8523 commented on src/main/java/lotto/view/LottoView.java
> +}
저도 마침 오늘 객체지향적 프로그래밍에 대한 아티클을 읽었는데요!! static 클래스를 만드는건 아주 나쁜 패턴이라고 하더라구요 ㅎㅎ 이전에 하던 방식으로 변경할게요~!

2023-01-04 11:41 UTC, ekzm8523 commented on src/main/java/lotto/domain/LottoGradeCounter.java
> +                .collect(Collectors.toMap(LottoGradeEnum::getGrade, i -> 0));
사실 이건 트릭을 조금 섞은건데요!!
`LottoGradeEnum`에 NONE_GRADE 값이 존재하는데 NONE_GRADE 는 카운팅을 하지 않아야 해서 Range로 1등부터 5등까지 getGrade를 해오는 방식으로 구성했어요 ㅎㅎ 더 좋은 방법이 존재할까요?

2023-01-04 12:05 UTC, ekzm8523 commented
@wade-lim 리뷰주신 부분 반영 하였고 몇개에 코멘트를 더 달았는데 <u>**⭐️내일 출근하시면⭐️**</u> 답변 부탁드릴게요 😊

2023-01-05 04:35 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGradeCounter.java
> +                .collect(Collectors.toMap(LottoGradeEnum::getGrade, i -> 0));
@ekzm8523 
좀 비효율적이지만 중간에 filter 를 섞어주는 것도 좋을거 같아요~

2023-01-05 04:44 UTC, wade-lim commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
@ekzm8523 
앗.. index 가 1부터 시작이었군요~
그러면 기존 방법 대로 하셔도 괜찮을거 같아요~

2023-01-05 04:46 UTC, merged