[kloong.96] 로또 미션 제출합니다
2023newkrew/java-lotto-kakao pull request #43
Opened 2023-01-03 09:57 UTC by Kloong1

로또 미션 제출합니다.

1차 과제에서 코멘트 해주셨던 부분을 최대한 지키면서 구현해봤습니다.
클래스를 잘 쪼개는게 이번 과제의 핵심이었던 것 같은데 잘 쪼갠건지 모르겠네요 ㅎㅎ...

이번 리뷰에서 궁금한 것 + 봐주셨으면 하는 부분은 이렇습니다.

### Enum 에서 static method 구현
[LottoPrize Enum](https://github.com/next-step/java-lotto-kakao/commit/247aa657bf42c54389c4f986ba5042b4f69eaef8)
여기서 처음에는 Enum 내부에서 `findPrize()` 메소드를 가지게끔 구현했는데, 저는 LottoPrize Enum이 다른 도메인 객체와의 의존도가 높아지는 것 같아서 `LottoNumberMatcher` 객체를 만들어서 해당 객체로 로직을 위임했습니다.

전자처럼 Enum에 저런 로직을 구현하는 방식이 실무에서도 사용하는 방식인지 궁금합니다.

또 저의 선택(의존도를 낮추기 위해 객체 분리)이 좋은 선택인지도 의문이고요. 사실 Enum이 의존하는 `LottoPrizeJudgement` 도 `LottoTicket`과 `LottoWinningNumber`를 의존하고 있어서 이게 의미있는 클래스 분리였는지 모르겠네요.

### service 패키지의 객체들
도메인 부분에서는 클래스를 쪼개는 데 크게 어려움이 없었는데, 해당 도메인 객체들을 사용하는 서비스 객체들은 클래스를 잘 쪼갠건지 모르겠네요. 나름 리팩토링 한다고 이런 저런 시도를 해봤는데 쉽지 않은 것 같습니다 ㅜㅜ

PS - 최대한 빨리 리뷰요청 하고 싶었는데 리팩토링 하다보니 시간이 늦었네요 ㅜㅜ 다음주부터는 더 빨리 리뷰요청 하도록 해보겠습니다. 아무래도 이번주까지 페어 프로그래밍 방식으로 진행되다보니 근무 시간에만 코딩을 할 수 있어서 어쩔수가 없는 부분이 있네요 ㅜㅜ 이번 리뷰도 잘 부탁드리겠습니다!

2023-01-04 02:17 UTC, NESOY requested changes
고생 많으셨습니다. **클래스를 잘 쪼개는게 이번 과제의 핵심**이라고 하셔서 중점적으로 보았습니다 ㅎㅎ

> Enum 에서 static method 구현
Enum에 저런 로직을 구현하는 방식은 많이 사용하고 있습니다. 결국엔 enum도 어떠한 책임을 가지느냐에 따라 책임에 따른 행위(로직)을 가져도 상관없다고 생각해요 :)

아래의 링크를 확인해보면 많은 도움이 되실거 같습니다.
- https://techblog.woowahan.com/2527/
- https://johngrib.github.io/wiki/java/enum/#interface를-사용해-확장한다

> service 패키지의 객체들
service로 정의할만한 클래스들이 없다면 따로 분류를 안해도 괜찮을거 같아요!
아래의 방법으로 접근해보면 어떨까요?

1. 일단 도메인 단위로 분류해보자.
2. 서로 다른 도메인들끼리 섞이는 새로운 Mix객체가 생긴다면? 그때 Service로 따로 분류해보면 어떨까요?

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoTicket.java
> +    private void validateDuplicates(List<LottoNumber> lottoNumbers) {
중복을 허용하지 않으면 List보다 더 적절한 자료구조가 있지 않을까요? 🤔

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoEarningRate.java
> +        if (earningRate < 0.0) {
위 값도 상수화하면 더 좋지 않을까요? 🤣

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoPrize.java
> +    FIRST_PRIZE(2_000_000_000, new FirstLottoPrizeJudgment()),
좋은 표기법이네요 👍

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoTicket.java
> +        this.lottoNumbers = new ArrayList<>(lottoNumbers);
LottoTicket 생성자에서 lottoNumbers관련 작업을 많이 하는거 같은데 lottoNumbers 책임을 분리해보는건 어떨까요? 🤔

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoTicketRandomGenerator.java
> +        return new LottoTicket(lottoNumberCandidates.subList(0, LottoTicket.LOTTO_NUMBERS_SIZE));
코드를 확인해보니 새로운 List로 생성해서 문제는 안될거 같지만, subList사용시 아래의 케이스도 있으니 참고해주세요 :)

```
ArrayList<String> list = new ArrayList<String>();

list.add("1");
list.add("2");
list.add("3");
list.add("4");
List<String> subList = list.subList(2,4);
list.remove(1);
```

아래의 에러가 발생할 가능성이 있습니다 ㅠ 
```
Exception in thread "main" java.util.ConcurrentModificationException
at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1169)
```

subList를 반환하면 새로운 리스트가 아닌, 내부적으로 subList를 만들어서 반환하기 때문에 이전 List의 Reference를 공유하고 있습니다. 그래서 다른곳에서 변경을 진행하면 에러가 발생하고, 디버깅하기 매우 어려운.. 상황이 벌어집니다 ㅠ

## Reference
- https://knight76.tistory.com/entry/Java의-List의-subList와-Set의-subSet-비교

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoTicketRandomGenerator.java
> +        List<LottoNumber> lottoNumberCandidates = IntStream.range(LottoNumber.MINIMUM_VALUE, LottoNumber.MAXIMUM_VALUE)
Generate 결정관련 값들을 매개변수로 받으면 어떨까요? 🤔 
- 테스트하기에도 편할거같고 변경에 유리한 구조가 될거 같아요

2023-01-04 02:17 UTC, NESOY commented on src/main/java/domain/lotto/LottoWinningNumber.java
> +        this.lottoNumbers = lottoNumbers;
LottoWinningNumber에서 `List<LottoNumber> lottoNumbers`관련 책임을 분리해보는건 어떨까요?

2023-01-04 02:17 UTC, NESOY commented on src/test/java/service/LottoPrizeResultTest.java
> +    HashMap<LottoPrize, Integer> prizeCounts;
자료구조 타입은 구체적인 HashMap보다는 interface인 Map을 사용하는게 더 좋습니다. 나중에 HashMap이 아닌 다른 Map을 사용했을때 변경을 최소화 할 수 있어요 😁

2023-01-04 02:17 UTC, NESOY commented on src/test/java/domain/lotto/LottoTicketTest.java
> +    @DisplayName("로또 번호가 6개가 아니면 예외가 발생한다")
더 많은 케이스도 추가적으로 테스트하면 어떨까요?

2023-01-04 02:17 UTC, NESOY commented on src/test/java/domain/lotto/LottoNumberTest.java
> +    @DisplayName("범위 밖의 로또 번호를 입력하면 예외가 발생한다.")
음수도 테스트하면 좋을거 같아요 :)

2023-01-04 02:17 UTC, NESOY commented on src/main/java/view/LottoOutputView.java
> +        System.out.println("3개 일치 (" + LottoPrize.FIFTH_PRIZE.getPrizeMoney() + "원)-" +
String.format을 사용해보는건 어떨까요?

2023-01-04 02:17 UTC, NESOY commented on src/main/java/service/LottoShop.java
> +        ArrayList<LottoTicket> lottoTickets = new ArrayList<>();
타입선언시에는 interface인 List를 사용하는게 좋습니다. 나중에 다른 List를 사용할때 타입 변경을 최소화 할 수 있습니다 ㅎㅎ

2023-01-04 02:17 UTC, NESOY commented on src/main/java/service/LottoPrizeResult.java
> +public class LottoPrizeResult {
이 객체는 service보다는 domain쪽이 어울리지 않을까요? 🤔

2023-01-04 02:17 UTC, NESOY commented on src/main/java/service/LottoNumberMatcher.java
> +public class LottoNumberMatcher {
`LottoNumberMatcher` 대신 예전에 구현해주셨던 방식이 더 좋다고 생각합니다 :)
- LottoNumberMatcher와 lottoPrize.prizeJudgment의 역할이 애매해서 한쪽으로 모아보는게 더 좋을거 같아요
https://github.com/next-step/java-lotto-kakao/commit/247aa657bf42c54389c4f986ba5042b4f69eaef8

2023-01-04 07:31 UTC, Kloong1 commented on src/main/java/domain/lotto/LottoTicket.java
> +        this.lottoNumbers = new ArrayList<>(lottoNumbers);
이 부분은 좀 생각을 해봤는데, `LottoTicket`을 `List<LottoNumber>` 에 대한 일급 컬렉션 이라고 생각하고 구현한 거라서 이렇게 된 것 같습니다.
근데 이제 로또 프로그램이다 보니까, 단순히 로또 번호의 집합이라는 의미보다는 로또 번호의 집합이 곧 `복권`이라는 의미를 강조하기 위해서 네이밍을 `LottoNumbers`가 아닌  `LottoTicket`이라고 하게 된 것이구요.
실제로 validation과 getter 말고는 다른 로직이 없기도 합니다.

그래서 말씀하신 "LottoTicket 생성자에서 lottoNumbers 관련 작업을 많이 하기" 때문에 분리를 해야 할 필요는 없다고 느껴지는데, 혹시 분리를 해야 할 다른 이유가 있을까요? 아니면 네이밍을 `LottoNumbers`로 바꾸는게 나은걸까요?

2023-01-04 07:35 UTC, Kloong1 commented on src/main/java/domain/lotto/LottoTicket.java
> +        this.lottoNumbers = new ArrayList<>(lottoNumbers);
앗 코멘트가 많아서 일부가 가려져있었네요;;

[> LottoWinningNumber에서 List<LottoNumber> lottoNumbers관련 책임을 분리해보는건 어떨까요?](https://github.com/next-step/java-lotto-kakao/pull/43#discussion_r1061061908)

말씀하신 요 부분까지 고려하면 `LottoTicket`을 그냥 `LottoNumbers`로 네이밍만 바꾸고 `LottoWinningNumber`에서 사용하도록 만들어도 될 것 같습니다! ㅎㅎ

2023-01-04 19:04 UTC, Kloong1 commented on src/main/java/view/LottoOutputView.java
> +        System.out.println("3개 일치 (" + LottoPrize.FIFTH_PRIZE.getPrizeMoney() + "원)-" +
`System.out.println(String.format())` 을 사용했더니 SonarLint가 중복된 코드라서 printf() 를 사용하라고 해서 그렇게 고쳐봤습니다 ㅎㅎ

[180689f](https://github.com/next-step/java-lotto-kakao/pull/43/commits/180689fe59388377fe46412302cc8d5b84606a30)

2023-01-04 19:27 UTC, Kloong1 commented
안녕하세요 nesoy. 리뷰해주신 부분 최대한 적용해 보았습니다.

### LottoNumbers
`LottoTicket` 클래스를 `LottoNumbers` 로 이름을 바꾼 뒤 `List<LottoNumber>` 에 대한 일급 컬렉션처럼 생각하고 리팩터링을 하니까 중복된 코드도 사라지고 깔끔하니 좋은 것 같습니다.
[6469907](https://github.com/next-step/java-lotto-kakao/pull/43/commits/64699078489bad7de6933e6d1053b1d285af80fd)

`LottoWinningNumber` 가 `LottoNumbers`를 가지고 있게 변경해보았습니다.
[a9cebdb](https://github.com/next-step/java-lotto-kakao/pull/43/commits/a9cebdbce12d5e979069ca05ec001c0628402dd3)

### LottoTickets
`List<LottoNumbers>`를 다시 한 번 감싸는 일금 컬렉션인 `LottoTickets` 까지 만드니까 클래스의 역할이 명확해지고, 뭔가 애매하던 클래스 (예를 들어 `LottoPrizeCounter`)들의 역할을 `LottoTickets`에 위임할 수 있었습니다.
[35979a2](https://github.com/next-step/java-lotto-kakao/pull/43/commits/35979a2ccf4067c88c7f16ccae1b1cd1614d243b)

또 기존에 몇 장의 복권을 구매했는지, 또 구매 비용이 정확히 얼마인지 구하는 로직이 따로 메소드 형태로 구현되어 있지 않아서 필요할 때마다 계산을 했어야 했는데, 이 로직들을 `LottoTickets` 내부에서 구현하게 하니 편리했습니다.

### Service 패키지 제거
클래스를 더 세분화했더니 서비스 패키지를 제거할 수 있게 되었습니다. 마지막에 `LottoShop` 하나가 서비스 패키지에 남아있었는데 도메인 성격이 더 강한 것 같아서 최종적으로 옮겼습니다.

### 기타 궁금한 점
`null` 체크는 값을 넘겨받는 쪽에서 항상 해줘야 하는 건가요? 지금까지는 거의 신경쓰지 않고 진행했는데, 뭔가 위험할 수도 있을 것 같다는 생각이 듭니다.

디테일한 리뷰 항상 감사합니다! ㅎㅎ

2023-01-05 04:44 UTC, NESOY requested changes
리뷰 반영하느라 고생 많으셨습니다 👏 
사소한거 몇가지 추가 의견드렸는데 확인해주신 후에 다음 단계로 넘어가도 될거 같습니다 🙇‍♂️

> null 체크는 값을 넘겨받는 쪽에서 항상 해줘야 하는 건가요? 지금까지는 거의 신경쓰지 않고 진행했는데, 뭔가 위험할 수도 있을 것 같다는 생각이 듭니다.

사실 Java에서 널에 대한 처리가 그렇게 좋지 않기 때문에; 안전하게 코딩하기 위해선 넘겨받는 쪽에서 항상 하는게 좋다고 생각합니다 ㅎㅎ 코틀린에서는 언어 자체에서 널 처리를 안전하게 해주는 장치가 있습니다.
https://codechacha.com/ko/kotlin-null-safety/

2023-01-05 04:44 UTC, NESOY commented on src/main/java/domain/lotto/LottoPrize.java
> +        return Arrays.stream(values())
Prize 당첨 검증 순서에 대한 보장이 필요한거 같은데 어떻게 생각하세요?
- Prize 검증방법이 1등에서 낮은 순서대로 가야 정확하게 검증이 되는 로직
- 테스트로 순서를 보장해도 괜찮을거 같고, 코드를 변경해도 괜찮을거 같아요

2023-01-05 04:44 UTC, NESOY commented on src/main/java/domain/lotto/LottoNumbers.java
> +        HashSet<LottoNumber> intersection = new HashSet<>(numbers);
```suggestion
        Set<LottoNumber> intersection = new HashSet<>(numbers);
```

2023-01-05 04:44 UTC, NESOY commented on src/main/java/domain/lotto/LottoNumbersRandomGenerator.java
> +        List<LottoNumber> lottoNumberCandidates = IntStream.range(lowerBound, upperBound + 1)
IntStream.range 대신 IntStream.rangeClosed로 의도하신거 같은데 맞나요? 🤔

2023-01-05 07:50 UTC, Kloong1 commented on src/main/java/domain/lotto/LottoPrize.java
> +        return Arrays.stream(values())
`values()`가 선언된 순서로 반환하긴 하지만 조금 찝찝하긴 했는데, 말씀하신 대로 정렬을 통해 검증 순서를 보장해 보았습니다.
상금 금액 순으로 내림차순 정렬한 뒤 당첨 여부를 판단하는 로직으로 변경했습니다.

[8c62840](https://github.com/next-step/java-lotto-kakao/pull/43/commits/8c62840cd2f324d971aed24e0ba61349e3f6fe4a)

2023-01-05 08:05 UTC, Kloong1 commented
리뷰 기다리면서 2단계를 진행하다가 실수로 푸쉬를 해버리는 바람에 커밋이 좀 꼬였습니다 ㅜㅜ
복구하긴 했는데 diff가 좀 이상한 것 같기도 하네요 ㅜㅜ 양해 부탁드립니다 ㅜㅜ

2023-01-05 08:54 UTC, NESOY approved these changes
고생많으셨습니다 다음 단계에서 뵙겠습니다 🙇‍♂️

2023-01-05 08:54 UTC, merged