[minion.mo] 로또 step2
2023newkrew/java-lotto-kakao pull request #53
Opened 2023-01-04 05:45 UTC by gusah009

안녕하세요 조엘!

앞서 step1의 코드 리뷰 사항과 추가 요청사항을 반영해서 한 번 개발해봤습니다.

이번에도 잘 부탁드립니다!! 🙇‍♂️🙇‍♂️🙇‍♂️

2023-01-05 12:33 UTC, haewon13 requested changes
고생 많으셨습니다 미니언~!! 1단계에서 드린 피드백도 잘 반영되어있고 
추가 기능에 대해서도 유연하게 처리될 수 있게 TotalLottoCount 리팩토링하신게 너무 좋습니다. 좋은 객체 분리 같아요~ 
코멘트 몇가지 남겼으니 확인 부탁드리겠습니다 :)



+) 그리고 코드를 다시 보다보니깐 변경사항이 없는 곳이지만 한가지 제안드리고 싶어서 추가로 남겨봅니다ㅎㅎ 

Lotto에서 getter로 외부에 numbers 넘겨주지 않고, 객체 내에서 처리되게끔 잘 구현해주셨어서 굳이 제안드리진 않았었는데요! 
그럼에도 Nit로 드리자면, Lotto 정적팩토리메서드에서 toList 대신 toUnmodifiableList을 사용해서 불변을 강조하면 어떨까 싶네요!

2023-01-05 12:33 UTC, haewon13 commented on src/main/java/javalotto/view/InputView.java
> +    private static List<Integer> getNumberListBy(String inputNumbers) {
사용자가 수동번호 입력하는 부분을 당첨번호 입력한 부분과 같이 사용하셨군요. 
제가 1차 리뷰때 놓친 부분 같은데 사용자가 유효하지 않은 숫자 외의 값을 입력했을때 의도하셨던 LottoNumberOutOfRangeException 대신 parseInt에서의 NumberFormatException이 발생합니다!

unique와 범위에 대한 체크는 잘 해주셨는데 이 부분도 catch해서 처리하면 어떨까 싶네요ㅎㅎ

2023-01-05 12:33 UTC, haewon13 commented on src/main/java/javalotto/controller/LottoController.java
> +        LottoCount totalLottoCount = LottoCount.of(purchaseAmount, PURCHASE_AMOUNT_UNIT_PRICE);
로또 개당 가격에 대한 상수값을 Controller에서 불러서 넣어줄 필요없이. LottoCount 정적팩토리메서드 단에서 purchaseAmount 인자만 주어지면 상수를 가져와서 계산하면 어떨까 싶네요!

실제 코드에서는 양수임이 분명한 상수값으로 넣어줘서 괜찮지만
unitPrice을 받아서 나눠주는 로직이 있는 이상, 해당 인자로 받은 unitPrice가 0은 아닌지 등의 validation이 추가로 필요해보여서요. 고정된 값을 사용하고 있으니 외부에서는 신경쓰지 않고 아예 내부에서 알아서 상수로 처리하는거죠ㅎㅎ

2023-01-05 12:33 UTC, haewon13 commented on src/main/java/javalotto/controller/LottoController.java
> +        return inputView.getPurchaseAmountInput();
한줄이어도 다른 input과 통일성있게 뺴주셨군요 미니언만의 기준이 있는것 같아서 좋습니다 👍

2023-01-05 12:33 UTC, haewon13 commented on src/main/java/javalotto/domain/TotalLottoCount.java
> +        LottoCount automaticallyLottoCount = totalLottoCount.getRemainExceptFor(manuallyLottoCount);
해당 getRemainExceptFor 메서드의 목적이 궁금합니다!
LottoCount 내에 count getter가 있는 이상 불필요해보여서요~
```suggestion
        LottoCount automaticallyLottoCount = LottoCount.withCount(totalLottoCount.getCount() - manuallyLottoCount.getCount());
```

suggestion을 위해서 불리는 쪽에다가 코멘트를 달았는데요 
LottoCount 입장에서는 getCount을 제공하고 있기도 하고, 각 LottoCount끼리의 연산 로직이 객체의 역할 내의 필수 기능은 아닌것 같아서 제안드려봅니다ㅎㅎ

2023-01-05 12:33 UTC, haewon13 commented on src/test/java/javalotto/domain/LottoCountTest.java
> +                .isInstanceOf(LottoCountNegativeException.class);
추가된 기능에 대한 상세 exception test 좋습니다 👍

2023-01-09 00:21 UTC, gusah009 commented on src/main/java/javalotto/view/InputView.java
> +    private static List<Integer> getNumberListBy(String inputNumbers) {
감사합니다!! 이걸 빠뜨렸었네요!

2023-01-09 00:27 UTC, gusah009 commented on src/main/java/javalotto/controller/LottoController.java
> +        LottoCount totalLottoCount = LottoCount.of(purchaseAmount, PURCHASE_AMOUNT_UNIT_PRICE);
**step1**에서 해주신 커멘트랑 같네요! 상수로 처리하는 방식으로 도입했습니다!!

조엘 말씀대로 추가 validation을 하지 않고 내부에 숨길 수 있어서 더 좋은 방식인 것 같네요!

2023-01-09 00:33 UTC, gusah009 commented on src/main/java/javalotto/domain/TotalLottoCount.java
> +        LottoCount automaticallyLottoCount = totalLottoCount.getRemainExceptFor(manuallyLottoCount);
동의합니다!! _**객체에 메시지를 던져서 결과를 얻어온다**_ 라는 문구에 너무 몰입해있어서 값 객체에도 이런 기능을 만들어버렸네요 ㅎㅎ

```java
Integer a = 3;
a.minus(2);
```
이런 메서드가 없듯이, 객체가 값을 던지는 **값 객체**인 이상 저런 기능까진 필요가 없었는데 좀 과했던 것 같습니다! ㅎㅎㅎ

2023-01-09 01:27 UTC, merged