[baero.kero] Lotto 2단계
2023newkrew/java-lotto-kakao pull request #55
Opened 2023-01-04 06:19 UTC by BaeRoNuI

2023-01-05 03:57 UTC, teddy-ready requested changes
멘션 드린부분 한번만 더 고민해 보시고 PR 주시면 머지 합니다

2023-01-05 03:57 UTC, teddy-ready commented on src/main/java/lotto/controller/LottoController.java
>          outputView.printStatistics(statistics, getRate());
솔직히 말씀 드리자면, 현재 코드는 컨트롤러가 너무 복잡해서 가독성이 많이 떨어짐니다. 어려운 로직이 아닌데 답답해 보이는 이유는 메소드로 레핑과 레핑을 거급하고 잇지만, 어떤 일관된 컨셉없이 메소드로 분리를 해나가고 있어서로 보입니다 ㅠㅠ 한번더 생각해 보시고 리팩터링했으면 합니다만, 어렵다고 느껴지시면 그냥 머지해 드릴수도 있으니 한번 고민해 보았으면 합니다~

예를 들면, run 메소드는 컨트롤러의 핵심이고 절차적인 흐름을 읽어내려갈수 있게 템플릿 패턴을 활용한다면, 
대체 가능하고 확장가능한 영역만 별도 메소드로 분리하고 나머지 부분은 그냥 기술하는게 나을듯합니다 .

public void run() {
   int numberOfLotto = 0;
   Integer numberOfLottoWithManual = 0;

    outputView.askForMoneyToBuyLotto();
    numberOfLotto = parseNumberOfLotto(inputView.getInteger());

    outputView.askForNumberOfLottoWithManual();
    numberOfLottoWithManual = parseNumberOfLottoWithManual(inputView.getInteger());

     // 이런 느낌을 살려서??? 하면 좋을것 같다는 의견입니다. 
}

2023-01-05 05:19 UTC, BaeRoNuI commented
저도 코딩하면서 스스로 Controller가 너무 비대해지고, 가독성이 나빠진다는 느낌이 들었습니다. 수정해야 되는 부분이 맞았군요.. 리팩토링 하면서 고려한 부분에 대해 말씀드리겠습니다.

* Controller의 run 메소드만 보고, 대충 어느 로직인줄 알 수 있어야 한다고 생각하여, 수정하였습니다. 그래서, Run은 다음과 같이 간단한 부분만 갖고 있습니다.
```Java
public void run() {
    setLotto();
    setGoal();
    showResult();
}
```

* LottoStatistic 이라는 클래스가 있는데, rate를 controller에서 계산하는 부분이 부자연스럽다고 생각하여 옮겼습니다.

* InputView에서 String, Integer 등등 여러 타입으로 받아오기에, split 정도는 수행해도 괜찮겠다 생각하여 옮겼습니다.

* 위와같이 리팩토링을 하고 나니, numberOfTotalLotto, numberOfMannualLotto가 전역으로 있을 필요가 없어 setLotto()안의 지역변수로 수정하였습니다.

* Controller 안의 메소드가 로직의 진행 순서와 무관하게 나열되어 있어, 같은 코드임에도 가독성이 매우 떨어지고 있다고 느꼈습니다. 그렇기에, 전체적인 flow에 맞게 위치를 추가로 수정하였습니다.

* lotto 의 개수를 가져오는 로직이 한줄임에도 따로 메소드를 만들었습니다. 잘못된 input에 대해 다른 처리를 할 수 있다고 생각하였고, 메소드로 애초에 빼놓은 다면 어디를 수정할지 명확하다고 생각하여 따로 합치지는 않았습니다.

한단계 한단계 수정을 할때마다 commit을 해야했지만, 체계적으로 수행하지는 못해서 commit 하나에 여러 작업이 들어가있습니다. 다음부터는 조금 더 신경써서 진행하도록 하겠습니다.

감사합니다!

2023-01-09 07:20 UTC, teddy-ready approved these changes
머지 할게요~ 수고하셨어요~

2023-01-09 07:20 UTC, merged