[Tank.500m] 2차 과제 PR입니다.
2023newkrew/java-lotto-kakao pull request #56
Opened 2023-01-04 06:34 UTC by fbgnwhife1

로또 수동 구매 기능을 추가하기 위해 LottoController 와 InputView 만 조금 수정을 했고,
InputView에서 중복으로 쓰이는 코드를 inputNumbers 메소드로 따로 빼내었습니다.
조금 고려해 봐야할 것 같은 것은 컨트롤러 부분에서 createLottoTickets 의 코드가 너무 지저분한 느낌이 있어서
이것을 InputView에서 미리 통합하는 과정을 거치는 것이 좋을지 고민됩니다.
감사합니다!

2023-01-05 02:33 UTC, hayden-ii requested changes
커맨트 몇개 확인 부탁드립니다. 새로 추가된 기능에 대한 테스트 케이스도 추가되어야 할 것 같네요~

2023-01-05 02:33 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
지난번에 놓쳤는데 여기 타입을 int가 아니라 Integer 로 사용하신 이유가 있을까요?

2023-01-05 02:33 UTC, hayden-ii commented on src/main/java/view/InputView.java
> +    public static List<LottoTicket> inputManualLottoNumbers(Integer purchaseAmount) {
pr 범위에 포함이 되어있지 않아 여기에 추가합니다. "수동으로 3장, 자동으로 11개를 구매했습니다." 라는 메세지가 나와야 할 것 같은데 총 구매 개수만 출력이 되는걸로 보입니다. 확인 부탁드립니다.

2023-01-05 02:33 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
intellij 님의 추천으로는
```
List<LottoTicket> lottoTicketList = new ArrayList<>();
lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
```
를
```
List<LottoTicket> lottoTicketList = new ArrayList<>(InputView.inputManualLottoNumbers(purchaseAmount));
```
와 같이 작성할 수 있다고 하네요

2023-01-05 04:26 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
아 이 부분은 요구사항에 원시값과 문자열을 포장하라고 되어있어서 이렇게 하라는건가 하고 사용했습니다..

2023-01-05 05:24 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
아래 링크에 다른 분이 올려주신 내용 참고해보시면 좋을것 같아요
https://velog.io/@jhp1115/%EC%9B%90%EC%8B%9C%EA%B0%92%EA%B3%BC-%EB%AC%B8%EC%9E%90%EC%97%B4-%ED%8F%AC%EC%9E%A5

2023-01-05 05:31 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
아하 이런 뜻이었군요...! 감사합니다!

2023-01-05 05:35 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
혹시 그럼 WinningNumbers 의 bonusNumber도 BonusNumber라는 클래스로 두는 것이 좋다.
이런 식으로 이해하면 되는 걸까요?

2023-01-05 05:35 UTC, fbgnwhife1 commented on src/main/java/view/InputView.java
> +    public static List<LottoTicket> inputManualLottoNumbers(Integer purchaseAmount) {
넵 수정하겠습니다!

2023-01-05 05:35 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
넵 이 부분도 적용시키겠습니다!

2023-01-05 05:45 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
잠깐 생각해보기로는 bonusNumber 에 대한 클래스를 생성하는게 아니라 lottoNumber를 만들고
```
List<Integer> lottoNumbers -> List<LottoNumber> lottoNumbers
Integer bonusNumber -> LottoNumber bonusNumber
```
이런 방향으로 변경 할 수도 있을 것 같구요.

2023-01-05 05:51 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
음 그렇군요 적용시켜보도록 하겠습니다! 시간이 조금 걸릴 것 같습니다..ㅠㅠ

2023-01-05 06:00 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
createLottoTickets가 길어지는게 신경쓰인다고 하셔서 보고 있는데, inputManualLottoNumbers 안에서 로또 수와 번호를 한 번에 가져오려다보니 manual과 random을 분리하기가 어려워지는게 아닌가 하는 생각도 드네요...

(1) inputManualLottoNumbers의 기능을 적절히 분리하고, (2) createLottoTickets 함수내의 코드를 createManualTickets(), createRandomTickets() 로 나눠서 작성할 수 있으면 좀 더 깔끔해보이지 않을까 싶어요.
^_^ 참고만 해주세요~

2023-01-05 06:01 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
제 커맨트에 넘 부담갖지 마시고 참고만 한다고 생각하고 편하게 작업해주세요~

2023-01-05 09:50 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
>          Integer purchaseAmount = InputView.inputPurchaseAmount();
넵 알겠습니다! 적용시켜보았는데 많은 양을 변경하다 보니까 조금 어수선하게 바꾼 것 같긴합니다 ㅠㅠ

2023-01-05 09:50 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
앗 이 코멘트를 지금 봤네요 ㅠㅠ 고치고 나서 코멘트 달도록 하겠습니다!

2023-01-05 10:00 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
지금 기능을 좀 나누어 보았는데 
LottoTicket.addAutoLottoTickets(lottoTicketList, purchaseAmount - manualCount);
이 부분에서 LottoTicket에 static 메소드를 추가해주었는데 문제가 되는 부분이 있을까요?

2023-01-05 10:10 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
addAutoLottoTickets 가 LottoTicket 클래스 안에 static 메소드로 선언되어야 하는 이유가 따로 있을까요? 해당 함수의 기능으로 보면 lottoTicketList에 autoCount 만큼의 lottoNumber 를 추가해주는 역할을 해주는 걸로 보이는데, LottoTicketList 클래스가 별도로 나와있는 상태에서 LottoTicket 클래스에 static 메소드로 선언을 해줄 필요가 있을까... 하는 의구심이 조금 들긴 하네요 😢

2023-01-05 10:12 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
그냥 봐서는 LottoTicketList 를 만들어주기 위해  List<LottoTicket> lottoTicketList 를 사용하는 것으로 보이는데, List<LottoTicket> lottoTicketList 를 꼭 먼저 만들고 LottoTicketList 클래스 오브젝트를 만들어줘야 하는걸까요? LottoTicketList 오브젝트를 먼저 만들고 필요한 메소드를 추가하는 방식으로도 구현할수 있을 것 같고, 다른 방식으로도 가능할 것 같은데, 위 처럼 진행하게된 이유가 있으실까요?

2023-01-07 02:51 UTC, fbgnwhife1 commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
앗 그렇네요... 하다보니 LottoTicketList를 제대로 활용을 안해버렸네요 ㅠㅠ 수정해봤습니다!
LottoTIcketList를 new LottoTicketList() 로 생성하고 이후에 티켓들을 추가해 주는 방향으로 진행하였습니다.
그리고 이전에 validation 체크를 다 줘해서 LottoTIcketList 클래스에는 따로 추가해주지는 않았는데
제가 놓친 부분이 있을까요?
리뷰 요청은 월요일에 누르도록 하겠습니다!

2023-01-09 02:31 UTC, hayden-ii commented on src/main/java/controller/LottoController.java
> +        lottoTicketList.addAll(InputView.inputManualLottoNumbers(purchaseAmount));
validate 완료 된 상태라면 추가로 또 해줄 필요는 없을 것 같습니다~ 👍

2023-01-09 02:37 UTC, hayden-ii approved these changes
수고하셨습니다~ 오버플로 케이스까지 테스트로 작성해주셨네요 👍 추가로 auto와 random 이라는 이름을 혼합해서 사용하셨는데, 자동과 무작위는 별도의 기능이라 분리해서 작성해주셨다면 더 깔끔한 코드가 될 수 있지 않았을까.. 하는 생각이 듭니다. 수동 로또 기능과 테스트 추가 잘 해주셨고, 로또 미션은 여기까지 진행하고 다음 미션으로 진행해주셔도 될 것 같습니다. 고생하셨습니다~! 😄

2023-01-09 02:37 UTC, merged