[huny.jeong] 로또 수동 - 2단계
2023newkrew/java-lotto-kakao pull request #57
Opened 2023-01-04 07:26 UTC by person003333

로또 수동으로 입력하는 것 추가 하였고
 controller에서 collection들 안 보이도록 일급객체 몇개 더 생성했습니다.

2023-01-05 03:38 UTC, teddy-ready requested changes
멘션 한 부분만 수정 주시면 머지 드릴게요~

2023-01-05 03:38 UTC, teddy-ready commented on src/main/java/lotto/controller/LottoController.java
이런 코드는 Factory 메소드 패턴을 사용하면 좋을 듯합니다. 
LottosFactory 인터페이스에 Lottos generate(int numberOfLotto); 선언하고 이를 구현한 구현체 2개 만들어서 
MaunalLottosLottosFactory.java 랑 AutoLottosFactory.java 처리하면 깔끔해 보입니다

2023-01-05 04:31 UTC, person003333 commented
Factory 메소드 패턴을 사용해서 MaunalLottosLottosFactory.java 랑 AutoLottosFactory.java로 분리 하였는데 몇가지 궁금한 점이 있습니다.

1. MaunalLottosLottosFactory의 경우 별도로 숫자를 입력받아야 해서 generate에 input 구문을 넣었는데 mvc 패턴에 위반되지 않았나 생각됩니다.  
이대로 해도 괜찮은 것인지 아니면 generate의 매개변수를 바꾸고 input 받는 부분은 controller 에서 처리해야 하는 것이 맞는 것인지 궁금합니다.

2. manualLottos와 autoLottos를 합치는 부분에서 그냥 manualLottosFactory의 joinLottos를 사용하였는데 이때 manualLottosFactory이나 autoLottosFactory 중 아무 팩토리에서 joinLottos를 호출하는 것이 맞는 건지 
아니면 별도의 매서드를 새로 만들어야 하는지 의문이 들어 질문드립니다.

2023-01-09 07:19 UTC, teddy-ready approved these changes
질문주신 부분은 아래와 같이 답변 드릴수 있을 것 같습니다 
1.MVC 에 대한 위배가 아닌가?
소스를 기준으로 본다면 factory 패키지가 mvc 중에 어떤것으로 정의하실것인지가 이슈일듯 합니다 
1) 모델로 정의한다면 
> 일단 패키지나 객체 구조 부터 모델 하위로 넣어야 할듯합니다
> 이럴경우 MVC 위배 입니다.
2) 유틸로 정의한다면
> 이럴경우 MVC 위배가 아닙니다. 유틸은 MVC 어느 레이어에서도 사용가능합니다.
> 단 비지니스 혹은 도메인 성격이 없어야하고, 인풋과 아웃품이 명확해야합니다. 

추가로 수동 로또를 위해서 generate 에 아큐먼트를 하나더 만든다면 추상화가 안되서 팩토리 메소드 패턴은 사용할 수 없으므로, 다르게 구현하시면 됩니다

2023-01-09 07:19 UTC, merged