[ jin.100 ] 로또 수동 - 2단계
2023newkrew/java-lotto-kakao pull request #58
Opened 2023-01-04 09:51 UTC by dongjinBaek

제프리 안녕하세요!

로또 2단계 코드 작성했습니다.
2단계 추가 기능은 로또 번호를 수동으로 지정해서 입력받을 수 있는 기능입니다.

이를 위해서 수동 발급 로또 개수, 자동 발급 로또 개수를  가지고 있는 `TotalLottoCount` 클래스를 새로 만들었습니다.

2023-01-05 05:02 UTC, artium59 commented on src/main/java/javalotto/view/InputView.java
> +    }
`InputView`에서 로또를 만드는 것은 `LottoGenerator`의 역할을 침범하는 것 같습니다. 한 번 분리해 보는 것이 어떠하신가요?

2023-01-05 05:12 UTC, artium59 commented on src/main/java/javalotto/controller/LottoController.java
> +    private Lottos simulateAndPrintLottoPurchase(TotalLottoCount totalLottoCount) {
이 함수는 1.로또를 생성 2.출력 2가지 일을 하는 것 같습니다. 제 생각에는 분리하는 것이 좋을 것 같은데, 어떻게 생각하시나요?

2023-01-05 05:13 UTC, artium59 commented on src/main/java/javalotto/domain/LottoCount.java
> +    private static void validateCount(int count) {
👍

2023-01-05 05:28 UTC, artium59 commented on src/main/java/javalotto/domain/Lottos.java
>      private Map<Rank, Integer> initRankCountMap() {
https://github.com/next-step/java-lotto-kakao/pull/58/files#r1062111293
이것과 동일한 내용입니다. 저는 `getLottoResults()`가 여기에 있는 것이 어색하다고 생각합니다.

2023-01-05 05:32 UTC, artium59 requested changes
진 안녕하세요~
간단하게 코멘트 남겼습니다.
질문이 있다면 편하게 해주세요.

2023-01-05 07:55 UTC, dongjinBaek commented on src/main/java/javalotto/view/InputView.java
> +    }
`InputView` 클래스의 리턴 타입이
  1. InputView 내에서 생성까지 해서 도메인 객체 반환하기
  2. primitive나 Collection of primitive 타입 반환하고 생성은 사용하는 곳에서 하기 

중에서 고민하다가 '규칙 3: 모든 원시값과 문자열을 포장한다.' 가 있어서 전자로 했었는데요, 객체 역할에 맞는 책임을 위해서 위 규칙은 도메인 객체 내에서만 적용하고 생성 책임은 적절한 곳으로 옮기도록 하겠습니다.

2023-01-05 08:10 UTC, dongjinBaek commented on src/main/java/javalotto/domain/Lottos.java
>      private Map<Rank, Integer> initRankCountMap() {
말씀해주신 내용 + 위에서 뷰에서 옮긴 객체를 생성하는 로직과 더불어서 
  1. 컨트롤러가 수동, 자동 로또들을 각각 발급하고 합치는 로직
  2. 구매 금액을 컨트롤러가 들고 있다가 맨 마지막에 수익률 계산하는 함수에 인자로 넣어주는 것

을 컨트롤러에서 해도 되나? 싶어서 담당하는 새 클래스를 만드려다 고민이 많아져서 포기했었는데, 다시 추가했습니다.

- [refactor : 로또 구매 역할을 하는 LottoBuyer 클래스 생성](https://github.com/next-step/java-lotto-kakao/pull/58/commits/7a1fae19f0d8c6eb76ca73b4bd2e119eec1ec976)
  - `LottoBuyer` 는 `PurchaseAmount`, `TotalLottoCount` 정보로 생성되고, `purchaseLottos` 메서드 호출 후에는 `Lottos` 정보도 추가됨
  - 로또 구매 (`LottoBuyer::purchaseLottos`) 책임을 `LottoController` 에서 `LottoBuyer` 로 이동
  - 구매한 로또들의 당첨결과 확인(`getLottoResult`) 책임을 `Lottos` 에서 `LottoBuyer` 로 이동
  - 수익률 계산(`getRateOfReturn`) 책임을 `LottoResult` 에서 `LottoBuyer` 로 이동
  - `LottoGenerator` 을 `LottoShop` 으로 rename 하고 수동 로또 발급해주는 `LottoShop::issueManualLottos` 메서드 추가
  - `LottoBuyer` 를 파라미터로 주고받으며 `LottoContoller::simulate` 메서드 분리 및 간소화

고민이었던 부분은 
1. `LottoBuyer` 인스턴스가 `purchaseLottoResult` 를 호출하기 전에 `getLottoResult` 나 `getRateOfReturn` 같은 메서드들을 호출하면 어떻게 하지? 구매 전에 lottos 항목이 비어있는 불완전한 `LottoBuyer` 객체가 있어도 되나?
2. 그래서 보통 이런 일들을 모아두는 `Service` 클래스를 만드는건가?

였습니다.

-----
또, 책 읽다가 `Collectors::groupingby` 에 대해서도 알게 되어서 추가적인 리팩토링도 진행해봤습니다.
- [refactor : LottoBuyer::getLottoResult 에서 등수별 로또 개수를 세는 로직을 Collectors::groupingBy를 이용하도록 변경](https://github.com/next-step/java-lotto-kakao/pull/58/commits/d6aa509ed764742ff972495fbdf1401762c524cb)

2023-01-05 08:11 UTC, dongjinBaek commented on src/main/java/javalotto/view/InputView.java
> +    }
- [refactor : InputView 클래스에서 도메인 객체 생성 역할 제거](https://github.com/next-step/java-lotto-kakao/pull/58/commits/319466f61460f0850fc8c224a6f7b026addc5961)

2023-01-08 08:04 UTC, artium59 commented on src/main/java/javalotto/domain/Lottos.java
> +        return lottos;
`Lottos.java`를 일급 컬렉션으로 알고 코드를 보고 있었는데요, 여기서 `List<Lotto> lottos`가 불변이 아니게 되네요.
아래 테스트를 통과할 수 있게 코드를 바꿔보시겠어요?

```java
class LottosTest {

    @Test
    void test() {
        Lotto lotto = Lotto.from(List.of(1,2,3,4,5,6));
        Lottos lottos = Lottos.from(List.of(lotto));

        assertThat(lottos.getLottos()).hasSize(1);

        lottos.getLottos().remove(0);
        assertThat(lottos.getLottos()).hasSize(1);
    }
}
```

2023-01-09 01:36 UTC, artium59 approved these changes

2023-01-09 01:36 UTC, merged