[ jin.100 ] 로또 자동 - 1단계
2023newkrew/java-lotto-kakao pull request #6
Opened 2023-01-03 05:42 UTC by dongjinBaek

# 로또 자동 - 1단계

제프리 안녕하세요.
로또 자동 1단계 코드입니다.

README 에 있는 기능 명세 및 제약 사항은 주어진 기능 요구사항과 입출력 예시를 보고 저희가 임의로 정한 내용이고, 이를 바탕으로 코드 작성했습니다.

매번 리뷰 감사합니다!!

2023-01-03 06:02 UTC, artium59 commented on src/main/java/javalotto/domain/LottoCount.java
> +        return new LottoCount(purchaseAmount.getPurchaseAmount() / unitPrice);
사용처를 보니 `unitPrice`에 `PurchaseAmount#PURCHASE_AMOUNT_UNIT_PRICE`가 들어가는 것 같습니다.
함수의 파라미터 2개가 `PurchaseAmount`인데 2개로 나눠 받은 이유가 있을까요?

2023-01-03 06:23 UTC, artium59 commented on src/main/java/javalotto/domain/Lotto.java
> +    }
저는 개인적으로 테스트만을 위해 함수 추가하는 것을 별로 좋아하지 않습니다.
`containsExactly()`의 경우 로또 생성할 때 오름차순으로 잘 만들어졌는지 체크하는 테스트를 위해 만드신 것 같은데요.
그냥 String으로 비교하면 되지 않을까 이런 생각이 듭니다. (Lotto의 toString()이 List의 toString()이라서요.)

2023-01-03 06:39 UTC, artium59 commented on src/main/java/javalotto/domain/Rank.java
> +    final int prize;
enum의 변수들도 private 붙여주세요.

2023-01-03 06:49 UTC, artium59 commented on src/test/java/javalotto/domain/LottoCountTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
이 테스트에만 있는 것 같은데요, 어떤 의미가 있을까요?

2023-01-03 07:00 UTC, artium59 commented on src/main/java/javalotto/domain/Lotto.java
> +    public static final int LOTTO_NUMBERS_COUNT = 6;
여기에 있는 것이 맞는 것 같긴 한데, 많은 곳에서 사용하네요. 아예 상수 클래스로 빼셔도 좋을 것 같습니다.

2023-01-03 07:05 UTC, artium59 requested changes
진 안녕하세요.
간단하게 코멘트 남겼는데요, 확인 부탁드려요.

2023-01-03 07:30 UTC, dongjinBaek commented on src/main/java/javalotto/domain/LottoCount.java
> +        return new LottoCount(purchaseAmount.getPurchaseAmount() / unitPrice);
- 처음에 발행할 로또의 개수를 결정하는 두 가지 요인이 구입 금액과 로또 1개의 가격 총 두가지라 생각해서 그 두 가지 인자를 받는 정적 팩토리 메서드로 만들었습니다.
- 구현하다보니 로또 1개 금액 정보도 PurchaseAmount 객체에서 관리하도록 구현해서, 1개의 인자만 받는 메서드로 수정했습니다.

- [refactor : LottoCount::of 에서 unitPrice 를 인자로 받는 대신 PurchaseAmount 내에 있는 상수 사용하도록 수정](https://github.com/next-step/java-lotto-kakao/pull/6/commits/525afa9421a722883a35b9f1f8a908d8cc060e37)

2023-01-03 07:32 UTC, dongjinBaek commented on src/main/java/javalotto/domain/Lotto.java
> +    }
- 넵 테스트에서 `toString` 이용하도록 수정했습니다.
- [refactor : 테스트에서만 사용하던 Lotto::containsExactly 메소드 제거](https://github.com/next-step/java-lotto-kakao/pull/6/commits/b793fe62e7d4f7591e0589e86cbb45e2b681cd0b)

2023-01-03 07:32 UTC, dongjinBaek commented on src/main/java/javalotto/domain/Rank.java
> +    final int prize;
- [refactor : enum 내 필드들 private 으로 변경](https://github.com/next-step/java-lotto-kakao/pull/6/commits/3091f8b260ff538af0299c28107768e973d0764c)

2023-01-03 07:53 UTC, dongjinBaek commented on src/test/java/javalotto/domain/LottoCountTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
- Intellij 가 생성해줘서 썼었는데... 찾아보니 테스트 인스턴스가 기본으로는 테스트 메서드 하나당 생성되는데, 클래스 내 모든 테스트 메서드에서 같은 인스턴스를 사용하도록 하는 어노테이션이라고 합니다.
- 로또를 만들면서 `@ParameterizedTest` 에서 테스트 입력값이 primitive type이 아니거나 입력값 외에 기대하는 값도 파라미터로 받고 싶을 때 `@MethodSource` 어노테이션을 이용했습니다
- 문서에서 `@MethodSource` 를 사용하는 경우 위의 `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` 또는 static 메서드로 만들어야한다고 하는데, 다른 클래스들에서는 static 으로 하고 여기에서만 둘 다 적용을 해서 어노테이션 삭제했습니다.
- https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/provider/MethodSource.html
  > Factory methods within the test class must be static unless the [PER_CLASS](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/TestInstance.Lifecycle.html#PER_CLASS) test instance lifecycle mode is used
- [fix : LottoCountTest 의 @testinstance(TestInstance.Lifecycle.PER_CLASS) 어노테이션 제거](https://github.com/next-step/java-lotto-kakao/pull/6/commits/8eb228fc269aa4e3ad67876fc5e72c6c9c679746)

2023-01-03 07:57 UTC, dongjinBaek commented on src/main/java/javalotto/domain/Lotto.java
> +    public static final int LOTTO_NUMBERS_COUNT = 6;
- 넵 여기랑 PurchaseAmount 아래 상수들도 constants 패키지 만들어서 클래스 분리했습니다.
- [refactor : static 상수들 constants 패키지 아래로 분리](https://github.com/next-step/java-lotto-kakao/pull/6/commits/8ca1f252deba455a3923ac333cfcf55f3109a253)
- 수정하면서 생긴 상수 관련해서 소소한 궁금증들인데... 제프리는 어떤 걸 선호하시는지랑 이유가 궁금합니다.
  1. xxxConstants 클래스들을 constants 패키지에 따로 모아놓기 vs 연관된 domain 객체 옆에 놓기
  2. 상수 사용할 때 static import 하기 vs (클래스명).(상수명) 으로 사용하기

2023-01-03 07:57 UTC, dongjinBaek commented
리뷰 감사합니다!!!!!!

2023-01-03 10:51 UTC, artium59 commented on src/test/java/javalotto/domain/LottoCountTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
저는 대부분 `@MethodSource`를 쓸 때 static 함수로 사용해서, 이런 조건이 있는줄은 몰랐네요.👍

2023-01-03 11:01 UTC, artium59 commented on src/main/java/javalotto/domain/Lotto.java
> +    public static final int LOTTO_NUMBERS_COUNT = 6;
1. constants 패키지에 모으는 것을 선호합니다.
2. 보통 후자를 사용하는데, 그 클래스의 상수를 많이 사용한다 싶으면 static으로 받습니다.

2023-01-04 02:17 UTC, artium59 approved these changes
제가 리뷰만 하고 승인을 안했었군요;; 고생하셨습니다.

2023-01-04 02:17 UTC, merged