[jerrie.choi] Java Lotto Step 2 PR
2023newkrew/java-lotto-kakao pull request #60
Opened 2023-01-04 12:56 UTC by CHOIJXWXN

안녕하세요 요한

이틀 연속 늦은 시간에 PR을 보냅니다 🥲
이러다가 이번에도 제 때 미션을 다 못 끝낼 수도 있을 것 같다는 생각이 드네요
2단계 미션으로 나온 로또 수동 "구현"은 많이 어렵지 않았지만 이전 리뷰를 통해 리팩토링하는 과정이 시간이 꽤 걸렸습니다.
최대한 원시타입이 없도록 감싸려고 노력해보았습니다.

개인적으로는 신경쓰였던 부분은 두 가지입니다.

1. 테스트 코드

- 출력할 메세지를 반환하는 메서드도 테스트를 해야할까요? 저번 미션 때는 했던 걸로 기억하는데 이번 미션에서는 메세지 반환 메서드가 많아서 테스트를 하지 않았습니다.

- 제대로 테스트를 하지 않은 것 같은 코드가 있습니다. 예를 들면 Lottos에 Lotto를 추가하는 addManualLotto나 addAutoLottos와 같은 메서드들은 "특정 로또"가 들어갔는지 확인하는 것이 아니라 그냥 사이즈 증가 체크 정도만 하고 있습니다. 이정도로 끝내도 되는 게 맞는지 의문이 듭니다.

2. Wrapper 클래스 사용으로 인한 equals, compare의 커스터마이징
int값을 Count나 Money, LottoNumber와 같은 객체로 사용하다보니
서로 비교할 때 equals 메서드를 오버라이드하거나 Comparator를 만들어 sort했습니다.
이런 부분을 제가 마음대로 로직을 짜서 지정해도 되는지 궁금합니다.
알고리즘 문제 풀 때는 자유롭게 썼는데, 이런 확장성과 유연성을 고려하는 프로그램을 만들려다보니 마음에 걸렸습니다.

요한이 질문하면 너무 잘 알려주셔서 제가 너무 많이 물어보고 있는지도 모르겠습니다.
이번에도 많은 코멘트 부탁드리겠습니다!

항상 감사합니다 :)

2023-01-05 02:26 UTC, leeyohan93 requested changes
피드백 잘 반영해주셨네요 👍 👍
질문 주신 부분에 대한 답변과 코멘트를 남겨 놓았으니 확인 부탁드립니다 :)
궁금한 점은 언제든지 코멘트나 DM 남겨주세요 😄

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Money.java
> +    private final int money;
Money 클래스를 만들어주셨네요! 💯 💯 
실무에서는 금액을 표현할 때 정확한 실수의 표현과 부동 소수점 방식의 오차가 발생하지 않도록 BigDecimal를 사용하곤 합니다.
참고만해주세요 :)
https://madplay.github.io/post/the-need-for-bigdecimal-in-java

Money 클래스에 대한 단위 테스트도 구현해주시면 좋을 것 같습니다 :)

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/util/validator/MoneyValidator.java
> +public class MoneyValidator {
객체 생성에 대한 검증에 대한 클래스를 분리시켜주신 이유가 있으신가요??
다른 Validator 클래스들도 동일한 코멘트입니다 :)

저는 개인적으로 검증에 대해서 별도의 클래스를 분리하는 기준이 아래와 같이 있는데, 제리도 이러한 기준을 생각해보시면 좋을 것 같아요!
1. 검증로직이 굉장히 많은 경우
2. 검증에 외부 의존성이 필요한 경우

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Count.java
> +    public final int remains;
객체 상태를 public으로 설정해두면 캡슐화 원칙을 위반하고, 객체의 변경에 신경써야합니다.
만약 타입이 List 였다면 변경되지 않았을 것을 검증할 수 있을까요?

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Count.java
> +        remains = totalCount - this.count;
zero나 remains 같은 경우는 Count 객체를 사용할 때 미리 모두 계산해두는데요!
반복되어 많이 사용되는 경우 성능에 이점이 있을 수는 있지만, 필드가 추가되고 생성자의 로직을 복잡하게 합니다!
트레이드 오프를 잘 고민해보시면 좋을 것 같아요 :)

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
> +            .boxed().map(number -> new LottoNumber(number))
LottoNumber 를 캐시하여 성능 최적화를 해주셨네요 💯 💯

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
> +    private static final Comparator<LottoNumber> LOTTO_NUMBER_COMPARATOR = Comparator.comparingInt(o -> o.number);
Comparator 대신 Comparable을 LottoNumber 가 구현하도록 하는 것은 어떨까요?

> Wrapper 클래스 사용으로 인한 equals, compare의 커스터마이징
int값을 Count나 Money, LottoNumber와 같은 객체로 사용하다보니
서로 비교할 때 equals 메서드를 오버라이드하거나 Comparator를 만들어 sort했습니다.
이런 부분을 제가 마음대로 로직을 짜서 지정해도 되는지 궁금합니다.
알고리즘 문제 풀 때는 자유롭게 썼는데, 이런 확장성과 유연성을 고려하는 프로그램을 만들려다보니 마음에 걸렸습니다.

equals와 compare의 구현은 실무에서도 순서를 보장해야하거나, 동등에 대한 비교를 해야할때 자주 사용하고는 합니다!
지금은 적절한 객체들에 잘 사용해주셨어요 💯

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/LottoGame.java
> +        WinningLottoWithBonus winningLottoWithBonus = new WinningLottoWithBonus(winningLotto, bonusNumber);
저는 개인적으로 당첨번호라는 의미가 보너스번호까지를 포함하고 있어서
WinningLotto 라는 클래스 이름을 쓰는게 더욱 적절해보이는 것 같아요 ! :)

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
> +    public static Lotto getAutoLotto() {
https://github.com/next-step/java-lotto-kakao/pull/46#discussion_r1061085048

이전에 드렸던 코멘트에 대해 한번 고민해봐주시면 좋을 것 같아요 :)

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
> +    public static Lotto getManualLotto(String input) {
정적 팩터리 메서드를 사용해주셨네요 👍 👍

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
>      }
getter를 사용하기 보다는 winningLottoWithBonus 에 메시지를 던져서 Result를 응답하도록 해보는건 어떨까요?

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
>      }
> 출력할 메세지를 반환하는 메서드도 테스트를 해야할까요? 저번 미션 때는 했던 걸로 기억하는데 이번 미션에서는 메세지 반환 메서드가 많아서 테스트를 하지 않았습니다.

도메인이 출력할 메세지를 반환하고 있다는 것이 아직 도메인이 View를 의존하고 있다는 의미로 해석될 수 있을 것 같아요!
이러한 로직들은 View로 옮기어서, View의 요구사항이 변경되었을 때 도메인 로직을 수정하지 않도록 반영해보면 좋을 것 같습니다!

2023-01-05 02:26 UTC, leeyohan93 commented on src/main/java/domain/Lottos.java
>      }
> 제대로 테스트를 하지 않은 것 같은 코드가 있습니다. 예를 들면 Lottos에 Lotto를 추가하는 addManualLotto나 addAutoLottos와 같은 메서드들은 "특정 로또"가 들어갔는지 확인하는 것이 아니라 그냥 사이즈 증가 체크 정도만 하고 있습니다. 이정도로 끝내도 되는 게 맞는지 의문이 듭니다.

일급 컬렉션을 사용할 때는 Collection의 불변성을 보장하는 것을 가이드하고 있는데요!
add와 같은 메서드를 별도로 만드는 것보다 생성자를 통해 List를 받아 불변성을 보장한체로 사용하고는 합니다!

addManualLotto()와 같은 테스트에서는 input에 String 대신 Lotto 타입으로 변경해주시면 제리가 고민하시던 부분이 해결될 수 있지 않을까요?

2023-01-05 04:41 UTC, CHOIJXWXN commented on src/main/java/domain/Money.java
> +    private final int money;
Money 클래스는 생성자, 게터, 그리고 로또 구매 가능 개수를 계산하는 getCount 메서드가 있는데
단위 테스트는 getCount 정도만 해도 적당할까요?

2023-01-05 04:44 UTC, CHOIJXWXN commented on src/main/java/util/validator/MoneyValidator.java
> +public class MoneyValidator {
Count, Money, LottoNumber 모두에게 적용되는 NumberFormat에 대한 검증은 코드 중복을 발생시키는데 이를 효과적으로 관리할 수 있는 방법이 있을까요?

2023-01-05 05:11 UTC, leeyohan93 commented on src/main/java/domain/Money.java
> +    private final int money;
게터를 제외하고 생성자도 테스트에 함께 포함시켜주셔도 좋을 것 같습니다 :)

추가적으로 인텔리제이 테스트 실행 방식 중 커버리지를 함께 측정할 수 있는 기능이 있는데요!
이 기능을 사용하면 꼼꼼한 테스트를 작성하는데 도움이 될 것 같아요 :)

[https://www.jetbrains.com/help/idea/running-test-with-coverage.html](https://www.jetbrains.com/help/idea/running-test-with-coverage.html)

2023-01-05 05:16 UTC, leeyohan93 commented on src/main/java/util/validator/MoneyValidator.java
> +public class MoneyValidator {
만약 이러한 중복이 많이 발생한다면 음수가 아닌 `양수` 를 의미하는 래핑 클래스를 만들어서 다른 곳에서 참조할 것 같아요.

하지만 로또의 경우를 생각해보면 또 아래와 같은데 굳이 `양수` 클래스가 굳이 필요할 정도로 중복이 일어나지는 않을 것 같다는 생각이 드네요! 🤔 
- LottoNumber: 1~45 사이의 숫자
- Count: 0 이상의 숫자 (Int)
- Money: 0 이상의 숫자 (BigDeciaml)

2023-01-05 09:29 UTC, CHOIJXWXN commented
코멘트 주셨던 부분 반영하려고 노력했습니다!
다만 제가 만든 LottoGenerator 부분이 제대로 만든 것인지 잘 모르겠습니다 🥲
로또 생성에 대한 테스트 코드도 마찬가지로 이정도로 마무리해도 되는 건지 확신이 서지 않아 쉽지 않네요

마지막 놀금 잘 보내세요 요한!

2023-01-05 09:29 UTC, CHOIJXWXN commented
코멘트 주셨던 부분 반영하려고 노력했습니다!
다만 제가 만든 LottoGenerator 부분이 제대로 만든 것인지 잘 모르겠습니다 🥲
로또 생성에 대한 테스트 코드도 마찬가지로 이정도로 마무리해도 되는 건지 확신이 서지 않아 쉽지 않네요

마지막 놀금 잘 보내세요 요한!

2023-01-05 09:30 UTC, CHOIJXWXN commented
코멘트 주셨던 부분 반영하려고 노력했습니다!
다만 제가 만든 LottoGenerator 부분이 제대로 만든 것인지 잘 모르겠습니다 🥲
로또 생성에 대한 테스트 코드도 마찬가지로 이정도로 마무리해도 되는 건지 확신이 서지 않아 쉽지 않네요

마지막 놀금 잘 보내세요 요한!

2023-01-09 01:12 UTC, leeyohan93 approved these changes
안녕하세요 제리~ 🙏 
주말에 이렇게 PR 보내시느라 고생하셨습니다 👍 👍 
피드백도 잘 반영해주시고 리팩토링도 많이 되었네요! 
소소한 코멘트를 남겨 놓았으니 확인 부탁드리고 이번 단계는 머지하겠습니다 :)
다음 단계도 화이팅입니다 ! 🔥

2023-01-09 01:12 UTC, leeyohan93 commented on src/main/java/domain/Lotto.java
>      }
> 제가 만든 LottoGenerator 부분이 제대로 만든 것인지 잘 모르겠습니다 🥲

LottoGenerator 를 자동, 수동 각각의 구현체를 잘 만들어주셨네요 ! 💯 💯 
LottoGenerator 를 별도로 만들어주신 만큼 로또를 생성하는 팩토리 클래스를 만들어서 사용해보는 것도 좋을 것 같아요.
팩토리 클래스를 만들게되면 Lotto 클래스가 생성에 대한 의존성을 없앨 수 있겠네요!

2023-01-09 01:12 UTC, leeyohan93 commented on src/test/java/domain/LottoTest.java
>      }
> 로또 생성에 대한 테스트 코드도 마찬가지로 이정도로 마무리해도 되는 건지 확신이 서지 않아 쉽지 않네요

로또 생성에 대한 테스트를 진행할 때는 기본적으로는 인터페이스인 LottoGenerator 를 테스트해주시는 게 좋습니다.
나중에 구현체가 바뀌더라도 테스트를 사용할 수 있기 때문이죠.

구현체에 대한 테스트도 있으면 물론 좋습니다 :)

2023-01-09 01:12 UTC, leeyohan93 commented on src/main/java/domain/Lottos.java
> +        }
AutoLottoGenerator 는 싱글톤으로 사용할 수도 있지 않을까요? :)

2023-01-09 01:12 UTC, leeyohan93 commented on src/main/java/domain/Lottos.java
> +                .forEach(lotto -> totalResult.increaseValueOfResult(winningLotto.getResult(lotto)));
foreEach 를 사용할때는 스트림은 작성하지 않아도 괜찮습니다 :)

```
lottos.forEach(lotto -> totalResult.increaseValueOfResult(winningLotto.getResult(lotto)));
```

2023-01-09 01:12 UTC, leeyohan93 commented on src/main/java/domain/Lottos.java
> +    }
https://github.com/next-step/java-lotto-kakao/pull/60#discussion_r1062049767

위 코멘트에서 질문해주셨떤 부분이 아직 해결되지는 않은 것 같아요!
Lottos를 생성할 때 생성자로 List<Lotto>를 받아 불변성을 보장하는 Collection으로 사용해보는 방법도 있을 것 같습니다 :)

2023-01-09 01:12 UTC, leeyohan93 commented on src/main/java/domain/WinningLotto.java
>      }
winningLottos 에게 메시지를 던져 응답할 수 있도록 반영해주셨네요 ! 👍 👍 
깔끔하고 좋은 것 같습니다 😄

2023-01-09 01:12 UTC, leeyohan93 commented on src/main/java/domain/Money.java
> +    }
Money 와 같은 클래스를 vo(value object) 라고 부르고는 하는데요!
저는 개인적으로 vo 에서는 외부에 대한 어떠한 의존성도 가지지 않도록 하고 있습니다.
어디에서든 재사용 될 수 있도록하고, 외부의 변경에 vo 가 영향을 받지 않게 하기 위함이에요!
한번 고민해보시면 좋을 것 같습니다 :)

2023-01-09 01:13 UTC, merged

2023-01-09 10:07 UTC, CHOIJXWXN commented
안녕하세요 요한!
이미 머지되었지만 더 리팩토링 해보았는데요,

1.
일급 컬렉션은 생성자를 통해 불변성 보장을 할 수 있다고 말씀해주셔서 Lottos를 바꿔보았습니다.
Lottos의 필드인 lottos는 건들지 않으려고 노력했습니다.
그러다보니 컨트롤러 단에서 getManualLottos 메서드를 보게 되면
수동 로또 번호를 입력받을 때
컨트롤러에서 List<T> 변수 없이 진행하려고 하니 Stream.generate()로 입력값을 반복해 받아 이를 로또로 생성하고
그렇게 생성된 로또들을 리스트로 묶어 Lottos를 만들었습니다.
이렇게 하는 건 괜찮을까요?

2.
로또팩토리 클래스를 만들었지만 사실상 이전 코드 Lotto 생성자를 그대로 복사한 것이나 다름없는데요,
팩토리 패턴의 의도가 결합성을 낮추는 데에 있다고 알고 있습니다.
이미 제 생각에는 LottoGenerator가 그 역할을 하고 있다고 생각했는데,
LottoGenerator를 클래스화하는 게 더 나은 리팩토링이었을까요?