[woogie.pyun] 로또 - step2
2023newkrew/java-lotto-kakao pull request #65
Opened 2023-01-05 01:19 UTC by pyun0825

특정 객체의 책임에 대해 생각하다보니 리펙터링 할때 고민이 많았던 것 같습니다.

수동 구매도 이미 만들어 둔 객체에 사용할 수 있는 기능이 있어 빠르게 될 거라 생각 했는데 controller에서 input과 엮어 주는 과정이 쓸 때 없이 지저분하게 나와서 고민하느라 시간이 많이 들었네요..

과제 수행하는 과정에서 생각했던 내용들을 다 따로 적어놨더니 글이 조금 길어져서 밑에 comment로 따로 달아두겠습니다!

2023-01-05 01:22 UTC, pyun0825 commented
### Step1 리펙터링
**Money 클래스**
- Budget class를 Money로 변경하고 int 대신 BigDecimal 쓰게 변경했습니다
- 모든 돈 관련 행위를 Money 객체를 통해 이뤄지게 만들었고 0 이상이어야 한다는 validation을 추가했습니다
- Money라는 돈을 의미하는 클래스로 바꾸고 나니 Buyer가 돈을 쓸 때 budget 변수에 할당된 Money 객체 내부의 값이 바뀌는 행위가 어색해 보였습니디 -> 따라서 Money를 불변 객체로 만들고 돈을 쓸 때 새로운, 감소한 값에 해댕하는 Money 객체를 새로 만들어 budget 변수에 할당하는 게 만들었습니다
- 불변 객체로 만든김에 static factory도 추가했습니다

**매직넘버**
- LottoGenerator에서 사용되는 매직넘버가 LottoNumber에 이미 상수로 선언되어 있고 LottoNumber와 관련된 숫자라 해당 상수를 public으로 변경하고 generator에서 가져와 사용하게 만들었습니다
- 상수를 이런식으로 다른 클래스에서 가져와 쓰는 것도 괜찮은지 궁금합니다

**파싱 로직**
- StringParser을 없애고 String으로 들어온 당첨 번호를 해석하는 역할을 다른 클래스에 할당 하기 위해 view는 적절하지 않은 것 같아서 WinningLotto 혹은 그 안에 LottoNumbers 클래스 중 고민을 했습니다.
- WinningLotto에서 보너스 번호와 당첨 번호 중에 겹치는 수가 있는지 validate를 해야해서 그 과정을 처리하기 위해 String을 List<Integer>로 파싱하는 과정을 WinningLotto에 추가했습니다
- 그런데 step2에서 수동 생성 위해 발급할 로또 번호 파싱 때문에 Lotto 생성자로 파싱 로직을 다시 옮겼습니다 ㅠ
- 결국엔 생성자에 파싱 과정이 추가되었는데 이게 올바른 방식인지 잘 모르겠습니다

**불필요한 클래스 제거**
- Lotto(Lottery) 클래스와 LottoNumbers 클래스가 둘 다 있는건 불필요해 보여서 LottoNumbers의 역할을 Lotto가 하도록 옮기고 LottoNumbers 클래스를 제거했습니다
- Lotteries 클래스는 막연하게 컬렉션을 감싸고 외부에서 컬렉션이 필요할 때 방어적복사를 해서 제공하면 불변성이 보장되지 않을까 해서 만든 클래스인데 다시 보니 add해주는 public 메소드가 있어 불변성이 애초에 보장되지 않는 불필요한 클래스인 것 같아 지우고 그냥 List<Lotto>를 사용했습니다
- BuyerProfit도 필요 없는 클래스여서 BuyerResult의 메소드 하나로 책임을 옮겼습니다

**보너스 번호 일치 여부**
- LottoMatch 객체 생성자에서 보너스 번호 일치 불리언 무시 처리 로직을 처리하지 않도록 WinningLotto의 getRank 메소드에 그 로직을 옮겼습니다
- 그래서 보너스 번호 검사 자체를 당첨 번호와 일치하는 번호가 5개 일 때만 하도록 만들었습니다
- 강제로 false로 바꾸는 거에서 필요하지 않을 땐 애초에 검사를 안하게 바꾼건데 크게 다른것 같지가 않아 생성자 밖으로 로직을 꺼낸 것에 의의를 두어야 하는건지 궁금합니다
- LottoMatch에서 equals 메소드를 수정해 구현할 수도 있을 것 같은데 어떤게 더 합리적인 방법일까요?

**getter 사용 지양**
- Lotto 객체에서 view에서 말고는 최대한 getter를 사용하지 않도록 하게 contains, compare 메소드를 추가했습니다

**결과 반환 메소드**
- 현재는 당첨번호를 가지고 있는 WinningLotto에 검사할 로또 리스트를 넘겨주면 결과 BuyerResult가 나오는 형식입니다
- 그런데 그 과정이 맞는지는 의문이 있습니다
- buyer 자체를 WinningLotto에 넘기거나 WinningLotto를 buyer에 넘기는 것이 더 말이 되는 것 같은데 어떤게 더 괜찮은 방법일까요?

### Step2
- Step2의 수동 구매를 구현하면서 컨트롤러에서 수동 개수와 그 수만큼의 String 입력을 받고 그걸 LottoGenerator의 수동 구매 메소드에 넘겨주게 만들면 깔끔하게 만들 수 있을 것 같습니다
- 그런데 수동으로 구매할 로또의 수를 받고나서 수동으로 구매할 번호들을 받기 전에 구매자의 구매금액으로 입력한 만큼의 수동 로또를 살 수 있는지 확인하고 안 되면 예외를 터트려야 한다고 생각을 했습니다
- 그렇게 구현을 하려다 보니 컨트롤러에 추가적인 로직이 들어가게 돼 지저분해진 것 같습니다..

2023-01-05 03:09 UTC, leeyohan93 commented
> 매직넘버
상수를 이런식으로 다른 클래스에서 가져와 쓰는 것도 괜찮은지 궁금합니다

다른 클래스의 상수를 쓰는 것은 캡슐화를 위반하지 않는다고 생각해서 저는 괜찮다고 생각해요 :)

> 파싱로직
결국엔 생성자에 파싱 과정이 추가되었는데 이게 올바른 방식인지 잘 모르겠습니다

생성자를 어떻게 사용하는 지가 정답이 없기 때문에 어려운 부분이죠 ㅠ
저는 개인적으로 `주 생성자`와 `부 생성자`의 개념을 사용하고 있는데 참고해보시면 좋을 것 같습니다 
(코틀린에서는 이것이 코드로 구현되어있죠.. ㅎㅎ)
- `주 생성자` 에서는 검증 로직과 객체 생성의 기능
- `부 생성자` 에서는 주로 객체 생성에 도움을 주는 로직(파싱)과 `주 생성자` 호출

> 보너스 번호 일치 여부
LottoMatch에서 equals 메소드를 수정해 구현할 수도 있을 것 같은데 어떤게 더 합리적인 방법일까요?

저도 이 부분에 대해서 다시 생각해보니, 매치 카운트가 5개일 때만 보너스 번호를 체크하기때문에 LottoMatch를 사용하는게 약간 애매하네요!
우선 2등이 아닌 다른 등수에서 isBonusMatch 여부를 false로 넣어주는 부분도 헷갈릴 수 있을 것 같습니다!
만약 객체지향을 꼭 반영해야한다면, LottoMatch를 인터페이스로 구현하고 각 등수에 맞는 구현체들을 만들어줄 것 같아요.
2등은 보너스번호까지 확인할 수 있도록 하는 구현체를 만드는 것이죠!

다만 이건 지금에서는 오버엔지니어링이라는 생각도 듭니다 ㅎㅎ :) 
LottoMatch 클래스를 사용하지 않고 Rank.getRank()에서 if 분기로 2등과 3등을 구별해주는 것으로 간단하게 구현하는 방법도 있을 것 같아요!

> 결과 반환 메소드
현재는 당첨번호를 가지고 있는 WinningLotto에 검사할 로또 리스트를 넘겨주면 결과 BuyerResult가 나오는 형식입니다
그런데 그 과정이 맞는지는 의문이 있습니다
buyer 자체를 WinningLotto에 넘기거나 WinningLotto를 buyer에 넘기는 것이 더 말이 되는 것 같은데 어떤게 더 괜찮은 방법일까요?

저는 WinningLotto를 buyer에 넘기는 것이 더 괜찮은 방법처럼 느껴지네요! :)

> Step2
Step2의 수동 구매를 구현하면서 컨트롤러에서 수동 개수와 그 수만큼의 String 입력을 받고 그걸 LottoGenerator의 수동 구매 메소드에 넘겨주게 만들면 깔끔하게 만들 수 있을 것 같습니다
그런데 수동으로 구매할 로또의 수를 받고나서 수동으로 구매할 번호들을 받기 전에 구매자의 구매금액으로 입력한 만큼의 수동 로또를 살 수 있는지 확인하고 안 되면 예외를 터트려야 한다고 생각을 했습니다
그렇게 구현을 하려다 보니 컨트롤러에 추가적인 로직이 들어가게 돼 지저분해진 것 같습니다..

이런 부분은 어쩔 수 없는 것 같습니다 😢 그래도 깔끔하게 잘 구현해주셨어요 👍

2023-01-05 04:34 UTC, leeyohan93 requested changes
피드백 잘 반영해주셨네요 👍 👍
질문 주신 부분에 대한 답변과 코멘트를 남겨 놓았으니 확인 부탁드립니다 :)
궁금한 점은 언제든지 코멘트나 DM 남겨주세요 😄

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/lotto/LottoMatch.java
>      public boolean equals(Object obj) {
저번 리뷰에 이 부분을 놓쳤었네요 😅 
equals를 오버라이딩할 때는 반드시 hashcode도 함께 오버라이딩 되어야합니다.
아래 링크가 도움이 되었으면 좋겠어요

https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/lotto/Lotto.java
> +        }
일급 컬렉션을 사용할 때 주로 컬렉션의 불변성을 보장하도록
numbers 를 가변리스트로 만들고 add 하는 대신, 처음 생성 시에 unmodifiableList 로 만드는건 어떨까요?

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/lotto/LottoGenerator.java
> +    }
n 이라는 변수명 대신 좀 더 구체적인 변수명을 사용하면 좋을 것 같아요!

추가적으로 몇장의 로또를 살 수 있는지에 대한 책임의 위치를 고민해보면 좋을 것 같아요!

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/lotto/LottoGenerator.java
> +    public int autoGenerateRemaining(Buyer buyer) {
로또를 굉장히 많이 구매하게되면 수 많은 로또 번호 객체들이 생성될 것 같아요!
성능을 최적화하는 방법을 고민해보셔도 좋을 것 같습니다 😄

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/lotto/LottoGenerator.java
> +        int quantity = 0;
변수는 사용하는 곳 과 가장 가까운 곳에 위치시키는 것이 좋습니다! :)
위치를 조절해보면 좋을 것 같아요!

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/buyer/Buyer.java
> +    private final List<Lotto> lotteries = new ArrayList<>();
Lotteries 클래스를 변경해주셨으니 변수명도 함께 바꿔주는건 어떨까요~?

```suggestion
    private final List<Lotto> lottos = new ArrayList<>();
```

2023-01-05 04:34 UTC, leeyohan93 commented on src/test/java/lotto/LottoGeneratorTest.java
> +public class LottoGeneratorTest {
인텔리제이 테스트 실행 방식 중 커버리지를 함께 측정할 수 있는 기능이 있는데요!
이 기능을 사용하면 꼼꼼한 테스트를 작성하는데 도움이 될 것 같아요 :)

https://www.jetbrains.com/help/idea/running-test-with-coverage.html

2023-01-05 04:34 UTC, leeyohan93 commented on src/main/java/lotto/Rank.java
> +    FIRST(new LottoMatch(6, false), 2000000000),
언더 스코어를 활용하면 숫자를 가독성 있게 나타낼 수 있습니다!

ex. FIRST(6, 2_000_000_000),

2023-01-05 08:24 UTC, pyun0825 commented on src/main/java/lotto/LottoGenerator.java
> +    public int autoGenerateRemaining(Buyer buyer) {
Integer같이 캐싱하는 방법을 사용하면 좋을 것 같네요..!

2023-01-06 01:13 UTC, pyun0825 commented
피드백 주신 내용 바탕으로 리펙토링 진행해 봤습니다!

궁금한 내용 몇가지만 아래에 적어봤습니다.

주말 잘 보내세요 요한!

---

- LottoNumber 객체들을 캐싱해두기 위해서 사용할 자료구조로 길이가 변할 일이 없고 컬렉션의 부가적인 기능들도 사용할 필요가 없어서 배열을 선택했습니다. 엄청난 차이는 없을 것 같은데 이런 상황에서는 굳이 ArrayList를 안쓰고 배열을 사용해도 괜찮을까요?
- view에는 어느 정도의 로직까지 들어가는게 적적한지가 궁금합니다! 지금까지는 사용자가 입력하는 데이터를 별도의 처리 없이 바로 컨트롤러에 넘겨주는 식으로만 하고 있는데 요한은 어떻게 생각하시는지 궁금합니다. view에서 파싱이라던가 처리하는 로직을 넣는건 별로일까요?

2023-01-09 02:10 UTC, leeyohan93 approved these changes
안녕하세요 우기~ 🙏 
주말에 이렇게 PR 보내시느라 고생하셨습니다 👍 👍 
여러 책임에 대한 고민을 많이 하신게 보여서 좋았습니다!
소소한 코멘트를 남겨 놓았으니 확인 부탁드리고 이번 단계는 머지하겠습니다 :)
다음 단계도 화이팅입니다 ! 🔥

2023-01-09 02:10 UTC, leeyohan93 commented on src/main/java/lotto/LottoNumber.java
> +    private static final LottoNumber[] NUMBERS = new LottoNumber[MAX_NUMBER + 1];
> LottoNumber 객체들을 캐싱해두기 위해서 사용할 자료구조로 길이가 변할 일이 없고 컬렉션의 부가적인 기능들도 사용할 필요가 없어서 배열을 선택했습니다. 엄청난 차이는 없을 것 같은데 이런 상황에서는 굳이 ArrayList를 안쓰고 배열을 사용해도 괜찮을까요?

물론입니다 😄 배열을 사용해도 상관 없죠
실무에서는 사실 이러한 최적화할 경우가 많지는 않지만 또 다른 최적화의 방법으로 플라이웨이트 패턴이라는 것도 있습니다!
관심 있으시면 한번 가볍게 보셔도 좋을 것 같아요 :)

https://ko.wikipedia.org/wiki/%ED%94%8C%EB%9D%BC%EC%9D%B4%EC%9B%A8%EC%9D%B4%ED%8A%B8_%ED%8C%A8%ED%84%B4

2023-01-09 02:10 UTC, leeyohan93 commented on src/main/java/view/InputView.java
>  package view;
> view에는 어느 정도의 로직까지 들어가는게 적적한지가 궁금합니다! 지금까지는 사용자가 입력하는 데이터를 별도의 처리 없이 바로 컨트롤러에 넘겨주는 식으로만 하고 있는데 요한은 어떻게 생각하시는지 궁금합니다. view에서 파싱이라던가 처리하는 로직을 넣는건 별로일까요?

저는 이야기 하신 것처럼 사용자가 입력하는 데이터를 별도의 처리 없이 바로 컨트롤러에 넘겨주는 식으로 주로 사용합니다.
실무에서도 view에 파싱하거나 처리하는 로직이 생긴다면, 도메인 모델이 바뀌었을 때 서버와 클라이언트(View)를 함께 수정해야하기 때문인데요! 

코드에서만 의존성을 관리하는 것이 아닌 R&R 부분에서도 의존성을 관리해주어야한다고 생각합니다 :)

2023-01-09 02:10 UTC, leeyohan93 commented on src/main/java/lotto/LottoGenerator.java
> +    public int autoGenerateRemaining(Buyer buyer) {
만약 자동 로또 티켓만 구매한다면 Remaining 네이밍은 오해가 생길 수도 있을 것 같아요!
저는 개인적으로 이러한 네이밍을 할때는 적절히 추상화하는 것이 좋다고 생각합니다 :)
참고만해주세요 😄

2023-01-09 02:10 UTC, leeyohan93 commented on src/main/java/lotto/Rank.java
> +                    return rank.matchCount == matchCount;
early return 을 사용해보는 것도 깔끔하고 좋을 것 같아요 :)

```java
        if (matchCount == MATCH_FIVE && isBonusMatch) {
            return SECOND;
        }
```

2023-01-09 02:10 UTC, merged