[oscar.award] 로또 미션 Step2 PR
2023newkrew/java-lotto-kakao pull request #67
Opened 2023-01-05 05:21 UTC by queueSub

안녕하세요 aiden, 
1차 리뷰에서 조언해주신 내용과 온보딩 강의에서 배운 내용을 토대로 리팩토링을 수행해보았습니다.

1차 때와 기능은 99% 동일하지만, 리팩토링을 마치고 나니 기존에 비해 클래스의 구조와 종류가 정말 많이 변했네요.
적절한 클래스 분리와 불필요한 클래스를 줄일 수 있는 능력이 정말 중요하다고 깨달은 것 같습니다.

이번 경우에는
단순 래핑만 하고 있어서 존재 이유가 없던 LottoTicket,
불필요하게 분리된 클래스였던 LottoChecker,
존재 이유가 모호했지만 리팩토링을 하며 확실히 필요없다는 것을 알게 된 LottoGame 클래스가 대표적이었던 것 같습니다.

구현에 있어서 애매한 부분들이 대부분의 경우에 잘못된 클래스 설계에서 비롯되는 것 같다고 느꼈습니다.

그리고 리뷰해주신 내용 중에 불변 객체는 명확한 개념이 잡히지 않은 것 같아서 공부하는 시간을 가져보려고 합니다.

코드 리뷰 잘 부탁드립니다!!

2023-01-05 07:26 UTC, YooInKeun requested changes
1단계 피드백 반영하시느라 고생 많으셨습니다~
몇가지 코멘트 남겼는데 확인 부탁드리고, 2단계 요구 사항 반영도 부탁드려요
감사합니다 : )

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/number/LottoNumber.java
> +    private final int MIN_LOTTO_NUMBER = 1;
`LottoNumber` 객체가 생성될 때마다 메모리를 새롭게 생성하지 않도록 `static` 도 함께 선언해주는 것은 어떨까요?

```suggestion
    private static final int MIN_LOTTO_NUMBER = 1;
```

https://djkeh.github.io/articles/Why-should-final-member-variables-be-conventionally-static-in-Java-kor/

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/number/LottoNumber.java
> +public class LottoNumber {
로또 번호에 대한 역할을 별도 클래스로 분리해주니 클래스간의 역할이 명확해지고 좋네요 👍

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/number/generator/LottoNumbersGenerator.java
> +    private List<Integer> lottoNumberPool = new ArrayList<>(
지금 상태에서는 `LottoNumbersGenerator` 객체를 생성할 때마다 `lottoNumberPool` 이 생성되지 않을까요~? 
`static final` 하게 만들어 주는 것은 어떨까요?

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/number/generator/LottoNumbersGenerator.java
> +public class LottoNumbersGenerator implements NumbersGeneratable {
`RandomNumberGenerator` 에서 클래스 이름을 변경하신 이유가 궁금합니다!

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/number/generator/NumbersGeneratable.java
> +public interface NumbersGeneratable {
역시 꼼꼼하시네요 오스카 👍

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/result/LottoResultType.java
> +                .filter((number) -> winningNumbers.getLottoNumber().contains(number))
`getter` 를 지양하고 객체에게 직접 메세지를 건네면서 풀어나가면 객체지향적으로 좋을 것 같은데 어떨까요?

ex)

```java
public static LottoResultType getLottoResult(final LottoNumbers lottoNumbers, final WinningNumbers winningNumbers) {
    int matchedNumberCount = lottoNumbers.findMatchedCount(winningNumbers);
    return getRank(matchedNumberCount, lottoNumbers.contains(winningNumbers.getBonusNumber()));
}
```

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/result/LottoResultType.java
> +    private static LottoResultType getRank(final int size, final boolean hasBonusNumber) {
조건에 따라 분기하는 것보다 조건에 해당하는 값을 `LottoResultType` 객체가 필드로 갖고 있는 형태가 좀 더 깔끔하지 않을까 싶은데 어떨까요?

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/result/LottoResults.java
> +    private final Integer LOTTO_TICKET_PRICE = 1_000;
마이너하지만 꼼꼼한 리뷰를 위해 suggestion 드립니다.. 🙇‍♂️ 

```suggestion
    private static final int LOTTO_TICKET_PRICE = 1_000;
```

2023-01-05 07:26 UTC, YooInKeun commented on src/main/java/domain/lotto/number/LottoNumber.java
> +    private int number;
`final` 로 선언해주면 좋겠네요~
```suggestion
    private final int number;
```

2023-01-05 09:45 UTC, queueSub commented
추가 기능을 push 하니 자동으로 PR에도 추가가 되어서 재요청은 리뷰해주신 내용 반영해서 다시하도록 하겠습니다!
한 주 동안 고생많으셨습니다.

2023-01-05 09:51 UTC, queueSub commented on src/main/java/domain/lotto/number/generator/LottoNumbersGenerator.java
> +    private List<Integer> lottoNumberPool = new ArrayList<>(
어차피 한 번만 생성해서 재사용할 거라고 생각을 해서 이렇게 작성을 했는데
확실하게 하려면 static final로 선언했어야 했네요. 생각이 짧았던 것 같습니다 🥲

2023-01-05 09:55 UTC, queueSub commented on src/main/java/domain/lotto/number/generator/LottoNumbersGenerator.java
> +public class LottoNumbersGenerator implements NumbersGeneratable {
단순히 RandomNumber를 생성한다기에는 1~45 범위 값을 생성을 해서 부정확한 의미가 아닐까 고민하다가 바꿔보았습니다.
더 정확히 하려면 RandomLottoNumber~가 나을 수도 있겠다고 생각은 했는데,
실제로 로또 번호를 뽑는 방법이 랜덤이니까 LottoNumbersGenerator라고 해도 랜덤의 의미가 담기지 않을까 생각했던 것 같습니다.

여전히 의미가 잘 전달이 안 된다면 변경하겠습니다!

2023-01-05 10:00 UTC, queueSub commented on src/main/java/domain/lotto/result/LottoResultType.java
> +                .filter((number) -> winningNumbers.getLottoNumber().contains(number))
LottoNumbers가 인자로 받은 숫자들 중에 포함하는 숫자들, 혹은 포함하는 숫자의 개수를 반환할 수 있도록 내부에 메서드를 작성해보겠습니다!

2023-01-05 10:07 UTC, queueSub commented on src/main/java/domain/lotto/result/LottoResultType.java
> +    private static LottoResultType getRank(final int size, final boolean hasBonusNumber) {
확실히 조건 값을 직접 가지고 있다면 더 좋겠네요! 
필드로 가지고 있도록 수정해보겠습니다.

2023-01-05 10:08 UTC, queueSub commented on src/main/java/domain/lotto/number/LottoNumber.java
> +    private int number;
final 을 빼먹지 않는 습관을 잘 들이겠습니다 🫡

2023-01-05 10:09 UTC, queueSub commented on src/main/java/domain/lotto/result/LottoResults.java
> +    private final Integer LOTTO_TICKET_PRICE = 1_000;
디테일한 부분까지 리뷰해주셔서 너무 감사합니다!
이번에 static을 많이 빼먹었네요..

2023-01-09 01:54 UTC, YooInKeun approved these changes
로또 미션 진행하시느라 고생 많으셨습니다 오스카~ 👍 
로또 미션은 이만 마무리 하도록 하겠습니다~ 🙌 
감사합니다~

2023-01-09 01:54 UTC, merged