[herbi.sf8] 로또 2단계 PR 요청
2023newkrew/java-lotto-kakao pull request #71
Opened 2023-01-05 06:01 UTC by herbi1411

안녕하세요 제이스!! 로또 2단계 과제 수행해서 PR 올립니다.
2단계 과제는 사용자가 로또 번호를 입력할 수 있도록 구조를 수정하는 것이었습니다!
수행하면서 요구사항이 변경될 때 변경되는 코드가 많아져서 클래스, 메소드 분리의 중요성을 실감한 것 같습니다.

앞서 1차PR 주신것은 내용 수정해서 수정한 내용 코멘트 달았습니다!!([링크](https://github.com/next-step/java-lotto-kakao/pull/24))

추가로 변경한 사항 정리해봤습니다.
- Lotto의 자료구조를 List -> Set으로 변경
- Money 원시값 매핑
- Prize를 enum으로 만들기
- 로또 당첨번호와 보너스볼 사이에 중복이 있는 지 확인하는 로직 추가
- 구매개수(times) 자료형 int -> Long으로 변환
- 테스트 코드를 변화된 구조에 맞게 수정

감사합니다!!

2023-01-06 14:21 UTC, maythree requested changes
고생 많으셨습니다.😁
올려주신 PR을 확인해보니 LottoService에 대하여 구조적으로 리팩토링을 한번 다시 수행해보시면 좋으실 것 같습니다.
리팩토링을 수행하시게 되면 변경이 크게 이뤄질 것 같아서, 우선은 간단히 눈에 띄는 부분들에 대해서만 코멘트를 추가적으로 남겨 놓았습니다. 혹시 코멘트 내용 중 이해가 가지 않는 부분이 있으시거나 제가 오해하고 있는 부분이 있으시다면 말씀해주세요^^

2023-01-06 14:21 UTC, maythree commented on src/main/java/service/LottoService.java
> +    private final Money money;
LottoService에서 불필요한 필드들을 너무 많이 알고 있는 것 같습니다. 너무 많은 의존성은 추후 수정시 어려움을 발생시키니 최소화하는 것이 좋습니다. 제 생각으로는 Money만 남기고 다 제거가 가능할 것 같네요.
하나를 예시로 들면 winningLottoSet은 lottoResult를 만들기 위해서 createWinningLotto에서 입력받아서 필드에 정의해놓고, 곧 바로 generateLottoResult를 호출해서 LottoResult를 만들고 이후에는 사용되지 않습니다. 굳이 필드로 관리가 되어야 할 필요가 있을까요??
그리고 서비스가 하나만 존재해야한다는 규칙은 없었던 것 같은데, 서비스를 세분화 시키는 것을 고려해보셔도 가독성이 더욱 좋아질 것 같습니다.

2023-01-06 14:21 UTC, maythree commented on src/main/java/model/WinningLottoSet.java
> +public class WinningLottoSet {
Readme에는 WinningLottoSet이 지난주 당첨 번호 정보라고 작성을 해주셨는데,
WinningLottoSet이라는 이름과 뜻이 서로 매칭이 저는 잘되지 않는 것 같은데 이렇게 정의하신 이유가 있으실까요??

2023-01-06 14:21 UTC, maythree commented on src/main/java/model/Lotto.java
> +    private static final List<Integer> possibleLottoNumberList = generatePossibleLottoNumberList();
해당 상수를 LottoConstant에 선언하시지 않고 Lotto 하위에 설정하신 이유가 따로 있으실까요?

2023-01-06 14:21 UTC, maythree commented on src/main/java/model/LottoResult.java
>  public class LottoResult {
LottoResult는 모델이라기 보다는 서비스에 가까운것 같긴하네요. 좀 더 고민해보시면 좋으실 것 같습니다.

2023-01-07 16:10 UTC, herbi1411 commented on src/main/java/service/LottoService.java
> +    private final Money money;
저는 한 서비스 클래스에서 로또 모델에 대한 모든 처리를 하려고 했는데, 가독성이 떨어진 것 같습니다. 또 말씀해주신대로 인스턴스 변수를 줄일 필요성이 있는 것 같습니다. 그래서 리팩토링을 진행하면서 최대한 인스턴스 변수를 없애려고 노력했습니다.

2023-01-07 16:11 UTC, herbi1411 commented on src/main/java/model/WinningLottoSet.java
> +public class WinningLottoSet {
원래 WinningLotto 였던 클래스 이름을 WinningLottoSet으로 변경했었습니다. 그 이유는 처음엔 당첨번호라는 의미를 가진 WinningLotto로 했는데 당첨 번호에는 6자리 로또 번호 + 보너스 볼 번호가 포함돼있으므로, 보너스 볼이 추가돼있다는 의미를 넣고 싶어서 WinningLottoSet으로 바꿨었습니다. 말씀해주신 내용의 요지가 클래스 이름에 ‘지난주 당첨번호’ 라는 의미가 없다는 부분인 것 같아서 이름을 LastWeekWinningLotto로 직역해서 바꿔봤습니다.

2023-01-07 16:11 UTC, herbi1411 commented on src/main/java/model/Lotto.java
> +    private static final List<Integer> possibleLottoNumberList = generatePossibleLottoNumberList();
possibleLottoNumberList는 Lotto 클래스에서만 사용되는 상수입니다. LottoConstant에는 여러 클래스에서 사용되는 로또의 기본 정보(자리수, 숫자 범위 등)을 담고 싶었습니다. 또 LottoConstant에 public으로 선언할 경우 예상치 못하게 List가 바뀔 수도 있어서  possibleLottoNumberList는 Lotto Class 안에 private 접근자로  선언습니다!!

2023-01-07 16:11 UTC, herbi1411 commented on src/main/java/model/LottoResult.java
>  public class LottoResult {
로또 결과를 구하는 과정은 서비스의 역할이라고 말씀하신 것으로 이해하면 될까요?? 일단 클래스를 서비스 패키지로 옮겼습니다!

2023-01-07 16:13 UTC, herbi1411 commented
말씀해주신대로 LottoService를 고치는데 집중했습니다. LottoService를 (LottoValidateService, LottoGroupGenerateService, LottoJudgeService)로 나눴습니다. 나누면서 최대한 인스턴스 변수가 없게 하려고 했는데 인스턴스 변수가 아예 없이도 구성이 가능했습니다. 다만 이러면서 메서드의 매개변수가 많아지고, 3개의 서비스 간에 모델 객체를 전달하기 위해  Controller에 많은 변수가 할당된 것 같습니다. 또 LottoJudgeService에는 실질적으로 어떠한 상태도 없고 메서드 1개만 있는 상태여서 이렇게 클래스로 빼는 것이 적절하지 않은 방법 같기도 합니다. 처음에 Service를 나누고자 할 때 어떻게 나눌지 계속 생각해봤는데, 잘 생각이 나지 않아서 컨트롤러의 run 메서드에서 기존의 LottoService의 메서드를 호출하는 흐름에 따라서 (검증 - 로또 생성 - 로또 결과 생성)의 3개 클래스로 나누었더니 이런 결과가 나왔습니다. 제 생각에는 지금 상태가 적절하지는 않은 것 같은데 의견 주시면 다시 한번 리팩토링을 진행해보겠습니다!😢 감사합니다!

2023-01-09 00:46 UTC, maythree commented on src/main/java/model/Lotto.java
> +    private static final List<Integer> possibleLottoNumberList = generatePossibleLottoNumberList();
넵 좋은 생각이신 것 같습니다👍
그래도 한가지만 좀 더 고민해주시면 좋을 것 같아 추가 코멘트 드립니다.
현재 로또 모델이 여러가지의 역할을 하고 있다고 저는 생각이 듭니다. possibleLottoNumberList가 로또를 생성하는 곳에서 로또 모델에 주입하는 형식으로 되게 된다면, 로또 모델은 로또 번호만 가지고 있을 수 있게 되어 성격이 좀 더 명확한 모델이 될 수도 있을 것 같습니다.

2023-01-09 01:32 UTC, maythree commented
> 말씀해주신대로 LottoService를 고치는데 집중했습니다. LottoService를 (LottoValidateService, LottoGroupGenerateService, LottoJudgeService)로 나눴습니다. 나누면서 최대한 인스턴스 변수가 없게 하려고 했는데 인스턴스 변수가 아예 없이도 구성이 가능했습니다. 다만 이러면서 메서드의 매개변수가 많아지고, 3개의 서비스 간에 모델 객체를 전달하기 위해 Controller에 많은 변수가 할당된 것 같습니다. 또 LottoJudgeService에는 실질적으로 어떠한 상태도 없고 메서드 1개만 있는 상태여서 이렇게 클래스로 빼는 것이 적절하지 않은 방법 같기도 합니다. 처음에 Service를 나누고자 할 때 어떻게 나눌지 계속 생각해봤는데, 잘 생각이 나지 않아서 컨트롤러의 run 메서드에서 기존의 LottoService의 메서드를 호출하는 흐름에 따라서 (검증 - 로또 생성 - 로또 결과 생성)의 3개 클래스로 나누었더니 이런 결과가 나왔습니다. 제 생각에는 지금 상태가 적절하지는 않은 것 같은데 의견 주시면 다시 한번 리팩토링을 진행해보겠습니다!😢 감사합니다!

모델과 서비스의 경계가 뚜렷하지 않고 서비스의 분리가 잘못되어 이와 같은 고민이 생기시는 것 같다고 생각이 드네요.
몇가지 예시를 드리면 LastWeekWinningLotto의 경우, 모델이 아닌 로또 번호와 보너스 번호를 가지고 점수를 확인해주는 서비스로 생각이 듭니다. 그리고 LottoJudgeService의 경우도 인스턴스를 생성하는 것 외에는 역할이 없어 서비스로 분리가 아닌 모델 생성자에서 처리가 가능할 것 같습니다.
그리고 Controller에 많은 변수가 할당되어 고민이시라면, Facade Pattern에 대해 학습해보시면 해당 고민을 해결하시는데 도움이 되실 것 같습니다.

2023-01-09 17:07 UTC, herbi1411 commented
안녕하세요. 말씀해주신대로 Service 부분의 재구조화를 진행해봤는데요. 어떻게 구성해야할지 계속 고민해봤는데 모델과 서비스의 적절한 역할 분담이 이루어지게 구조화가 잘 안되네요..ㅠㅠ 사실 오히려 더 산으로 간 느낌입니다. 그래도 변경 사항을 일단 정리해봤습니다!

퍼사드패턴 말씀해주셔서 새로 조금 알아보게 됐습니다. 감사합니다. 제가 보기로 퍼사드 패턴은 하위클래스들이 독립적인 작업을 할 때 상위 클래스에서 단지 하위클래스 패턴의 메서드 호출로 명령을 실행시켜서 구조를 더 간단히 할 수 있다는 장점이 있는 것 같습니다. 그런데 제 프로젝트 구조에서는 하위클래스들이 Service 들과 Service의 작업 결과물로 나오는 Model들이라 생각이 드는데 다 상호 연관성이 있어서 퍼사드 패턴을 적용해도 각 하위 클래스 결과물들을 Controller에서 받았다가 다른 Service로 전달을 해줘야 해서 변수의 개수는 변함이 없을 것 같아서 적용하지 않았습니다. (퍼사드 패턴을 적용했을 때 Controller의 하위클래스가 Service 클래스들이라 보는게 맞다면 어차피 이미 퍼사드 패턴이 적용된 것일 지도 모르겠네요.)

변경된 부분

- LastWeekWinningLotto → LottoRankService로 변경
    - 생성자 인자로 LottoGroup, Lotto, bonusNumber
    - calculateScores 메서드를 통해 생성자 인자들로 상금 정보 리스트를 반환
- Lotto에 contains, matchNumber 메서드 추가
    - contains를 통해 Lotto의 인스턴스 변수인 LottoNumber 집합을 꺼내지 않고 로또 번호의 포함 여부를 알 수 있다.
    - matchNumber를 통해 LottoNumber 집합을 꺼내지 않고, 두 로또의 겹치는 숫자 갯수를 Model 단에서 구해준다.
- LottoResult → LottoResultService 이름 변경
    - `Map<LottoPrize, Long>` 인스턴스 변수 초기화에 너무 많은 코드가 있어서 `LottoPrizeMap` 모델을 새로 생성해서 로직을 분리
- LottoResultDto 생성
    - OutputView에서 LottoResultService가 가지고있는 LottoPrizeMap, earningRate를 출력해야할 필요가 있는데, View로 Service를 전달하는 것은 어색한 것 같아서 Dto 추가
- LottoScore 삭제
    - LottoRankService에서 LottoPrize를 구하기 전에 중간 단계로 매치 숫자 개수와 보너스볼 일치 여부를 저장하는 역할을 했었는데,  `LottoPrize.valueOf`로 바로 LottoPrize를 구하게 수정했기 때문에 제거
- LottoJudgeService 삭제
    - 관련 로직은 LottoResultService로 이동

의문점

- LottoRankService의 메서드가 유일하게 calculateScores 하나여서 이전과 마찬가지로 인스턴스를 생성할 필요가 없이 단지 메서드 하나로만 역할을 할 수 있을 것 같습니다. 하지만 이 로직을 다른 서비스와 합치자니 합쳐지는 클래스의 인스턴스 변수가 많아지고 역할이 모호해질 것 같아서 어떤 방법이 좋을 지 궁금합니다.. 모델로 보내는 방법을 생각해봤는데 그러면 다시 LastWeekWinningLotto였던 상태랑 똑같아질 것 같습니다.
- LottoResultService 또한 LottoRankService에서 만들어진 PrizeList를 받아서 PrizeMap을 만들고, 수익률을 구하는 역할을 하고 있는데, 메서드가 DTO를 만들어주는 것 1개밖에 없는 상황입니다.. DTO를 만든 이유는 위의 설명과 같이 OutputView에서 LottoResult를 출력을 해야하는데 View로 Service 객체를 보내는 것은 이상한 것 같아서 DTO로 변환한 다음에 옮겼습니다.

2023-01-10 16:36 UTC, herbi1411 commented
안녕하세요!! 오늘 다시 Service 부분 수정을 진행해봤습니다.  말씀해주신대로 Service를 1개로 다시 줄여봤고 Service에서 모델을 인스턴스 변수로 갖지 않도록 작성했습니다! 오늘 직접 피드백을 주셔서 방향을 다시 잡은 것 같습니다.  감사합니다!!   

`변경 내용`

- 삭제
    - LottoGroupGenerateService
    - LottoRankService
    - LottoResultService
    - LottoValidateService
    - LottoResultDto
- 생성
    - LottoService
- 수정
    - Money모델을 통해 remainedMoney 변수를 생성해서 로또 생성 개수 관리
        - 말씀해 주신대로 로또를 생성할때 돈을 줄여나가면서 로또를 구매하는 식으로 구성해봤습니다! 이렇게하니까 로또를 몇개 사야할 지 계산하는 로직이 확실히 개선된 것 같습니다.
    - Money모델 getter 제거
        - Money만큼은 getter를 안써보고 싶어서 getter를 없애고 메시지를 전달하는(?)방법을 사용해봤습니다.
        - 로또 구매개수를 구할 때, 수익률을 계산할 때 Long 값을 가져와서 나눗셈을 할 필요가 있었는데, 나누기를 해달라고 메시지를 보내서 처리했습니다. 다만 메서드 이름이 dividedByResult, divideResult 이렇게 나왔는데 직관적이지 못하고 뜻이 모호한 것 같습니다. 더 좋은 이름이 생각나지 않아서, 위 이름대로 작성했습니다.
    - (문자열, 구분자) 로 Lotto 생성하는 생성자 제거
        - 문자열을 받으면 구분자로 나눠서 Lotto를 생성하는 것은 Service에서 해야하는 것 아닐까하는 생각이 들어서 생성자를 제거하고 Service에서 문자열을 입력받으면 Lotto를 만들어주도록 변경했습니다!
    - Service에서 수익률(earningRates) 구하기
        - LottoPrizeMap에 earningRates를 저장하고 outputView에서 getter로 꺼내서 출력하는 방법대로 하려고 했는데, Controller에서 Service의 메서드를 호출해 earningRates를 구하고, 이를 Outputview로 전달하는 것이 더 나을 것 같아서 Service에 earningRates를 구하는 메서드를 추가했습니다!! Service에서는 LottoPrizeMap의 getTotalPrize를 호출한 후, 처음에 구입한 총액을 통해 수익률을 반환해줍니다.
    - 수동 로또 입력 + 자동 생성 로또 입력을 LottoGroup으로 각각 만든 다음 addAll로 합치기
        - 기존에는 수동 로또 리스트를 만들고, 자동 생성 로또를 만들 개수와 함께 LottoGroup의 생성자로 입력하면 전체 로또그룹을 만드는 방식이었습니다.
        - 이를 수동 로또와 자동 로또 각각 로또그룹을 만들고 addAll 메서드를 만들어 합치는 구조로 변경했습니다.
        - 그 결과 LottoGroup에서 (자동 로또 생성 개수, 수동 로또 리스트) 를 통해 로또 그룹을 생성하는 생성자가 안쓰이게 돼서 제거했습니다.

2023-01-11 00:39 UTC, maythree approved these changes
고생 많으셨습니다😁
코드가 처음보다는 확실히 더욱 가독성이 좋아지고 분리가 잘된 것 같네요. 다음 과제를 원활히 진행하기 위해서 2단계는 여기서 마무리 짓도록 하겠습니다. 과제 진행과는 별도로 2단계 과제는 시간나실때 개인적으로 구조나 설계에 대해서 좀 더 고민해보시고 발전시켜나가보시면 좋으실 것 같습니다.

2023-01-11 00:55 UTC, maythree commented
마지막으로 몇가지 더 코멘트를 드리자면,
이번 과제를 진행하시면서 아쉬웠던 부분은 단일 책임 원칙과 개방 폐쇄 원칙을 인지는 하고 계시지만 코드 작성시에 놓쳐지는 부분이 많으셨던 것 같습니다. 원칙 자체는 간단하지만 코드를 작성하다보면 타협하게 되고 지켜지기가 어렵기는 합니다. 그래도 계속 인지하면서 **완벽히는 아니더라도 최대한 지킬 수 있도록 노력하시는 습관**을 길러가보시면 더욱 좋으실 것 같습니다.👏

> 수정
Money모델을 통해 remainedMoney 변수를 생성해서 로또 생성 개수 관리
말씀해 주신대로 로또를 생성할때 돈을 줄여나가면서 로또를 구매하는 식으로 구성해봤습니다! 이렇게하니까 로또를 몇개 사야할 지 계산하는 로직이 확실히 개선된 것 같습니다.
...

그리고 제가 리뷰를 드리고 수정 후에 위와 같이 수정하신 내용에 대해서 일괄적으로 모아서 코멘트로 공유해주시는 것도 좋으시지만, 
이렇게 추가적으로 많은 내용이 커밋 메세지 이외로 공유되어야 할 필요가 있다면, 한 **커밋의 크기가 크지는 않나 고민**을 해보시면 좋으실 것 같고,
커밋의 크기는 크지 않지만 추가적으로 설명이나 논의가 필요한 부분이 있다면 설명 및 논의가 필요한 코드의 위치에 코멘트를 나눠서 달아주시면 동료들이 리뷰하는데 더욱 이해하기가 쉬워질 것 같습니다.😁

2023-01-11 00:56 UTC, merged