[gray.ts] 로또 2단계
2023newkrew/java-lotto-kakao pull request #72
Opened 2023-01-05 06:02 UTC by abcworld123

에디 안녕하세요 그레이입니다.
저번 1단계 코드리뷰 반영 및 수동 로또 입력 기능 추가 구현하였습니다.

구현 중 궁금한 점이 생겨 여쭤봅니다.
`LottoView` 클래스 내에 `inputLottoNumber`라는 메소드를 구현하였습니다. 이 메소드는 `1, 2, 3, 4, 5, 6`과 같은 한 줄을 입력받아 스플릿하고 `Lotto` 인스턴스를 만들어주는 역할을 수행합니다.
근데 이 메소드에서 `Lotto` 인스턴스를 만드는 기능 같은 부분이 view 안에 있어도 되는지 의문이 듭니다.
이 경우가 아니더라도 비슷한 상황이 자주 발생할 것 같아 비슷한 역할의 메소드를 통틀어서 질문드리겠습니다.

1. 이런 메소드는 별도의 클래스(제너레이터 또는 서비스 쪽)에 구현해야 하는지
2. 만약 그렇다면 이 메소드를 스태틱으로 구현해야 하는지, 아니면 그렇지 않은지
3. 만약 스태틱으로 구현하지 말아야 한다면, 제너레이터 또는 서비스 인스턴스를 뷰 내에서 생성해야 하는지, 아니면 메인에서 인자로 넘겨줘야 하는지 궁금합니다.

항상 꼼꼼한 리뷰 감사합니다 :)

2023-01-05 11:53 UTC, eddy-oum requested changes
안녕하세요 그레이.

1차 코드리뷰 때 리뷰드렸던 외부 config로의 분리 등을 잘 수행해주셨습니다.

이번엔 LottoRank와, LottoResult가 나눠가진 승자 결정로직을 합치고,
main이 갖고 있는 로직을 적절히 나눠주는 것을 중점적으로 리뷰를 드렸어요.

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/domain/Lottos.java
> +    }
로또 클래스에서 정의한 add를 잘 활용해주셨네요.

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/view/LottoView.java
> +        List<LottoRank> rankList = List.of(LottoRank.FIFTH, LottoRank.FOURTH, LottoRank.THIRD, LottoRank.SECOND, LottoRank.FIRST);
LottoRank.values()를 활용하면 좋을 것 같습니다.

2023-01-05 11:53 UTC, eddy-oum commented on src/test/java/lotto/LottoResultTest.java
> +        );
nit : Lotto는 순서와 무관하다는 내용의 테스트가 추가되면 좋을 것 같아요.

2023-01-05 11:53 UTC, eddy-oum commented on src/test/java/lotto/LottoResultTest.java
> +        assertThat(stat.getProfitRate()).isCloseTo(profitRate, within(0.0001));
👍

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/domain/LottoResult.java
> +        if(LottoRank.FIFTH.COUNT == myLotto.getMatchCount(winningLotto))
getMatchCount는 한번만 계산되어도 좋을 것 같다는 생각이 듭니다.

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/domain/Lotto.java
> +        return matchedSet.size();
Lotto의 결과는 맞춘 갯수와, 보너스번호의 여부로 결정되는데요, 지금은 MyLotto로부터 결과를 알려면
public int getMatchCount(Lotto other)과 public boolean hasBonus(LottoNumber other) 를 합쳐야합니다.

1) 결과를 담는 하나의 dto가 나오면 좋을 것 같아요.
```java
public class Result() {
     private final Integer matchCount;
     private final Boolean matchedBonus;
}
```

2) 당첨 로또는 Lotto + 보너스 LottoNumber로 구성이 되는데요, 이 자체를 별도의 클래스 혹은, Lotto를 상속받은 WinningLotto로 구현하는 것은 어떨까요?

그리고 Lotto, WinningLotto, Result를 코디네이션하는 역할을 LottoService에서 맡으면 어떨까싶은데요, 그레이 생각은 어떠신가요?

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/domain/LottoRank.java
>      }
LottoRank와 LottoConfig의 연관관계가 명확하게 드러나면 좋을 것 같습니다.

FIRST의 COUNT가 6인 것은 LottoConfig의 LOTTO_SIZE와 연관이 있고, 지금은 고정값인 prize도 사실은 LottoConfig의 MIN, MAX, SIZE와 기타 요소에 의해 계산되어야 하는 값이라고 생각해요.

LottoConfig의 LOTTO_SIZE위에 ```// 이 값을 바꿀 땐 LottoRank 클래스도 같이 보세요```라는 주석을 달거나,
LottoConfig를 바꾸면 LottoRank도 바꿀 수밖에 없게 테스트 어딘가에 ```assertTrue(LottoRank.FIRST.COUNT == LottoConfig.LOTTO_SIZE)``` 를 추가할 수도 있겠죠.

더 좋은 방법은, 승자 결정로직을 오직 한 곳에 두는 것이라고 생각합니다.
enum에 로직을 부여하여 LottoRank에 두어도 좋고, LottoRank는 FIRST, SECOND, THIRD만 있고, LottoResult에서
```java
if (getmatchCount ==  Config.SIZE - 1) {
    return LottoRank.SECOND
}
```
같은 방식을 취할 수도 있을 것 같아요.

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/domain/LottoResult.java
>              return LottoRank.SECOND;
LottoRank의 내부상태인 COUNT와, 2등, 3등을 고를 때 LottoRank와는 관계없는 bonus를 같이 고려해야한다는 것은
한 곳에 있어야할 LottoRank 결정 로직이 LottoRank와 LottoResult 간에 나뉘어져있는 것이라는 생각이 들어요.

LottoRank에 의하면 FIRST의 COUNT는 6이지만, LottoResult에서
```java
if (LottoRank.FIRST.COUNT == myLotto.compare(winningLotto)) {
    return LottoRank.SECOND;
}
``` 
를 하는 것을 LottoRank 클래스가 막을 방법이 없습니다.

LottoRank에도 남긴, _승자 결정로직을 오직 한 곳에 두는 것_을 고려해보시면 좋을 것 같아요.

2023-01-05 11:53 UTC, eddy-oum commented on src/main/java/lotto/App.java
>          lottoView.printTotalProfitRate(stat);
메인에서 하는 역할이 조금 많은 것 같습니다.

main은 view, LottoService(혹은 비슷한 것), stats 를 코디네이션하고,
Lotto number를 코디네이션하는 것은 LottoService가 해주면 어떨까하는 생각이 들어요.

2023-01-05 12:26 UTC, eddy-oum commented
> 구현 중 궁금한 점이 생겨 여쭤봅니다. `LottoView` 클래스 내에 `inputLottoNumber`라는 메소드를 구현하였습니다. 이 메소드는 `1, 2, 3, 4, 5, 6`과 같은 한 줄을 입력받아 스플릿하고 `Lotto` 인스턴스를 만들어주는 역할을 수행합니다. 근데 이 메소드에서 `Lotto` 인스턴스를 만드는 기능 같은 부분이 view 안에 있어도 되는지 의문이 듭니다. 이 경우가 아니더라도 비슷한 상황이 자주 발생할 것 같아 비슷한 역할의 메소드를 통틀어서 질문드리겠습니다.
> 
>     1. 이런 메소드는 별도의 클래스(제너레이터 또는 서비스 쪽)에 구현해야 하는지
> 
>     2. 만약 그렇다면 이 메소드를 스태틱으로 구현해야 하는지, 아니면 그렇지 않은지
> 
>     3. 만약 스태틱으로 구현하지 말아야 한다면, 제너레이터 또는 서비스 인스턴스를 뷰 내에서 생성해야 하는지, 아니면 메인에서 인자로 넘겨줘야 하는지 궁금합니다.

0. View안에서 Lotto를 만들어줘도 될까?
    만들어주지 않는 편이 좋다고 생각이 됩니다. 그런데 왜 만들어주지 않는 편이 좋다고 생각했을까요?
    아마 그레이도 비슷한 이유로 거부감 혹은 의문을 느끼셨을텐데요, 가장 큰 이유는 View가 외부와 맞닿아있는 클래스이기 때문입니다.
    View가 Lotto 도메인을 생성하는 방법까지 알게되면, View와 Lotto 사이에는 tight coupling이 생기게됩니다.
    View의 변화가 Lotto에 영향을 미치거나, Lotto의 변화가 View에 영향을 미치게됩니다.
    
    Lotto를 db에 저장하기로 결정해서, Lotto 클래스가 생성자로 구매자의 id도 같이 받는다고 가정해볼게요
    사용자에게서 로또 넘버를 받는 inputLottoNumber()를 변경해줘야합니다. 숫자를 받는다는 요구사항은 변경되지 않았음에도요.
    inputLottoNumber()가 Lotto 대신 ```List<Integer>```를 잘 반환했다면, View에 id를 받는 기능만 추가하고(이건 필요한 변경이죠)
    로또를 생성하는 곳에서 다른 생성자를 쓰도록(이 또한 필요한 변경이죠)만 변경해주면 됩니다.

1. 이런 메소드라고 표현해주신 것을, 외부에서 넘어온 dto를 도메인 객체로 바꿔주는 메소드라고 할게요. 취향문제지만, 저는 제너레이터라고 표현해주신 맵퍼, 컨버터같은 것을 써서 컨버팅은 서비스쪽에서 하되, 컨버팅 로직 자체는 서비스 밖에 두는 것을 선호합니다.
    
    a. 서비스쪽에서 변환하는 이유: 서비스레이어 밖에서는 도메인 객체에 대해서는 모를 수 있게 한다.
    b. 컨버팅 로직은 서비스밖으로 두는 이유: 서비스 레이어는 도메인 객체의 상호작용에 집중하고, 외부의 dto가 어떻게 엔티티와 연관되는 지는 모른다.
    
    그러나, 소규모 프로젝트에서는 서비스레이어에서 변환을 수행하기도 합니다.

3. 이건 취향이라고 생각합니다, 싱글톤 컨버터를 만들어 메소드를 써도 되고, 컨버터의 스태틱메소드를 사용해도 되고요. 

4. 1번에서 살짝 답변드린 것 같은데요, 메인에서 제너레이터를 만들어 서비스레이어에 주입해주면 좋을 것 같아요. 뷰 내에서 하게되면, 뷰는 convert(dto, domain)를 하면서 dto와 entity 양쪽에 대해서 알아야합니다. 뷰는 domain 대해서 최대한 모를 수록 좋다고 생각해요.

2023-01-05 13:04 UTC, abcworld123 commented on src/main/java/lotto/domain/Lotto.java
> +        return matchedSet.size();
맞습니다. 말씀해주신 방법이 훨씬 깔끔하고 좋아보입니다. 아직도 클래스를 제대로 활용하지 못하고 있는 것 같아요 😥

2023-01-05 13:21 UTC, abcworld123 commented
상세한 답변 정말 감사합니다..!!

2023-02-02 09:01 UTC, abcworld123 commented
로또 2단계가 남은 걸 까먹고 있었네요.. 리뷰 요청 드립니다!
이번에도 진행하며 궁금한 점이 생겼습니다.

1. 저번과 비슷한 질문인 것 같은데.. 서비스 안에 뷰가 있어도 되는걸까요? 메인의 줄이 길어서 서비스로 옮기려 했는데, 뷰를 같이 옮겨야 할 것 같은 상황이 생기는 것 같습니다.
2. 자바에서는 보통 두 개 이상의 변수를 리턴해야 할 경우 어떻게 처리하나요? 가끔은 리턴값이 한 곳밖에 안 쓰여서 뭔가 dto까지 만들기는 좀 애매한 경우가 종종 생기는데 이런 경우 좋은 방법 있을지 궁금합니다.

기타 모든 조언 감사히 받겠습니다.

2023-02-03 07:05 UTC, eddy-oum commented
> 로또 2단계가 남은 걸 까먹고 있었네요.. 리뷰 요청 드립니다! 이번에도 진행하며 궁금한 점이 생겼습니다.
> 
>     1. 저번과 비슷한 질문인 것 같은데.. 서비스 안에 뷰가 있어도 되는걸까요? 메인의 줄이 길어서 서비스로 옮기려 했는데, 뷰를 같이 옮겨야 할 것 같은 상황이 생기는 것 같습니다.
> 
>     2. 자바에서는 보통 두 개 이상의 변수를 리턴해야 할 경우 어떻게 처리하나요? 가끔은 리턴값이 한 곳밖에 안 쓰여서 뭔가 dto까지 만들기는 좀 애매한 경우가 종종 생기는데 이런 경우 좋은 방법 있을지 궁금합니다.
> 
> 
> 기타 모든 조언 감사히 받겠습니다.

1. 아니용. 서비스 로직은 뷰에 대해서 몰라야 합니다.

2. 네 자바에는 아쉽게도 tuple이나 multiple return이 없죠 ㅠㅠ. 한 곳밖에 안쓰이지만 꼭 의미부여를 해야한다면 dto를 만드는 것이 좋겠습니다.
자바 14부터는 레코드(https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/Record.html) 생겨서 조금 수월합니다.

2023-02-03 07:08 UTC, eddy-oum approved these changes

2023-02-03 07:08 UTC, merged