[Marcus.min] 로또 게임 Step2 PR 요청 드립니다.
2023newkrew/java-lotto-kakao pull request #74
Opened 2023-01-05 06:13 UTC by ekzm8523

안녕하세요 로또 2단계 PR 입니다.

2단계 설명 페이지 링크 함께 올릴게요!
https://edu.nextstep.camp/s/GiKTqpMP/ls/OUW7bXsx

### 특이 사항
- 수익률을 계산하는 부분에서 상금이 21억이 넘어가면 Int overflow가 발생하기 때문에 Long 으로 변경해주었습니다.
- 맞은 로또의 갯수와 보너스 포함 여부를 던지면 몇등인지를 return하는 LottoGradeEnum.evaluate() 메서드에 2등을 판별하는 로직에 버그가 있어서 수정하였습니다.

### 고민되는 부분

- Application과  View의 상호작용이 유연하진 않아보입니다.
  - View에서 수동로또는 몇 개인지, 자동 로또는 몇 개인지 출력을 하기 위해서 private 변수로 저장을 하게 되는 부분도 좀 더 우아하게 구성해보고 싶은데 조금 더 고민이 필요해 보입니다.
  - Application에서 generateLotto를 하는 부분에 약간의 로직이 들어가는 부분에 로직이 아닌 요청을 하는 방식으로 변경되도록 고민이 필요해 보입니다.

2023-01-05 08:34 UTC, wade-lim requested changes
고생하셨습니다~

Application 쪽 코멘트는 그대로 수정하면 수정 분량이 조금 많을거 같은데 필요하다고 판단되시면 선택적으로 진행해주시면 좋을거 같습니다 :)

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/LottoGradeEnum.java
>      }
[의견]
enum 필드 쪽에 needBonusMatch 필드를 추가하면 어떨까요?

조건에 해당되는게 여러개일 때 묵시적으로 더 높은 grade 를 선택하는게 이슈가 될 수도 있긴 하지만 grade 선택을 아래처럼 할 수 있고, 데이터 자체에서 어떤 조건에서 해당 grade 가 선택되는지 바로 표현되기 때문에 좀 더 명확할거 같아요~ 

```java
Arrays.stream(LottoGradeEnum.values())
  .filter(grade -> grade.matchCount == matchCount)
  .filter(grade -> !grade.needBonusMatch || isMatchBonus)
  .findFirst()
  .orElse(NONE_GRADE);
```

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/domain/LottoGradeCounter.java
> +                .mapToLong(entry -> (long) entry.getKey().getPrice() * entry.getValue())
금액이 커서 overflow 발생할 수도 있나보군요 :)

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/domain/LottoNumber.java
>      }
[질문]
혹시 요렇게 따로 캐시된 `LottoNumber` 객체를 반환하는 이유가 있을까요?

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/domain/WinningLotto.java
> +        return LottoGradeEnum.evaluate(matchCount, lotto.getNumbers().contains(bonusNumber));
요런 버그가 있었군요 😰

2023-01-05 08:34 UTC, wade-lim commented on src/test/java/lotto/domain/LottoTest.java
> +                .hasMessage(INVALID_LOTTO_SIZE);
[의견]
에러 메시지까지 테스트 할 필요가 있을까 싶긴 하네요 😅

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/view/LottoView.java
> +    private int manualLottoCount;
[의견]
요 필드를 View 쪽에서 직접 가지고 있어야 하는 이유가 있을까요?
`Scanner` 도 일종의 state 이지만, 더 이상 state 가 늘어날 필요는 없을거 같아서요~

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/view/LottoView.java
>      public LottoView() {
[의견]
클래스가 전체적으로 View, Model, Controller 기능이 모두 섞여있는 것 같네요~

2023-01-05 08:34 UTC, wade-lim commented on src/main/java/lotto/Application.java
> +        );
[의견]
현금, 현재 가진 티켓 리스트를 필드로 가진 `Customer` 와 티켓을 발행해주는 `LottoStore` or `LottoGenerator` 컨트롤러 클래스를 만들면 계산 로직을 분리할 수 있지 않을까요?

또한 `LottoView` 쪽에서 `receiveManualLottoCount` 와 같이 직접 계산하는 로직을 컨트롤러 쪽으로 분리할 수도 있을거 같아요.

2023-01-05 08:38 UTC, ekzm8523 commented on src/main/java/lotto/Application.java
> +        );
금액을 받고 로또를 발급해주는 컨트롤러를 하나 추가해야겠네요 :)
좋은 의견인 것 같아요!! 반영해볼게요 👍

2023-01-05 08:39 UTC, ekzm8523 commented on src/main/java/lotto/view/LottoView.java
> +    private int manualLottoCount;
저도 그 부분이 가장 고민이였는데 Store 객체를 하나 만들면 해결될 것 같네요!

2023-01-05 08:40 UTC, ekzm8523 commented on src/main/java/lotto/domain/LottoNumber.java
>      }
바깥에서도 전부 LottoNumber 객체로 핸들링하도록 통일하기 위해서입니다!

2023-01-05 08:46 UTC, ekzm8523 commented on src/main/java/lotto/LottoGradeEnum.java
>      }
기가 막힌데요? 바로 적용하겠습니다~

2023-01-05 08:54 UTC, wade-lim commented on src/main/java/lotto/domain/LottoNumber.java
>      }
요 메소드는 없어도 괜찮지 않을까요? 사실상 `this` 와 다를게 없어보이고, 테스트 외에는 사용되는 곳이 없어서요~
int 필드를 숨겼다는 것은 외부 관점에서는 숫자 자체보다 객체의 equality 에만 신경을 쓰겠다는 목적인 것 같아서 테스트에서도 아래처럼 equality 만 체크해주면 되지 않을까 싶네요.

2023-01-08 11:12 UTC, ekzm8523 commented
@wade-lim 리뷰해주신 부분 최대한 반영해보았습니다!

- LottoController 클래스 추가
- Ticket 클래스 추가
- Customer 클래스 추가

Model 구조
- LottoGame
  - Customer
    - Ticket
    - ManualLottos
      - List[Lotto]
    - AutoLottos 
      - List[Lotto]
  - WinningLotto
    - List[Lotto]
    - BonusNumber
Customer는

2023-01-09 02:14 UTC, wade-lim approved these changes
고생하셨습니다~

코멘트 드린 부분 잘 반영해주셔서 추가적으로 코멘트 드릴게 없네요 :)

2023-01-09 02:14 UTC, wade-lim commented on src/main/java/lotto/domain/Tickets.java
> +public class Tickets {
[의견]
살 수 있는 티켓 수를 의미하는 이름이면 좋을 것 같아요!
혹은, 수량이 아닌 현금을 저장하도록 해서 `Cash` 와 같이 네이밍해도 괜찮을거 같습니다.

2023-01-09 02:14 UTC, merged