[anthony.yup] 로또 2차 PR 입니다
2023newkrew/java-lotto-kakao pull request #78
Opened 2023-01-05 06:35 UTC by Sangyups

WIP

2023-01-09 06:00 UTC, wotjd243 requested changes
전체적인 설계와 깔끔한 코드 구현이 좋았습니다. 👍 
조금 더 고민해 보면 좋을 것 같은 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.
아래의 글이 도움 되면 좋겠어요.

- https://stackoverflow.com/questions/7026507/why-are-static-variables-considered-evil
- https://www.yegor256.com/2015/07/06/public-static-literals.html

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/controller/LottoController.java
> +    private List<Lotto> purchaseTicket() {
소스 파일은 일반적으로 위에서 아래로 읽습니다. 즉, 일반적으로 순서가 더 높은 선언을 이해하면 순서가 더 낮은 선언을 이해할 수 있도록 순서가 지정됩니다.

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/controller/LottoController.java
> +        return new AnswerLotto(toLotto(answerLottoInput), bonusNumber);
생성자의 수가 늘어날수록 클래스를 사용하기 위한 유연성은 높아집니다.

```suggestion
        return new AnswerLotto(new Lotto(answerLottoInput), bonusNumber);
```

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/controller/LottoController.java
> +        }
View에 대한 호출을 최소화해 보면 어떨까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/AnswerLotto.java
> +        });
`Collectors#groupingBy(Function, Collector)`를 찾아보고 그 기능을 사용해 보면 어떨까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<SingleLottoNumber> singleLottoNumberList;
`List` 대신 `Set`을 사용하면 어떨까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/Lotto.java
> +        message.append("]");
Model에 View의 요구 사항을 반영하는 것이 맞을까요? Model과 View의 기능을 분리하면 어떤 장점이 있을까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/LottoCalculator.java
> +public class LottoCalculator {
`LottoCalculator`는 `LottoPrize`와 합칠 수 있을까요? 아래의 글이 도움 될 거예요.
https://techblog.woowahan.com/2527

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/LottoPrize.java
> +    FIRST_PRIZE(2000000000, "6개 일치", new FirstPrizeStrategy()),
Java 7부터는 `100_000_000`처럼 숫자에 밑줄을 사용하여 가독성을 높일 수 있어요.

```suggestion
    FIRST_PRIZE(2_000_000_000, "6개 일치", new FirstPrizeStrategy()),
```

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/PrizeCountMap.java
>      @Override
`equals()`, `hashCode()`, `toString()`이 마지막에 위치하는 것이 일반적인 관례입니다.

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/domain/SingleLottoNumber.java
>  public class SingleLottoNumber implements Comparable<SingleLottoNumber> {
아래의 질문에 답해 보면 좋을 것 같아요.

- `SingleLottoNumber` 인스턴스가 만들어지는 경우의 수는 몇 가지 일까요?
- 미리 생성하여 필요할 때마다 사용해 볼 수 있을까요?
- 위의 방식은 어떤 장점이 있을까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/utils/RandomLottoGenerator.java
>  package lotto.utils;
비즈니스 문제를 해결하는 클래스들이 `domain` 패키지에 위치하면 어떨까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/main/java/lotto/view/OutputView.java
> +    public void printPurchaseResult(int manualLottoCount, int autoLottoCount) {
이왕 만든 `LottoCount`를 사용하면 어떨까요?

2023-01-09 06:00 UTC, wotjd243 commented on src/test/java/lotto/domain/AnswerLottoTest.java
> +public class AnswerLottoTest {
아래의 글을 읽고 느낀 점을 전체 코드에 반영해 보면 어떨까요?
https://blog.kingbbode.com/52

2023-01-09 06:00 UTC, wotjd243 commented on src/test/java/lotto/domain/StoreTest.java
> +        assertThat(store.calculateTicketCount()).isEqualTo(inputMoney / LottoRule.PRICE);
변수와 필드 대신 실제 값을 사용하여 단언문을 작성해 보세요.

2023-01-25 13:03 UTC, Sangyups commented
커밋 하나를 실수로 잘못 작성해서 force-push 하였습니다. 직전 커밋 하나만 reset하긴 했지만 앞으로는 꼼꼼히 살펴보겠습니다.

위의 리뷰대로 코드를 변경해보았습니다. 한 가지 궁금한 점이 있는데,
> 변수와 필드 대신 실제 값을 사용하여 단언문을 작성해 보세요.

이것을 보면서 든 생각이, 실제 값을 사용한다면 요구사항이 변경될 때마다(ex. 로또의 가격이 오르면 살 수 있는 개수도 달라진다.) 테스트 케이스를 새로 작성해야 할 텐데, 테스트 케이스를 수정하면서 생길 수 있는 human error는 감수해야 하는 걸까요? 복잡한 로직의 경우 테스트 케이스를 고치면서 테스트가 통과하지 않을 때 구현 코드와 테스트 케이스 둘 다 살펴보면서 의심하려면 상당히 어려울 것 같습니다.

2023-01-30 01:42 UTC, mjin1220 commented
@wotjd243 시간되실 떄 [위 질문](https://github.com/next-step/java-lotto-kakao/pull/78#issuecomment-1403573971)에 대한 답변 부탁드릴게요 :)

2023-01-30 01:43 UTC, mjin1220 approved these changes
기능 동작에 이슈가 없어보이고, 테스트 코드도 잘 작성해주신 것으로 보입니다 👍🏼 
원활한 미션 진행/완료를 위해 머지하도록 하겠습니다.
고생하셨습니다. 👏👏👏

2023-01-30 01:43 UTC, merged