[sienna.o] 로또 미션 2단계
2023newkrew/java-lotto-kakao pull request #79
Opened 2023-01-05 06:36 UTC by binimini

안녕하세요 맷! 저번 로또 1단계에 이어서 로또 2단계를 구현했습니다. 
이번 단계에서는 어떻게 이번 단계 코드를 활용하면서 추가 요구사항을 반영할 수 있을지 고민했던 것 같습니다.
변경사항을 요약하자면 아래와 같습니다!

### 변경사항
- `InputView`
   - 단순 String 반환 -> `NumberParser` 사용해 원시값을 포장한 형태로 반환 (Integer, List<Integer> 등)
   - 어플리케이션 로직 (`main()`) 내 흐름이 잘 보이도록 파싱까지 내부에서 수행
- `LottoStore`
    - 로또 구매시에 사용자가 입력한 로또 리스트(수동 로또)를 넘겨받음 
    - 구매된 로또 반환시 `List` -> `PurchasedLotto` (dto) 형태로 반환
    - 기존 자동 로또 구매 함수를 이용해 수동 로또 구매 후 남은 금액으로 자동 로또 구매
    - 구매금액의 유효성 검증 함수 분리
- `OutputView`
   - `List<Lotto>` -> `PurchasedLotto` 받아서 수동 로또와 자동 로또 개수 구분해서 출력
   
항상 리뷰 감사합니다! ✨

2023-01-06 01:32 UTC, matt-jylee requested changes
이번 개선에서 가장 심도있게 생각해 보실 부분은 Lotto입니다.
이 친구는 많은 부분에 관여하는 팔방미인 느낌이 들었습니다.
열심히 공부하셨을 키워드인 "응집도" "결합도" 관점에서 한번 더 고민해 보시면 좋겠습니다.

2023-01-06 01:32 UTC, matt-jylee commented on src/main/java/controller/LottoApplication.java
>  public class LottoApplication {
전반적으로 큰 개선이 이뤄진것 같습니다.
1단계 코드보다 더 진화한 느낌이 들었습니다!

2023-01-06 01:32 UTC, matt-jylee commented on src/main/java/domain/Lotto.java
> +    static public Lotto ofAuto() {
일단 권장되는 순서는 
접근제어자를 앞에 둡니다.

ex)
public static void main
public void run

2023-01-09 00:11 UTC, binimini commented on src/main/java/domain/Lotto.java
> +    static public Lotto ofAuto() {
이 클래스에서 반대로 작성했네요 😅 수정하겠습니다!

2023-01-09 04:43 UTC, binimini commented
피드백 해주신 내용 읽어보니 Lotto가 너무 많은 클래스를 사용하고, 또 많은 클래스에서 사용되고 있어서 해당 부분에 대해서 수정했습니다!
### 변경사항
- `Lotto.getRank(WinningLotto)` -> `WinningLotto.getLottoRank(Lotto)`
    - Lotto가 DTO인 WinningLotto를 사용 -> WinningLotto만 Lotto를 의존 으로 수정
- `LottoPurchasePlace` 인터페이스 삭제
   - 구매 로직이 한 클래스 내에 처리하게되어 불필요해짐 -> 삭제
- `LottoStore`
    - 기존 : 구매 검증 (금액, 수량), 구매금액에 따른 자동 로또 구매
    - 수정 후 역할 : 구매 관련 로직 및 검증
    - 직접적인 로또 관련 처리 역할을 LottoBuyer에게 완전히 이동 (Lotto 의존하지 않도록 수정)
- `LottoBuyer`
    - 자동 로또 리스트와 수동 로또 리스트를 별개로 관리하도록 수정
    - 수동 및 자동 로또 생성 및 저장
    - DTO인 PurchasedLotto가 LottoBuyer 사용하도록 수정 (`PurchasedLotto.of(LottoBuyer)`)
### 궁금한 점
DTO만 도메인을 의존하도록 수정해 DTO와 도메인을 비교해 다른 형태로 변환하는 내용을 DTO가 가지게되었는데,
(`WinningLotto.getLottoRank(Lotto)` : `당첨 로또 WinningLotto 와 로또 Lotto 의 비교로 로또 등수 Enum을 반환`)
일반적으로 DTO가 다른 형태로의 변환을 가져도 되나요? 아니라면 Convertor와 같은 역할을 분리하나요?
만약 비교로 다른 형태를 만들어내는 내용(일종의 로직?)을 가진다면 WinningLotto는 DTO가 아니라 도메인이 더 적합한걸까요? 🤔

쓰다보니 내용이 너무 길어졌네요 😅 맷 항상 꼼꼼히 봐주셔서 감사해요!!

2023-01-09 14:15 UTC, matt-jylee approved these changes
언제나 코드를 삭제하는 것이 더 어려운데 어려운 일을 잘 해내신것 같습니다.
많은 연습이 되셨길 바랍니다.

다음 단계에서 뵙겠습니다!

덧. (WinningLotto.getLottoRank(Lotto) : 당첨 로또 WinningLotto 와 로또 Lotto 의 비교로 로또 등수 Enum을 반환)
이 부분은 이야기를 좀 더 들어봐야 할것 같습니다.

써주신 내용으로만 보면 DTO가 도메인 지식을 가지고 있는것 처럼 판단되고,
코드에서는 winningLotto::getLottoRank 이 사용되는 부분을 차라리 LottoRank 를 직접 사용하는건 어떨까 싶습니다.
하지만, 이전 리뷰에서 이야기했듯 위임으로 해결하는 방법이 정적 메서드를 사용하는 방법보다 한결 낫다는 의견을 드립니다.

2023-01-09 14:15 UTC, merged