[leo.pss] 로또 미션 2단계 - 로또 수동 리뷰요청 드립니다.
2023newkrew/java-lotto-kakao pull request #80
Opened 2023-01-05 06:42 UTC by HolywaterPark

안녕하세요 캐니!
이번 로또 미션 2단계에서는 로또를 일부 수동으로 구매할 수 있는 기능이 추가되었습니다.
또 1단계에서 피드백 주셨던 내용들을 바탕으로 리팩토링을 진행하였습니다.
피드백 주시면 열심히 고쳐보도록 하겠습니다.
항상 감사합니다!!

2023-01-05 14:24 UTC, allstarkenny requested changes
레오 오늘도 열정적으로 코드를 올려주셨군요 🙇 
조금 더 생각할 만한 내용들을 작성해드렸는데 아래 내용만 수정되면 머지하도록 하겠습니다~
첫 과제를 올려주셨을때 보다 점점 더 좋아지는 모습이 보여서 좋습니다. 화이팅이에요! 💪 💪 💪 💪

2023-01-05 14:24 UTC, kenny-kim2 commented on README.md
> +- 입력, 출력하는 로또 번호는 쉼표(,)를 기준으로 구분한다.
README 부터 수정하는것 좋네요 👍

2023-01-05 14:24 UTC, kenny-kim2 commented on src/main/java/lotto/controller/LottoController.java
> +            lottoService.setPurchaseAmount(inputPurchaseAmount);
p3; 아마 가이드 중에 Setter를 쓰지 않기로 했는데 Setter를 사용하지 않고 구현해볼까요?

2023-01-05 14:24 UTC, allstarkenny commented on src/main/java/lotto/controller/LottoController.java
> +    private void inputPurchaseAmountController() {
p4; 네이밍이 조금 아쉬운 것 같아요. Controller라는 명칭이 꼭 들어가야 할까요?

2023-01-05 14:24 UTC, allstarkenny commented on src/main/java/lotto/controller/LottoController.java
> +        inputPurchaseAmountController();
p4; 혹시 여기에 사용하신 메소드를 전부 void 형태로 만드신 이유가 있으실까요?

2023-01-05 14:24 UTC, allstarkenny commented on src/main/java/lotto/model/LottoCount.java
> +        Integer manualLottoCount = StringUtil.convertStringToInt(manualLottoCountString);
p4; 이렇게 되면 StringUtil.convertStringToInt() 함수가 계속 반복될것 같네요. 
validateTypeOfManualLottoCount 함수에서 manualLottoCount 를 int형으로 변환된 내용을 넘겨주면 간단하게 해결되지 않을까요?

2023-01-05 14:24 UTC, allstarkenny commented on src/main/java/lotto/model/LottoTicket.java
>          List<LottoNumber> lottoNumbers = numbers.stream()
p4; 혹시 lottoNumbers가 정상적인 형태로 나오지 않는 경우가 있을까요?
아래 validation은 제외해도 되지 않을까? 라는 생각이 드네요 😢

2023-01-05 14:24 UTC, allstarkenny commented on src/main/java/lotto/model/PurchaseAmount.java
> +        }
오호 새로운 예외처리 좋네요 👍

2023-01-05 14:24 UTC, allstarkenny commented on src/main/java/lotto/model/PurchaseAmount.java
>  public class PurchaseAmount {
p3; 여기 생성자를 이전 PR에서 못보고 넘어갔군요 ㅠ
validation 체크를 하는것은 좋은데 validation 체크와 변수 할당을 생성자에서 분리할 필요가 있을까요? 😢

2023-01-09 00:20 UTC, HolywaterPark commented on src/main/java/lotto/model/LottoTicket.java
>          List<LottoNumber> lottoNumbers = numbers.stream()
아래 validation 함수 자체는 수동번호나 당첨번호등을 직접 입력받을 때 그 길이가 적절한지 판단하고 있어서 제외하긴 어려울 것 같습니다..! 해당 생성자에서 validation을 제거하는 것은 맞는 것 같습니다.
이와 관련해서 궁금한 점이 있습니다. 위와 같이 로또티켓을 올바르게 생성해서 validation을 할 필요가 없는 경우, 즉 로직을 정확하게 작성했다면 별도의 validation을 추가하진 않나요? 테스트 코드를 통해서 로직이 정확한지만 체크하면 되는 걸까요?

2023-01-09 00:51 UTC, HolywaterPark commented on src/main/java/lotto/controller/LottoController.java
> +        inputPurchaseAmountController();
컨트롤러를 리팩토링 할 때 로직에 필요한 객체(구매 금액, 로또 개수, 당첨 번호...)를 서비스가 들고 있는게 맞다고 생각했는데, 다시 보니까 컨트롤러가 들고 있으면서 넘겨주는게 맞는 것 같습니다..! 수정하도록 하겠습니다!!

2023-01-09 03:07 UTC, HolywaterPark commented
안녕하세요 캐니! 피드백 주신 내용 바탕으로 수정했습니다.
혹시나 제 수정방향이 잘못되었거나 더 나은 방향이 있다면 얼마든지 피드백 주시면 감사하겠습니다.
항상 감사합니다!!

2023-01-09 06:57 UTC, allstarkenny approved these changes
레오~ 고생하셨습니다 👍 
머지해도 괜찮을것이라 판단하여 머지하도록 하겠습니다.
다음 과제에서 뵈어요 🙇

2023-01-09 06:57 UTC, allstarkenny commented on src/main/java/lotto/model/LottoTicket.java
>          List<LottoNumber> lottoNumbers = numbers.stream()
아하 좋은 질문 감사합니다.
물론 취향의 문제일 수 있지만 제 생각은 레오가 말씀하신대로 테스트 코드를 통하여 로직이 정확하다고 판단이 되면 별도의 validation 코드가 추가되지 않아도 된다고 생각합니다. 극단적으로 예를 들면 int형 변수를 하나 할당해두고 해당 변수가 int인지 확인하지 않는것 처럼요. 😅 다만 외부에서 변수할당이 사용된다면 당연히 필요하겠죠 ㅎㅎ

2023-01-09 06:57 UTC, allstarkenny commented on src/main/java/lotto/model/PurchaseAmount.java
> +    private Integer validateTypeOfPurchaseAmount(String purchaseAmount) {
p4; 중복 로직을 잘 수 정해주셨군요 👍 다만 이렇게 되면 네이밍이 좀 애매한것 같아요.
메소드 네이밍을 좀 바꾸면 좋을 것 같습니다.

2023-01-09 06:57 UTC, merged