로또 미션 2단계
2023newkrew/java-lotto-kakao pull request #83
Opened 2023-01-05 06:52 UTC by kimtaehyun98

안녕하세요 웨이드! 로또 미션 2단계 완료해서 PR 보냅니다.

## 변경사항
### 1) calculator 병합
이번 단계에서 1단계 코드리뷰에 대해서 많은 고민을 했습니다.
특히 웨이드가 고민해보라 했던 "Calculator 로직의 클래스 분리 장단점"에 대해서 깊이 고민해본 결과 아래와 같은 결론을 내렸습니다.

**리팩토링 해보면서 느낀 점은 Calc 로직이 WinnerTicket 안에 있어야 더 깔끔함**
- 클래스 분리 시 계속해서 인자로 넘겨야 되고 이러한 부분들이 너무 많아서 힘들었음
- stateless 하게 유지하기 위해 변경하다 보니 calculator 자체가 필요 없어졌다고 생각했음
- 웨이드 말처럼 이렇게 DTO가 인자로 넘어가면 불필요한 노출이 될 수 있다고 생각

### 2) 클래스 명 변경
기존 클래스들 명이 직관적이지 못하다는 생각이 들었습니다.
ex) LottoTickets는 여러개의 티켓을 가지고 있다는 것인가? 티켓은 사람당 한 명씩 사는 것 아닌가?

따라서 아래와 같이 변경하였습니다.
- LottoTickets -> LottoTicket
- LottoController -> LottoGame
- LottoTicket -> LottoNumber

### 3) enum 추가
계속해서 List만 고집하려고 했었는데, 이번에는 Map을 활용해서 구현해보았습니다.

이 외에도 수동 로직을 구현하였습니다.
감사합니다! 😆

2023-01-09 02:03 UTC, wade-lim requested changes
고생하셨습니다!

`LottoTicket` 쪽에 코멘트 드린 부분이 작업량이 좀 많을 것 같은데, 코멘트 확인 부탁드립니다~

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
[의견]
이 클래스가 사실상 티켓의 의미로 쓰이는 클래스라면 `LottoTicket` 과 같은 이름이 적합할거 같아요~
요구사항에는 없지만 티켓에는 구매일자, 구매자 등등 다른 부가 정보도 들어갈 수도 있으니까요~

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/domain/LottoTicket.java
> +    private final int purchaseCount;
[확인]
하나의 클래스에 기능이 너무 많은거 같네요~
1. 여러 티켓을 저장하는 Collection 기능
2. 랜덤하게 번호를 생성하는 기능
3. 금액에 맞게 티켓을 구매하는 기능

단순하게 숫자를 저장하는 `LottoTicket`, 금액과 구매한 티켓을 가지는 `Customer`, 랜덤 번호 생성/금액에 맞게 티켓 생성 등 티켓을 발행해주는 `LottoStore` 과 같이 기능을 분리하면 좋을 것 같아요. 

추가적으로 `LottoTicket` 이라는 클래스 명을 봤을 때 6개의 번호만 저장되어 있을 것 같은데, 여러 티켓이 저장되어 있네요.
`LottoTickets`, `LottoTicketList` 등등 일종의 리스트 역할을 한다는 의미를 이름에 담는게 좋을거 같아요!

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/controller/LottoGame.java
> +}
[질문]
요 클래스가 필요한 이유가 있을까요?
객체를 생성해주는 팩토리가 목적이라면 필드 없이 바로 LottoTicket 을 생성해주도록 하는게 좋을 것 같고, 사실 팩토리로 사용하기에도 사실상 LottoTicket 생성자와 역할이 같을 것 같아요.

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/utils/LottoRank.java
> +
[의견]
당첨금을 enum 으로 만든거 좋은거 같네요 👍

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/domain/LottoWinnerTicket.java
> +                .reduce(0, (sum, now) -> sum + checkContains(now));
[의견]
`filter` 와 `count` 를 이용하는 것도 좋아보여요~

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/domain/LottoWinnerTicket.java
> +    }
[확인]
함수 목적 상 boolean 을 반환해야 할 것 같아요

2023-01-09 02:03 UTC, wade-lim commented on src/main/java/lotto/view/InputView.java
>  package lotto.view;
[의견]
클래스가 View 와 Controller 의 역할을 동시에 하는 것 같네요~
`LottoTicket` 쪽에서 코멘트 드린 것처럼 티켓 발행 기능을 `LottoStore` 로 옮기면 괜찮아질듯 합니다.

2023-01-10 00:09 UTC, kimtaehyun98 commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
처음에는 실생활과 연관지어 생각해봤던 것 같아요! 실제로 로또 티켓(LottoTicket)을 구매했을 때 그 안에 6자리 숫자(LottoNumber)가 여러개(List<LottoNumber>) 있다 라고 생각해서 이름을 지었었는데 확장성에서 확실히 부족하다고 느껴지네요..

2023-01-10 00:09 UTC, kimtaehyun98 commented on src/main/java/lotto/domain/LottoTicket.java
> +    private final int purchaseCount;
리뷰의 Customer와 LottoStore를 보고 정말 띵 했습니다.. 왜 저걸 분리할 생각을 하지 못했던건지..  각 기능에 맞게 클래스 분리 후 push 했습니다!

2023-01-10 00:10 UTC, kimtaehyun98 commented on src/main/java/lotto/controller/LottoGame.java
> +}
이전에는 단순히 Controller가 있어야 한다는 생각에 코드를 구현했던것 같아요. 이번에 리뷰 반영하면서 Customer 클래스와 Store 클래스를 분리하게 되었고, 이를 Controller에서 생성하는 식으로 구현했습니다!

2023-01-10 00:10 UTC, kimtaehyun98 commented
계속해서 설계가 부족했다는 느낌이 드네요ㅠㅠ 이미 짜여진 코드에서 리팩토링 하려고 하니 쉽지 않네요 😂
웨이드가 말해준것처럼 LottoTickets를 분리해 보니 클래스 각각이 주어진 역할만 하도록 된 것 같네요.
리뷰 감사합니다~!

2023-01-10 22:40 UTC, wade-lim approved these changes
수정 분량이 많으셨을텐데 고생하셨습니다~

2023-01-10 22:40 UTC, merged