[davi] Step2
2023newkrew/java-lotto-kakao pull request #85
Opened 2023-01-05 07:46 UTC by Siryeong

니오 안녕하세요 step2 수동 로또의 pr을 요청드립니다.
항상 꼼꼼하고 좋은 리뷰 달아주셔서 감사합니다 :)
따끔한 피드백 기다리고 있겠습니다.

2023-01-05 13:46 UTC, sehan requested changes
안녕하세요 davi 

step1 의 피드백을 잊지 않고 잘 반영해주셨네요  👍
step2 에 추가된 수동로또 생성에 대한 책임을 맡아줄 객체가 있으면 좋을거 같습니다. 
관련해서 코드에 코멘트 남겨두었습니다.  그리고 사용자 입력에 대한 예외처리를 신경써서 추가해 주세요.

개선요청 드립니다.

2023-01-05 13:46 UTC, sehan commented on src/main/java/lotto/App.java
> +        lottos.addAll(generator.generateLottos(auto));
로또생성 역할을 어떤 객체가 가지고 있나요? 
이 부분을 다시한번 생각해 볼 필요가 있습니다. RandomLottoGenerator  가 로또를 자동으로 생성하는 역할을 맡고 있습니다. 그러면 수동으로 입력받은 로또는 누가 생성해 주나요? 현재 구현에서는 View 에서 직접 구현하고 있습니다. 수동 로또는 생성해주는 역할을 새로운 도메인 객체에게 부여해보는건 어떨까요?

2023-01-05 13:46 UTC, sehan commented on src/main/java/lotto/domain/LottoResult.java
>      public LottoRank getRank() {
리팩토링 후 현재의 LottoResult 를 보니 로또와 당첨번호를 가지고 당첨결과를 제공해주는 역할을 하고 있습니다. 클래스 멤버로 있는 count, bonus 의 상태를 관리할 필요가 있는것인지 의문이 생깁니다. 즉, LottoResult 를 사용하는 Statistics 에 getRank(Lotto myLotto, Lotto winningLotto, LottoNumber bonusNumber) 매소드로 제공해도 될거 같다는 생각이 듭니다.

2023-01-06 12:41 UTC, siryeong commented
니오 안녕하세요~ step2의 개선사항을 반영하여 다시 리뷰요청 드립니다.
항상 좋은 리뷰 달아주심에 감사합니다.

이번 리팩토링을 진행하며 소소하게 궁금한 점이 있었는데요
1. 사용자 입력에 대한 예외를 모두 throw Exception으로 처리했는데, 실제 프로덕션에서는 이렇게 처리하면 장애요인이 되진 않을까 하는 궁금함이 있습니다.
2. 입력 예외처리의 경우 validator를 만들어 view딴에서 더블체크를 하는 것이 좋을지에 대해 고민이 있었는데요. 그럴 경우 로직이 같은 중복된 코드가 생산되더라도 해주는 것이 좋을지 고민이 됩니다. 어쩌면 제가 아직 view를 제대로 분리해 내지 못해서 오는 고민일 수도 있겠네요!

따끔한 피드백 기다리고 있겠습니다!

2023-01-09 06:37 UTC, sehan commented
> 니오 안녕하세요~ step2의 개선사항을 반영하여 다시 리뷰요청 드립니다. 항상 좋은 리뷰 달아주심에 감사합니다.
> 
> 이번 리팩토링을 진행하며 소소하게 궁금한 점이 있었는데요
> 
> 1. 사용자 입력에 대한 예외를 모두 throw Exception으로 처리했는데, 실제 프로덕션에서는 이렇게 처리하면 장애요인이 되진 않을까 하는 궁금함이 있습니다.
> 2. 입력 예외처리의 경우 validator를 만들어 view딴에서 더블체크를 하는 것이 좋을지에 대해 고민이 있었는데요. 그럴 경우 로직이 같은 중복된 코드가 생산되더라도 해주는 것이 좋을지 고민이 됩니다. 어쩌면 제가 아직 view를 제대로 분리해 내지 못해서 오는 고민일 수도 있겠네요!
> 
> 따끔한 피드백 기다리고 있겠습니다!

1.  도메인에서는 예외에 맞는 exception 을 정의해서 throw 해주는것이 맞습니다. 도메인 객체를 사용하는 caller 들이 각 상황에 맞게 예외를 처리할 수 있기 때문입니다.  사용자 입력의 경우 exception 발생시 적절한 예외처리, 즉, 사용자 친화적인 처리가 필요합니다.  exception stacktrace 를 그대로 화면에 출력해 버리면 사용자(일반사용자, 개발자가아닌) 가 이 메세지를 보고 어떻게 느낄까요? 이 부분을 생각해 보시면 됩니다. 

2. 원론적으로 이야기를 하자면 웹 서비스구성을 예로 front 와 backend 측면에서 사용자 입력에 대한 validation 처리를 모두 구현합니다. 중요도로 보자면 backend 측 validation 이 더 우선입니다.  backend 측 validation 이 갖추어져야 사용자 입력을 통해 만들어지거나 변경되는 data 의 일관성이나 신뢰성이 보장되기 때문입니다.  front 측 validation 을 하는 이유는 사용자에게 더 나은 사용자 경험을 제공하고 위함입니다.  front 에서 즉각적으로 입력에대한 오류를 확인해서 사용자에게 빠른 피드백을 제공해주면 사용자는 긍정적인 경험을 하게 되지만 입력을 다 하고 나 후 저장 버튼을 눌렀더니 입력값에 문제가 있어서 저장이 안된다는 피드백을 받으면 "입력할때 좀 알려주지?" 하는 생각이 들게 될겁니다. 이런 관점에서 생각해 보시면 될거 같습니다.  다시 말해 front, backend 모두 validation 을 구현한다. 구현자 측면에서는 증복이라 생각될 수 있지만 사용자 측면에게는 더 나은경험을 제공 받을 수 있다 라고 할 수 있겠습니다.

2023-01-09 06:38 UTC, sehan commented
@Siryeong 제가 오늘까지 휴가인 관계로 step2 에 대한 리뷰는 오후 늦게 진행 가능할거 같습니다. 
우선 질문에 대한 답만 우선 드려요 😊

2023-01-10 00:42 UTC, sehan approved these changes
긴 휴가로 인해 이제서야 늦은 리뷰를 진행합니다. 😣

피드백 내용을 잘 반영해주셨습니다. 
예외처리 부분과 테스트 작성에 대해 코멘트를 남겨 두었습니다. 
다음 미션진행시 참고하시어 진행하시면 좋겠습니다. 

고생하셨습니다. 👏👏👏

2023-01-10 00:42 UTC, sehan commented on src/main/java/lotto/view/LottoView.java
> +    }
try {} catch 후 다시 throw 한다는 것은 throw 한 exception 을 누군가 처리를 해줄거라는 의도 입니다. 해당 매소드를 사용하는 최종 caller 인 App 객체 에서도 exception 을 try/catch 하지 않고 있기 때문에 해당 exception 은 아무도 책임지지 않고 있다는 말이 됩니다.

2023-01-10 00:42 UTC, sehan commented on src/test/java/lotto/LottoGenerateTest.java
> +        assertThat(ManualLottoGenerator.generateLottos(userInputs)).contains(new Lotto(1,2,3,4,5,6));
테스트 작성시 테스트 객체는 테스트할 대상이 명확해야 합니다.

테스트 클래스에 테스트할 대상 객체를 여러개 포함해서 작성하지 않는게 좋습니다.
테스트할 대상이 여러개라면 테스트 클래스를 분리해서 작성해주세요

여러 객체들을 조합해서 테스트하는 코드들이 많이 발생한다면 조합에 참여한 객체들이 함께 처리하는 역할을 할 새로운 객체가 필요한건 아닌지 생각해 볼 필요가 있습니다. 객체들이 협력하여 어떤 역할을 하고 있다면 해당 객체들을 가지고 어떤 역할을 하는 객체가 필요하다는 신호 일수 있습니다.

2023-01-10 00:42 UTC, sehan commented on src/main/java/lotto/App.java
> +        lottos.addAll(RandomLottoGenerator.generateLottos(auto));
수동로또생성역할을 새로운 객체에게 잘 넘겨주셨습니다. 
한가지 더 생각해 볼 점은 수동로또, 자동로또를 생성하기 위해서 사용자가 사용해야할 ( 알아야 할 ) 클래스가 좀 많아 보인다는 것입니다.  
다시말해서 "5000원이 있는데 수동으로 1장 (1,2,3,4,5,6) 나머지는 자동으로 로또 발급해줘" 라고 쉽게 이야기하고 싶은데 현재 구현대로 라면 
1. 수동로또 1장 구매할께
2. 수동로또 1장 발급해줘
3. 자동로또 4장 구매할께
4. 자동로또 4장 구매해줘

해야 합니다.  이 부분을 어떻게 개선해 볼수 있을까요? 
관련해서 파사트(Facade) 패턴이 무엇인지 참고해보면 좋을거 같습니다.

2023-01-10 00:42 UTC, merged