[verus.j] 로또 2단계
2023newkrew/java-lotto-kakao pull request #86
Opened 2023-01-05 09:00 UTC by wilgur513

1단계에서 주신 피드백 적용과 수동 로또 구매 기능을 구현했습니다
피드백에 대한 답변도 이전 PR에 남겨뒀습니다~

2023-01-05 12:38 UTC, parksjin01 requested changes
로또 2단계 미션 진행하시느라 고생하셨습니다 
1단계 PR에서 드렸던 코멘트도 잘 적용해주신것 같아요 👍 

1단계 PR중 베루스가 남겨주셨던 [의견](https://github.com/next-step/java-lotto-kakao/pull/5#discussion_r1062157240)에 대해서는 1단계 PR에 추가 의견 남겨뒀습니다.
수정해주실 필요는 없고, 이런 의견도 있구나하고 참고만 해주시면 될 것 같아요 😄 

이번에 요청주신 PR에서 몇가지 코멘트를 남겨뒀습니다.
코멘트를 참고하셔서 수정해주셔도 좋고, 베루스의 의견을 남겨주셔도 좋을것 같아요

2023-01-05 12:38 UTC, parksjin01 commented on src/main/java/lotto/model/Lotto.java
>      }
`Lotto`의 `createRandomLotto` 메소드를 보다보니 
"`LottosGenerator` 인터페이스를 삭제할 수 있지 않을까?" 라는 생각이 들었어요

현재 `LottosGenerator`의 가장 큰 역할은 필요한 만큼 `Lotto` 의 팩토리 메소드들을 호출해서 
로또 객체를 생성하는 것이라고 생각이 되는데요
이런 역할을 `LottoMachine` 클래스로 옮겨볼 수 있지 않을까요?

만약 `LottosGenerator`를 삭제하고 `LottoMachine` 클래스에서 로또를 생성한다면 
`LottosGenerator` 클래스들의 역할인 몇장의 로또를 생성해야하는지 `LottoMachine`에서 계산하고, `Lotto`의 팩토리 매소드를 호출해볼 수도 있을 것 같아요

꼭 인터페이스를 삭제해야하는 것은 아니지만, 이미 `LottoMachine` 클래스가 `Lotto` 클래스에 의존하고 
인터페이스가 없더라도 클래스의 역할을 적절히 나눌수 있을 것 같아서 제안드려봅니다.

2023-01-05 12:38 UTC, parksjin01 commented on src/main/java/lotto/model/LottoMachine.java
> +    }
위 메소드는 생성된 로또 정보 출력을 위해서 사용되는 것 같은데요, 
외부에서 데이터가 변경되지 않도록 `Collections.unmodifiableSet()`로 레핑해서 전달하면 좋을것 같아요

2023-01-05 12:38 UTC, parksjin01 commented on src/main/java/lotto/model/LottoNumber.java
>      }
지금은 `createPool` 메소드가 호출될 때마다 1 ~ 45의 `LottoNumber` 객체를 담은 객체 풀이 생성되는데요
메소드가 호출될 때마다 매번 객체 풀을 생성하는 것보다 1번만 객체 풀을 만들고 재사용하는 것이 어떨까요?

2023-01-05 12:38 UTC, parksjin01 commented on src/main/java/lotto/model/ManualLottosGenerator.java
> +    }
`LottosGenerator`를 보고 처음에는 로또 번호 생성 방법을 추상화한 인터페이스라고 생각했는데요
`ManualLottosGenerator`와 `Lotto` 코드를 보며 로또 번호 생성 방법이 아닌 로또를 생성하는 방법을 추상화 해주신것 같아요

`RandomLottosGenerator`는 자동 로또만 발급이 되지만, `ManualLottosGenerator`에서는 수동으로 발급된 로또외에 추가로 발급해야하는 자동 로또 수를 계산해서 자동 로또를 생성하는데요.
코드를 읽어보지 않고 클래스 이름만 봤을 때는 자동 로또도 생성된다고 파악하기 어려운것 같아요.

`Lotto` 클래스에서 피드백 드렸던 것처럼 필요한 장수를 계산하고, 로또를 발급하는 역할을 `LottoMachine`으로 옮겨보는 것은 어떨까요?

2023-01-05 12:38 UTC, parksjin01 commented on src/main/java/lotto/view/LottoInputView.java
>      }
자동 로또 티켓은 모델 객체에서 만드는데, 수동 로또 티켓은 뷰 객체에서 생성되네요
아마 비즈니스 로직을 담은 모델 객체들이 뷰에서 참조되지 않도록 하기 위해서 수동 로또를 뷰에서 생성하셨다고 상상해봤습니다.
(혹시 잘못 상상한거라면 말씀해주세요 😄 )

다만 자동 로또와 수동 로또 객체가 만들어지는 위치가 다르다 보니  수동 로또 객체가 생성되는 곳을 찾는 것이 어려웠는데요.
수동 로또도 모델 객체에서 생성되도록 변경해보는 것은 어떨까요?

지금은 수동으로 구매한 로또를 뷰에서 한번에 생성해서 반환하는데, 
뷰에서 1개의 로또 정보만 입력받고 컨트롤러로 로또 정보를 전달한 다음 모델 객체에 로또 생성을 요청한다면
수동 로또도 뷰가 아닌 모델 객체에서 생성할 수 있을 것 같아요.

2023-01-11 05:25 UTC, wilgur513 commented on src/main/java/lotto/model/Lotto.java
>      }
`LottoGenerator`를 삭제하면 LottoMachine을 어떻게 테스트해야할지 감이 안잡히네요 ㅠㅠ
`LottoGenerator`를 사용하는 이유 중에 테스트를 위한 로또 생성 스텁을 만들기 위해서 사용한 것도 있습니다.
스텁과 같은 목 객체의 의존성 주입 없이 로또 생성을 내부에서 추상화해서 내가 원하는 환경을 세팅하는 방법은 잘 모르겠습니다...

2023-01-11 06:40 UTC, wilgur513 commented on src/main/java/lotto/view/LottoInputView.java
>      }
이 부분은 고민을 많이 해봤지만, 당첨 번호 또는 구매 금액을 모두 view에서 객체를 생성해서 오히려 뷰 쪽에서 모델 객체를 생성하는 게 더 좋을 것 같습니다. 입력 받은 정보를 모델 객체로 변환하는 로직이 view와 컨트롤러에 흩어져 있으면 더 알아보기 힘들꺼 같아요...
우선은 뷰 쪽에 두겠습니다. 나중에 입력 받은 정보로 객체를 매핑하는 부분이 많이 복잡해지면 따로 매핑을 위한 객체를 만들꺼 같습니다.

2023-01-11 06:52 UTC, wilgur513 commented on src/main/java/lotto/model/ManualLottosGenerator.java
> +    }
저도 이름이 `ManualLottosGenerator`가 많이 아쉽다고 생각했는데... 같은 생각을 하셨군요 ㅠㅠ
로또 생성 역할을 `LottoMachine`으로 옮기게 되면, 이전에 말씀드렸듯이 테스트를 작성하기 어려워질 것 같습니다 ㅠㅠ
현재 의존성 주입을 통해서 테스트하기 어려운 부분을 격리시키고 있다보니... 어떻게 해야할 지 모르겠더라구요...
우선은 이름을 `ManualAndAdditionalLottosGenerator`로 변경했습니다

2023-01-11 08:40 UTC, parksjin01 commented on src/main/java/lotto/model/Lotto.java
>      }
로또 프로젝트도 랜덤한 수를 만들어내는 부분이 있어, 해당 부분을 인터페이스로 분리해야 테스트가 유리할 것 같기는 합니다.
랜덤한 수를 만드는 로직을 인터페이스로 분리해두면, 1주차 자동차 경주 미션에서 작성해주셨던 것처럼 
테스트시 별도의 목 객체 주입 없이 테스트를 위한 데이터를 생성하는 구현체 주입으로 테스트가 가능해서요

아래는 제가 생각했던 방법인데요, 참고만 해주시면 좋을 것 같아요
저는 `LottoMachine`에서 로또를 생성하는 메소드 만들어서, 해당 메소드에서 `Lotto` 팩토리 메소드를 호출하는 방법을 생각했어요
`LottoMachine`에서 로또를 만드는 메소드는 오버로딩을 통해 
`List<LottoNumber>` 파라미터가 전달된 경우 전달받은 숫자로 로또 팩토리 메소드를 호출하고, 
파라미터가 전달되지 않는 경우에는 `LottoMachine`에서 랜덤한 수를 만들어서 로또 팩토리 메소드를 호출하는 것을 생각했습니다.

테스트를 위해서 특정 숫자를 지정해서 로또를 생성해야하는 경우에는 `List<LottoNumber>` 파라미터를 전달받는 메소드를 사용하는 방법을 생각했고, 필요하다면 자동차 경주 미션처럼 랜덤한 로또 번호를 만드는 부분을 인터페이스로 추상화할 수도 있을 것 같아요

이런 생각을 했던 이유는 수동 로또를 만들 때 `LottosGenerator`의 역할이 애매해지는것 같더라고요
처음 올려주신 PR에서는 수동으로 발급된 로또외에 나머지 로또를 발급하고 있어서 `LottosGenerator`가 자동 로또를 만드는 역할만 하고 있다는 생각이 들었고,
자동 로또와 수동 로또를 모두 `LottosGenerator` 인터페이스 구현체에서 만드는 것은 수동 로또를 고려했을 때 요구사항 대비 복잡하다는 느낌을 받았습니다.

다만 기존처럼 수동 로또는 뷰단에서 생성하게 된다면 위 방법을 사용하는 것은 어려울것 같네요.

2023-01-11 08:46 UTC, parksjin01 commented on src/main/java/lotto/model/ManualLottosGenerator.java
> +    }
저도 좋은 이름을 정하는 것이 가장 어려운 것 같아요 😢 
기존 `ManualLottosGenerator`라는 이름을 보면 수동 로또를 발급해줄것 같은 생각이 드는데, 실제로는 자동 로또를 발급하고 있어 코멘트를 드렸었습니다.
자동 로또를 발급할 때는 `LottosGenerator` 인터페이스가 사용되지만 수동 로또는 해당 인터페이스를 사용하지 않아서 적절한 이름을 찾기 더 어려운것 같아요

만약 `LottosGenerator`라는 인터페이스를 사용하신 이유가 테스트를 위함이었다면,
로또를 생성하는 역할을 인터페이스로 추상화하는 대신, 자동 로또에 포함되는 숫자 생성을 추상화해보는 것도 방법이 될 수 있을 것 같아요.

2023-01-11 09:04 UTC, parksjin01 commented on src/main/java/lotto/view/LottoInputView.java
>      }
위 내용은 앞서 이야기나왔던 `LottoMachine`으로 로또 생성 책임을 옮기는 것이나, `LottosGenerator` 구현체의 이름과도 관련이 있을 것 같아요.

현재는 수동 로또와 자동 로또를 생성하는 책임이 각각 다른 클래스에 있다보니 로또를 만드는 위치를 찾는 것이 어렵고,
`LottosGenerator` 구현체의 이름을 정할 때에도 인터페이스가 자동 로또만 발급하다보니 적절한 이름을 찾기 어렵다는 생각이 들었어요.
동일하게 자동 로또를 발급하지만, 전체 로또가 자동 로또인 경우와 일부 로또만 자동 로또인 경우의 `LottosGenerator` 구현체가 분리되어 있어, 해당 내용을 잘 나타낼 수 있는 이름을 정하기 어렵고, 햇갈린다는 생각이 든 것 같아요.

`Money`나 `LottoNumber`가 뷰에서 생성된다는 점은 제가 놓쳤던 부분이네요. 😅 
다른 모델들이 뷰에서 생성되기 때문에 수동 로또를 뷰에서 만드는 것도 좋은것 같아요.

다만, 수동 로또와 연관된 개념인 자동 로또는 `LottosGenerator`에서 만들어지기 
때문에 수동 로또 생성 위치 변경을 고려해보는 것도 좋을 것 같아요 😄

2023-01-11 09:08 UTC, parksjin01 approved these changes
코멘트에 남겨주신 의견을 보며 많은 고민을 하신것 같다는 생각이 들었습니다.
베루스가 고민하고 계신 부분에 대해 제 생각을 달아뒀는데요, 참고해보시는 것도 좋을 것 같아요 😄 
추가로 남겨드린 의견과 관련하여 궁금하신 부분이 있으면 언제든 편하게 연락주세요 

로또 미션 머지하도록 하겠습니다. 2주차 미션 진행하시느라 고생 많으셨습니다 :)

2023-01-11 09:09 UTC, merged