[dao.123] 로또 2단계
2023newkrew/java-lotto-kakao pull request #87
Opened 2023-01-05 09:08 UTC by Jeothen

안녕하세요.
1차 피드백 내용 반영 / 2차 기능 (수동구매) 구현했습니다.

코드리뷰 부탁드립니다!!
감사합니다~

2023-01-05 09:23 UTC, Jeothen commented
commit이 1단계까지 다 올라가 버렸네요..

refactor: 보너스볼 중복 테스트 케이스 README에 추가
 - 여기까지가 1차 commit 내용입니다.

2023-01-09 01:37 UTC, sh-ju requested changes
중요한 수정 사항이 있어 수정 요청 보냅니다.

2023-01-09 01:37 UTC, sh-ju commented on src/main/java/lotto/LottoApplication.java
> +        amount -= manualCount * MIN_PURCHASE_PRICE;
변수가 저장하는 것의 형태가 변하는 것은 좋지 않은 습관인 것 같아요. (물론 최적화를 위한 것이라면 도움은 되지만)
amount 는 처음에 '전체 구매금액'이 되었다가, 
여기 구문이 지나고 나면 '자동번호 구매 금액'이 되는데요. 

amount의 변수명이 '자동번호 구매 금액을 나타내지 않는데다가,  
나중에 '전체 구매 금액'이 필요하면 다시 만들어야 하는 이슈가 생겨요. 
성능에 큰 이점이 없는 한 변수는 구별해서 사용하는 게 좋을 것 같아요.

2023-01-09 01:37 UTC, sh-ju commented on src/main/java/lotto/controller/LottoController.java
>  public class LottoController {
(중요)
**1. Stateful -> Stateless**

LottoController가 state을 가지게 되었어요. 
state을 가지게 되면 매번 생성해서 다뤄야 하는 이슈가 생깁니다. 
1개의 controller는 1번의 게임만 컨트롤을 할 수 있고, N번의 게임을 컨트롤 하려면 N개의 컨트롤러를 생성해야 합니다. 
(지난번 Service layer에 상태 제거 하는 거랑 동일한 이슈예요.)

controller를 stateless로 만들 필요가 있습니다.

2023-01-09 01:37 UTC, sh-ju commented on src/main/java/lotto/controller/LottoController.java
> +    private final LottoTickets Tickets;
대소문자도 신경 써 주세요.

2023-01-09 01:37 UTC, sh-ju commented on src/main/java/lotto/domain/LottoTicket.java
>          this.lottoNumbers = lottoNumbers;
변수에 값을 먼저 대입 한 후에 argument 체크를 하게 되면, 
아래 IllegalArgumentException이 발생하더라도  this.lottoNumbers에는 lottoNumbers가 저장되어 있습니다.

2023-01-09 01:37 UTC, sh-ju commented on src/main/java/lotto/domain/WinnerScore.java
> +    public void addScore(int index){
WinnerScore 분리까지는 좋았는데, index를 외부에서 보내주게 되어 있네요. 
index는 WinnerScore내부 데이터 저장에 관여하는 것이라 외부에 open 하지 않고, 내부적으로 처리하는게 좋습니다. 
(외부에서 WinScore내부 ArrayList의 저장 index를 직접 관여하지 않는다는게 핵심입니다.

외부에는 이런식의 고정 변수가 오픈되면 코드가 좀 더 명확해 질 것 같아요. 

public static final int WIN_MATCH_THREE = 1
public static final int WIN_MATCH_FOUR = 2
public static final int WIN_MATCH_FIVE = 3
public static final int WIN_MATCH_FIVE_PLUS = 4
public static final int WIN_MATCH_SIX = 5

2023-01-10 01:07 UTC, sh-ju requested changes
코드를 조금 더 보강 해야 할 것 같아요.

2023-01-10 01:07 UTC, sh-ju commented on src/main/java/lotto/domain/LottoTickets.java
> +        this.tickets = new ArrayList<>();
ArrayList는 API spec으로 보면 가변 길이인데, 내부적으로 메모리 할당은 고정 길이를 사용하고 있습니다. (어찌보면 당연하겠죠?)

외부에는 동적길이를 유지하지만, 내부적으로는 고정길이를 사용하고 있는데, 그 원리를 알아 두면 나중에 도움이 될겁니다. 
Java 내부 스펙이라 Java버전 따라 내부 구현체가 달라 질 수도 있지만 (아마 크게 다르진 않을꺼예요.) 
아래 부분 참고 해보시면 도움 되실거예요. 

- 국문 
ㄴ http://heather-dev.tistory.com/32

- performance 이야기
ㄴ https://medium.com/@malith.jayasinghe/a-performance-evaluation-of-java-arraylist-f097582b5c4d

- code (intelliJ 같은데서 코드 따라가 보면 도움 되실거예요.)
ㄴ https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/ArrayList.java#l237

2023-01-10 01:07 UTC, sh-ju commented on src/main/java/lotto/controller/LottoController.java
>  public class LottoController {
LottoController, LottoTickets 두 개 클래스 얘기 입니다. 

저도 깊이가 부족하긴 하지만, dao 코드에 아래 두 가지 패턴이 조금 섞여 있는 듯 해요. 
DDD 패턴은 domain 레이어에 데이터의 흐름(로직의 구현)을 맡기는 형식이고요. 
MVC는 데이터의 제어를 controller(+service)에게 맡기는 형식이예요. 
두 패턴 모두 데이터의 저장은 Model (Domain)에 하고요.
적당히 섞여 있어도 큰 문제는 없겠지만, 하나를 제대로 사용하는게 좋을 것 같고요. 

우선 가장 큰 이슈는 Runtime 시에 에서 두 개의 클래스가 stateful로 각각 1개씩 생성 되는데요. 
이 부분이 중복이고, 오류 발생 소지가 많아서 Controller쪽에 state를 제거 하는 방향으로 의견 드렸어요. 
(그래야 MVC 패턴이 되거든요.)
**그러려면  controller에 tickets 변수가 없어야 합니다.**

2023-01-10 08:15 UTC, sh-ju approved these changes
모든 요청 내용이 잘 반영되어 있네요. 고생하셨어요.

2023-01-10 08:15 UTC, merged