[bayne.jeong] 로또 2단계 제출합니다!
2023newkrew/java-lotto-kakao pull request #92
Opened 2023-01-05 10:05 UTC by jungin0507

- 수동 로또 번호를 받을 수 있는 기능을 추가했습니다.

단순히 수동 로또가 가능하다는 요구사항 하나만 추가 됐을 뿐인데 변경해야할 부분이 너무 많네요
나름 초기 설계를 잘 했다고 생각했는데 부족한 부분이 많다고 느껴집니다 ㅠㅠ

## 로또 티켓 발행 로직 변경
As-is: LottoStore에서 로또 번호를 생성해서 로또 티켓 발행
To-be: Controller에서 로또 번호를 생성해서 LottoStore에 넘겨준 후 티켓 발행

## 로또 구매 로직 변경
As-is: LottoStore에 금액을 넘겨주면 금액에 맞는만큼의 로또 티켓을 구매
To-be: Controller에서 금액에 맞는 만큼 LottoStore에 로또 티켓 구매 요청

2023-01-09 16:42 UTC, wotjd243 requested changes
전체적인 설계와 깔끔한 코드 구현이 좋았습니다. 👍 
조금 더 고민해 보면 좋을 것 같은 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/controller/LottoController.java
>  package controller;
`lotto` 패키지를 기준으로 프로젝트를 관리하면 어떨까요? 아래의 글이 도움 되면 좋겠어요.
https://wikidocs.net/231

```suggestion
package lotto.controller;
```

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/controller/LottoController.java
> +        }
View에 대한 호출을 최소화해 보면 어떨까요?

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/UserAccount.java
> +        validateBalance();
메서드 몸체가 시작되기 전에 유효성을 검사하면 어떨까요? 아래의 글을 참고하세요.
https://leedo1982.github.io/wiki/ITEM49

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/UserAccount.java
> +    public void withdraw(int money) {
`withdraw()`에 대한 테스트 코드를 작성해 보면 어떨까요?

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/lotto/LottoResultCalculator.java
>      private double calculateEarningRate() {
아래의 글을 읽고 코드에 반영하면 어떨까요?
https://tecoble.techcourse.co.kr/post/2021-04-26-BigInteger_BigDecimal

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/lotto/store/dto/LottoTicketBuyRequestDto.java
> +public class LottoTicketBuyRequestDto {
사용하지 않는 코드는 과감하게 지우는 것이 좋겠어요.

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/lotto/ticket/LottoTicket.java
>      private final List<LottoNumber> lottoNumbers;
`List` 대신 `Set`을 사용하면 어떨까요?

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/lotto/ticket/generator/LottoTicketGenerator.java
>  public interface LottoTicketGenerator {
`LottoTicketRandomGenerator`가 있다면 수동으로 로또를 생성하는 구상 클래스(concrete class)도 있어야 하지 않을까요?

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/lotto/ticket/generator/LottoTicketGenerator.java
> +    List<LottoNumber> generate();
"`LottoTicketGenerator`는 `List<LottoNumber>`를 생성한다."라는 설계는 자연스러울까요?

2023-01-09 16:42 UTC, wotjd243 commented on src/main/java/domain/lotto/ticket/generator/LottoTicketRandomGenerator.java
>                  .mapToObj(LottoNumber::new)
아래의 질문에 답해 보면 좋을 것 같아요.

- `LottoNumber` 인스턴스가 만들어지는 경우의 수는 몇 가지 일까요?
- 미리 생성하여 필요할 때마다 사용해 볼 수 있을까요?
- 위의 방식은 어떤 장점이 있을까요?

2023-01-09 16:42 UTC, wotjd243 commented on src/test/java/domain/lotto/LottoStoreTest.java
> +        Assertions.assertThatNoException()
아래의 코드로 개선해 보면 어떨까요?

```suggestion
        assertThatNoException()
```

2023-01-10 10:17 UTC, jungin0507 commented
리뷰 감사합니다!
강의에서 들었던 내용, 피드백 해주신 내용 반영완료 했습니다. 확실히 놓친 부분이 많이 보이네요.. 훨씬 더 분발해야할것 같습니다..!

2023-01-16 23:04 UTC, javajigi approved these changes
로또 미션 진행하느라 수고했어요. 👍 
앞으로 개발자로 살아가는데 작으나마 도움이 되는 미션이 되면 좋겠네요.
다른 미션에 집중하라는 의미로 제가 대신 merge해요.

2023-01-16 23:04 UTC, merged