[bryan.ko] 로또 Step2
2023newkrew/java-lotto-kakao pull request #93
Opened 2023-01-05 10:58 UTC by SJGeeKo

예외처리를 '철저히' 하라는 요구사항을 충족시키기가 매우 까다로웠습니다.

예외처리를 하다보니 컨트롤러 역할을 하는 Main 클래스가 다소 정신없어진 감이 있습니다.

관련하여 더 깔끔하게 정리할 수 있는 방법이 있을지 고민해보겠습니다.

리뷰 부탁드립니다.

감사합니다.

2023-01-06 01:44 UTC, matt-jylee requested changes
점점 많은 고민과 함께 코드를 작성하시는 것 같이 느껴집니다.
고생하셨습니다.

리뷰 내용도 한번 고민 부탁드립니다.

2023-01-06 01:44 UTC, matt-jylee commented on src/main/java/lotto/Main.java
>      public static void main(String[] args) {
말씀하신 것과는 매우 다르게 저는 메인 클래스가 잘 정리되어 있다고 보여집니다.
많은 고민을 하신것 같고, 이전 단계에서보다 훨씬 높은 수준의 코드가 작성된것 같습니다.
아주 좋습니다!

2023-01-06 01:44 UTC, matt-jylee commented on src/main/java/lotto/view/LottoView.java
> +public class LottoView implements AutoCloseable {
이제 사용하신 인터페이스의 사용 방법을 조금 개선해보는건 어떨까요?

- Main 클래스의 필드가 아닌 main 메서드  범위 내의 변수로의 전환

2023-01-06 01:44 UTC, matt-jylee commented on src/main/java/lotto/view/LottoView.java
> +            // parseInt 가능한지 확인
우리가 중복해서 이야기 하는 주제가 등장한것 같습니다.
"무조건" 제거할 필요는 없지만 한번 더 생각해 볼 필요가 있는 주제입니다.

2023-01-07 12:32 UTC, SJGeeKo commented on src/main/java/lotto/Main.java
>      public static void main(String[] args) {
그렇다면 다행이네요! 감사합니다 :)

2023-01-07 12:50 UTC, SJGeeKo commented on src/main/java/lotto/view/LottoView.java
> +public class LottoView implements AutoCloseable {
네 제가 AutoCloseable을 구현하여 사용한다는 것에만 집중해서 정작 사용하는 방식에 대해서는 깊이 생각하지 않았던 것 같습니다ㅠ 말씀하신 것처럼 개선해보도록 하겠습니다 :)

2023-01-07 13:19 UTC, SJGeeKo commented on src/main/java/lotto/view/LottoView.java
> +            // parseInt 가능한지 확인
맷, 죄송하지만 이 댓글에서 말씀하시고자 하는 의도를 제가 잘 이해하지 못했습니다ㅠ
이 시점에 scanner를 닫아주는 것을 고려해봐야 한다는 뜻일까요?

그런데 그렇게 하는 경우 현재 제 코드 설계상 Scanner가 LottoView의 필드멤버이기 때문에 해당 클래스 내 Scanner를 사용하는 다른 메서드의 실행에 문제가 생기게 됩니다.

아니면 혹시 Scanner를 LottoView의 필드멤버로 선언하지 말고 메서드 내에서 생성 및 소멸시키는 방식을 고려해보라는 말씀이실까요?

2023-01-09 01:42 UTC, matt-jylee commented on src/main/java/lotto/view/LottoView.java
> +            // parseInt 가능한지 확인
좀 더 자세히 이야기 해보면,
중복은 무조건 제거할 필요는 없지만 이미 작성하신 코드 내에서 
"// parseInt 가능한지 확인" 로 시작하는 중복되는 코드가 발견됩니다.

위 코드에 대한 중복, 중복을 어떻게 다루고 어떻게 처리할지 등을 생각해보자는 의미였습니다.

덧붙여서, 느낌상 위 코드는 복사&붙여넣기 코드 같아서 더 기억에 남았구요.
내가 복사&붙여넣기를 하고 있다는 말은 "조금씩 수정할 거리가 생기는구나" "어떤 과정에서 놓친게 있을까?" 등을 생각하는 계기가 되는 시발점입니다.

2023-01-09 01:44 UTC, SJGeeKo commented on src/main/java/lotto/view/LottoView.java
> +            // parseInt 가능한지 확인
아 이해했습니다! 리팩토링 후 다시 리뷰 요청드리겠습니다😁

2023-01-09 09:58 UTC, SJGeeKo commented
안녕하세요 맷, 바쁘신 와중에 리뷰해주셔서 감사드립니다.

1. try-with-resource에 더욱 알맞도록 `LottoView`를 `Main` 클래스의 필드멤버가 아닌 메서드 내 지역변수로 변경하였습니다.
2. `getInput()` 메서드를 정의하여 `LottoView` 내 많은 try-catch 블록의 중복을 제거하였습니다.
3. `LottoView`의 책임은 입출력만을 담당하는 것이라 생각해 모든 메서드의 반환 데이터형을 `String`으로 변경하였습니다.

감사합니다 :)

2023-01-09 14:08 UTC, matt-jylee approved these changes
모두 이야기 나눈대로 잘 구현해주신것 같습니다.
고생하셨습니다!

다음 단계로 가볼까요!

2023-01-09 14:08 UTC, merged