[kayla.park] 2차 pr 드립니다..!
2023newkrew/java-lotto-kakao pull request #97
Opened 2023-01-06 06:34 UTC by kokomo0

헨리, 안녕하세요!
로또 게임 2차 pr 드립니다.

2차에선 유저가 수동으로 로또 번호를 기입할 수 있는 기능이 추가되었습니다!
또, 사용자의 입력값에 대해 예외처리를 철저히 하라는 요구사항이 존재하는데요..! 제가 구현한 방식이 괜찮은 방식인건지 궁금합니다.

1) 각 예외들에 대해 예외 클래스를 새로 만들었는데요, 이렇게 따로따로 사용자 정의 클래스를 만드는 것 vs illegal exception을 사용하고, 메시지만 따로 설정해주는 것 중 어떤게 나은 방식인지 궁금합니다.

2) 로또 번호가 1~45사이 값이고, 중복이 없어야 하고 등등의 검증은 각 클래스의 생성자에서 예외를 던지도록 하였는데요, '구입 금액'이나 '수동 로또 개수' 등 따로 클래스 정의 없는 데이터 타입은 Parser에서 예외를 던지도록 되어 있습니다.. 통일성을 위해서 몇 가지 고민을 해보았는데요,
1. 모든 예외를 Parser에서 던지도록 통일한다.
2. 구입 금액, 수동 로또 개수 등 포장되지 않은 데이터를 모두 클래스로 만들고, 생성자에서 예외를 던지도록 통일한다.
3. 통일하지 않아도 상관없다.
4. 아예 다른 곳에서 예외를 던지는게 맞다.
이 중 어떤 구현 방식이 옳은지 조언을 해주실 수 있을까요? 😭

확인해주셔서 감사합니다, 좋은 주말 보내셔요..!

2023-01-09 06:48 UTC, topjung3 commented
PR 전 질문 주신 내용 부터 제 생각을 말씀 드릴께요.

1. 예외 발생 이후 특별한 처리가 없고 메세지만 출력하는 형태라면 표준 예외를 많이 쓰는 편입니다. 특수한 예외라 그 예외만 따로 잡아서 무언가의 처리가 필요하다면 custom exception을 사용하는게 좋구요.
2. 상황에 따라 다른데요. 보통의 상황에서는 각 책임이 주어지는 클래스에서 던지는게 맞다고 생각합니다. 즉 Parser는 입력을 받은 String -> Int 부분에서 에러가 났을 경우 (특수문자나 알수없는 파싱 에러) 만 처리하구요. 로또 비지니스 로직에 관련된 내용(수동 입력시 갯수, 중복 처리, 숫자 범위)은 해당 비지니스 로직을 처리하는 부분에서 에러를 발생한 후 해당 exception을 입력을 받는 class에서 받아서 다시 입력을 받을 수 있게 처리 해주면 좋겠죠. 이럴 경우 위의 custom exception을 사용하면 좋습니다.

2023-01-09 08:09 UTC, topjung3 requested changes
이번 미션이 Exception 관련 내용인 것 같아서 해당 부분을 위주로 리뷰하였습니다. 점점 더 잘 하시고 계시는게 보이네요~! 다음 코드도 기대가 됩니다.

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/exception/LottoNumberCountException.java
> +public class LottoNumberCountException extends RuntimeException {
RuntimeException을 IllegalArgumentException로 변경하면 좋아 보여요. 이러면 장점이 있는데 LottoController의 inputManualLotto에 달아 두었습니다~!

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/controller/LottoController.java
> +        } catch (Exception e) {
위의 LottoNumber~~Exception의 부모를 IllegalArgumentException로 변경하고 IllegalArgumentException를 catch하면 관련된 모든 exception을 잡을 수 있습니다. 그리고 RuntimeException을 따로 catch 하고 해당 오류는 스택트레이스를 출력하면 좋아요.

위와 같이 수정하면 좋은 이유는 예외를 처리함에 있어서 RuntimeException는 정말로 예상치 못한 에러라는 의미를 내포하고 있습니다. 즉 해당 에러가 나면 코드를 꼭 수정해야하는 예측못한 에러라고 보면 되구요. 로또 숫자 관련된 에러는 사용자 입력에 관한 문제이기 때문에 RuntimeException과 따로 구분하여 처리를 해주면 나중에 잠재적 문제가 있어서 치명적인 오류가 발생하고 있는데 발견하지 못하고 넘어가는 일이 없겠죠. Exception을 catch하면 모든 에러를 잡아주기 때문에 좋지만 꼭 수정해야하는 에러를 발견하지 못하고 사용하게 되는 문제점도 있습니다.

```
try {
  ...
} catch (IllegalArgumentException e) {
  // 에러 메세지 발생 후 사용자에게 재입력 요청
  ...
} catch (RuntimeException e) {
  e.printStackTrace();
  // 알수없는 에러라는 것을 사용자에게 알린 후 해당 에러를 리포팅해달라는 메세지와 재입력 요청
  ...
}
```

여기서 Exception은 제거하는게 좋고 이유는 Parser에 코멘트 달아 두었습니다.

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/utils/Parser.java
> +    public static Lotto parsingStringToLotto(final String input) throws Exception {
throws ~~~ 는 해당 메소드는 해당 에러가 발생할 수 있으니 꼭 처리를 해달라는 의미입니다. 즉 LottoNumber~~Exception이 되어야 명확합니다. `throws Exception` 은 너무 범위가 넓고 해당 에러가 어떠한 형태의 에러가 나올지 함수 시그니쳐를 보고 예측할 수 없어서 코드를 다시 봐야하는 불편함이 존재하겠죠.

위에서 LottoNumber~~Exception들을 전부 IllegalArgumentException를 부모로 변경하기로 하였다면 해당 구문은 `throws IllegalArgumentException`가 되면 됩니다. 해당 에러가 왜 발생하는지는 주석으로 달아두면 좋아요. 예시로 Set#add 에 대한 주석 링크 및 javadoc 에 대한 가이드 링크도 첨부했습니다.
Set#add
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Set.html#add(E)
javadoc
https://parkadd.tistory.com/137?category=913738

intelliJ 에서 함수나 클래스 위에 `/**` 치고 엔터만눌러도 기본적은 틀은 만들어주니까 한번 활용해보세요.

변경하지 않았다면 `throws LottoNumberCountException, LottoNumberDuplicateException, LottoNumberRangeException` 가 되는게 명확하겠죠.

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/model/Lotto.java
> +        if (lottoNumbers.size() != lottoNumbers.stream().distinct().count()) {
중복 이슈는 자료구조를 List 말고 Set으로 변경하면 자동으로 처리가 되서 편리합니다. distinct를 통해서 필터링 해주는 것도 좋지만 자료구조가 원래 Set이었다면 바로 size만 체크하면 되니까 훨씬 간결해질 것 같네요. 

```
Set<LottoNumber> lottoNumbers = new HashSet<>();
```

Parser부분부터 다 바꿔야하니까 코드작업이 꽤 필요한데 한번 해보시면 좋아 보여요.

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/model/Lotto.java
> +        stringBuilder.append(lottoNumbers.stream().map(LottoNumber::getNumber).sorted().map(String::valueOf).collect(Collectors.toList()));
잘하셨네요~! 이미 아실 수도 있지만 StringBuffer와 StringBuilder의 차이점도 알아두시면 좋아서 링크 하나 남겨봅니다.

https://ifuwanna.tistory.com/221

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/utils/Parser.java
>          List<LottoNumber> lottoNumberList = Arrays.stream(input.replace(" ", "")
수동 로또 번호를 입력받을 때 구분자가 , 로 정해져 있으면 입력받을 때 알려주면 좋을 것 같아요. 저는 개수 테스트하려고 `10 24 32 23 13 13 45 23` 이렇게 했더니 1024322313134523 를 숫자로 파싱하려고 해서 에러가 나더라구요. Exception 부분에서 말씀드린것처럼 이런건 예측 못한 예러였으니 RuntimeException로 처리가 되었다면 개발자에게 좀 더 유용한 정보를 유저가 리포팅 할 수 있겠죠.

2023-01-09 08:09 UTC, topjung3 commented on src/main/java/dto/LottoWinnerDto.java
> +    public LottoWinnerDto(Lotto winNumbers, LottoNumber bonusNumber) throws Exception {
이 부분도 `throws Exceptions` 이 아닌 명확한 어떠한 부분에서 에러가 나는지 개발자에게 알려주어야 좋습니다.

2023-01-11 05:41 UTC, kokomo0 commented on src/main/java/controller/LottoController.java
> +        } catch (Exception e) {
헉 그런 차이점이 있었군요..! 자세한 설명 감사드립니다!

2023-01-11 08:13 UTC, kokomo0 commented on src/main/java/model/Lotto.java
> +        if (lottoNumbers.size() != lottoNumbers.stream().distinct().count()) {
Set으로 변경하였습니다..!
사용자가 "1,2,3,4,5,6,6,6,6,6" 이런 입력을 했을 때, 중복된 번호를 입력하지 마라(혹은 번호는 6개만 입력해라) 라고 알려주어야 할 것 같아서, 이 부분에 대한 예외는 Parser로 이동시켰습니다!

2023-01-12 14:18 UTC, kokomo0 commented on src/main/java/exception/LottoNumberCountException.java
> +public class LottoNumberCountException extends RuntimeException {
넵! 모두 IllegalArgumentException을 상속하도록 변경하였습니다..!

2023-01-12 14:32 UTC, kokomo0 commented on src/main/java/model/Lotto.java
> +        stringBuilder.append(lottoNumbers.stream().map(LottoNumber::getNumber).sorted().map(String::valueOf).collect(Collectors.toList()));
넵, StringBuilder를 사용한 것은 페어가 그냥 String을 쓰는 것 보다 빠르다고 알려줬기 때문인데요..!(mutable, immutable 차이일까요 ㅎ,,) StringBuffer라는 것 도 있었네요..! 알려주셔서 감사합니다!!!

2023-01-13 02:08 UTC, kokomo0 commented on src/main/java/controller/LottoController.java
> +        } catch (Exception e) {
어제 질문드린 것 처럼, try - catch - catch 구문을 따로 빼서 만들었습니다..! 보내주신 코드 참고해서 전략 패턴으로 구현해 봤는데,,, 이렇게 구현하는 것이 맞는 것인지 궁금합니다..!(utils/controller 수정)
찾아보니 템플릿 메소드 패턴이라는 것도 있던데, 이것도 이런 예제에서 적합한 것인지 궁금합니다..!!

2023-01-13 02:10 UTC, kokomo0 commented on src/main/java/utils/Parser.java
>          List<LottoNumber> lottoNumberList = Arrays.stream(input.replace(" ", "")
네 감사합니다 ㅠㅠ 생각지도 못한 예외였네요.. 콤마가 구분자라는 사실을 입력 받을 때 메시지로 알려주고, 콤마가 5개가 아닐 경우 예외를 발생시키도록 처리하였습니다. 또 위에서 알려주신 것 처럼 IllegalArgumentException, RuntimeException을 따로 받을 수 있게 처리했어요, 알려주셔서 감사합니다!

2023-01-13 02:18 UTC, kokomo0 commented on src/main/java/utils/Parser.java
> +    public static Lotto parsingStringToLotto(final String input) throws Exception {
넵 알려주셔서 감사합니다! throws의 시그니처를 명시적으로 변경하고, 주석으로 달아 두었습니다! 문서화 주석을 이런식으로 사용하는 것 이군요..!!

+ 추가로 궁금한 것이 있습니다..!!
throw 만으로도 예외 발생 시키기 충분한 것 같은데, throws는 언제 사용하는 것이 좋을까요..?? 지금 코드에서는 크게 필요하지 않는데 사용한 것 같아서 질문드립니다!

2023-01-13 02:20 UTC, topjung3 commented on src/main/java/controller/LottoController.java
> +        } catch (Exception e) {
템플릿 메소드 패턴으로 하는게 더 깔끔하겠네요. 그렇게 수정하는게 좋을 것 같아 보입니다~! 대충 아래와 같은 느낌이 되겠네요.

```
public abstract class AbstractInput {
    protected void input(String s) {
        //
    }

    protected void retry() {
        //
    }

    public void run(String s) {
        try {
            input(s);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            retry();
        }
    }
}

public class WinnerInput extends AbstractInput {
    @Override
    protected void input(String s) {
        System.out.println("input logic");
    }

    @Override
    protected void retry() {
        System.out.println("retry logic");
    }
}

```

2023-01-13 02:21 UTC, kokomo0 commented on src/main/java/utils/Parser.java
>          List<LottoNumber> lottoNumberList = Arrays.stream(input.replace(" ", "")
네 감사합니다! 생각지 못한 부분이었네요..! 말씀하신 것 거럼 구분자로 콤마를 넣어달라고 입력에 추가했습니다..! 이런 경우를 위해 런타임 익셉션을 사용하는 것 이군요, 알려주셔서 감사합니다!

2023-01-13 02:23 UTC, kokomo0 commented on src/main/java/dto/LottoWinnerDto.java
> +    public LottoWinnerDto(Lotto winNumbers, LottoNumber bonusNumber) throws Exception {
넵.. 여기 시그니처의 throws는 제가 문법을 잘 못 알고 있어서 작성했던 것이라 삭제하였습니다,,!

2023-01-13 02:29 UTC, kokomo0 commented
위에서 조언 주신 것 처럼, 로또 비즈니스 로직 관련 예외를 관련 클래스에서 처리하도록 하기 위해, 기존 parser에서 처리하던 예외를 다음과 같이 변경했습니다.
구입 금액 예외 - 돈에 해당하는 값들을 Money, PurchaseMoney 클래스로 래핑하고 생성자에서 처리했습니다. (혹시 너무 과할까요..? 클래스가 너무 많아진 느낌이 들었습니다.)
수동 구입 로또 개수 예외 - LottoGame에서 set 할때 처리하도록 했습니다.
감사합니다!

2023-01-13 04:40 UTC, kokomo0 commented on src/main/java/controller/LottoController.java
> +        } catch (Exception e) {
앗;; 리뷰 요청을 보내드리고 확인을 했습니다..!! 템플릿 메소드 패턴으로도 구현해보겠습니다 감사합니다!!

2023-01-13 05:33 UTC, kokomo0 commented on src/main/java/controller/LottoController.java
> +        } catch (Exception e) {
템플릿 메소드 패턴을 이용하도록 수정을 하였습니다..!! 전략 패턴이랑 형태가 비슷하네요, 다만 전략 패턴과 다르게 템플릿 메서드 패턴에서는 부모 클래스가 interface가 아니어서 메소드 오버라이드에 람다식을 사용할 수 없네요 ㅠㅠ 코드가 길어지는 단점이 있었습니다..!

2023-01-13 06:34 UTC, topjung3 commented on src/main/java/utils/Parser.java
> +    public static Lotto parsingStringToLotto(final String input) throws Exception {
throw랑 throws는 사용 목적이 다릅니다. throw는 실제로 에러를 발생시키는 예약어이며, throws는 에러를 메소드를 호출하는 부분으로 미루는(양도) 예약어입니다.

의문이 드신 이유는 throw만 써도 밖에서 try catch를 해주니까 굳이 throws를 꼭 적어야할까? 하는 의문이 있으실 텐데, 이 부분은 현재 해당 예외가 상속받는 부모의 본래 의도와 현재 사용하는 방식에 약간의 괴리가 있기 때문입니다.

현재 `Lotto~~Exception`은 `IllegalArgumentException`를 상속하고 있고 이 `IllegalArgumentException`는 `RuntimeException` 을 상속하고 있기 때문입니다. `RuntimeException`은 unchecked exception으로 분류 되고 이는 실제로 체크되지 못한 exception, 예상치 못한 exception으로 분류 되기 때문에 해당 exception이 발생했을 때 프로그램은 종료가 됩니다. 처리를 하지 않아도 되는 (의도적이던지 의도적이 않던지) 에러이며, 이 에러가 발생한 순간 어플리케이션은 종료가 되기 위해 컴파일러는 catch로 묶게 강제하지 않습니다. 즉 처리를 하지 않아도 컴파일 및 빌드가 되며 실행이 됩니다.

하지만 `Exception`을 상속받는 checked exception은 다릅니다. checked exception은 말 그대로 꼭 개발자가 확인해어야하는, 처리해야하는 `Exception`을 의미합니다. 만약에 `Lotto~~Exception`이 `Exception`을 상속받았다면 반드시 컴파일러단에서 해당 메소드가 `catch`로 처리가 되거나 `throws`를 함수 시그니처에 명시하여 해당 함수를 사용하는 부분에서 에러를 처리할 수 있게 명시하도록 경고가 뜨면서 컴파일이 되지 않습니다. 즉 꼭 처리를 해주어야만 실행이 됩니다.

현재 `Lotto~~Exception`은 unchecked exception 이지만 우리는 해당 exception을 checked exception 처럼 사용하고 있으며 잘못된 입력이 들어왔을 때 프로그램이 종료되지 않고 제대로된 경고문과 retry를 시도하고 싶기 때문에, 함수 시그니쳐에 `throws`를 붙여 함수를 사용하는 개발자가 꼭 해당 에러를 처리하게 강제하여 프로그램이 비정상적으로 종료되지 않게 하기 위함입니다. 물론 전체 코드를 이해하고 있다면 throws가 없더라도 작업자가 어떠한 unchecked exception이 있는지 파악하고 작업을 할 수 있으나 이는 무조건 코드를 봐야만 알수있는 내용이므로 다른 사람이 작업할 때는 생산성이 떨어지거나 버그가 발생할 확률이 높겠죠.

정리하자면 `throws`는 함수 사용자(개발자)가 발생하는 exception을 꼭 무조건 처리하게 강제하기 위하여 사용합니다. `throws`는 실제로 에러를 발생하는 구문이 아니라 이러한 에러가 발생한다고 알려주는 역할을 합니다.

한번 `Lotto~~Exception`의 부모를 `Exception`으로 바꾸시고 생성자의 super만 주석처리하신 후 테스트 해보시면 한눈에 파악하시기 쉬우실 것 같네요.

2023-01-16 02:32 UTC, topjung3 approved these changes
Exception 관련해서 질문 주신거 코멘트 달아놨으니 한번 읽어보시고 추후 작업할 때 반영하시면 좋을 것 같아요. 일단 다른 과제도 진행해야하니까 머지하도록 하겠습니다~ 고생하셨어요.

https://github.com/next-step/java-lotto-kakao/pull/97#discussion_r1068980966

2023-01-16 02:33 UTC, merged

2023-01-16 07:10 UTC, kokomo0 commented on src/main/java/utils/Parser.java
> +    public static Lotto parsingStringToLotto(final String input) throws Exception {
헉 자세한 답변 정말 감사드립니다! 사용 목적이 다르군요.. 감사합니다!!