[gene.y] 로또 step 2
2023newkrew/java-lotto-kakao pull request #98
Opened 2023-01-06 06:56 UTC by Eithea

늦어서 죄송합니다

지난 리뷰와 step2의 요구사항에 겹치는 부분이 많아 함께 작업했습니다.

1. number, cash 를 wrapping하여 validation을 직접 수행하도록 했습니다.
2. 2개의 책임을 가졌던 Exchagne는 lotto publisher와 prize calculator로 분리했습니다.
3. controller가 직접 절차적으로 로또를 구매하기에는 복잡해진 것 같아 Trader객체를 새로 만들었습니다.
4. 테스트 추가

작업한 내용은 크게 이정도 되는 것 같습니다.
잘 부탁드려요 오션!

2023-01-09 04:00 UTC, KakaoOceanWorld requested changes
@Eithea 전체적으로 피드백 반영해주셔서 감사합니다~ 특히 원시값을 Cash, LottoNumber등 잘 포장해주셨습니다

몇가지 코멘트 남겼으니 한번 확인 부탁드리겠습니다 (__)

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/view/InputView.java
> +        }
@Eithea 제생각은, View 에서 validation을 엄격하게 할 필요가 있나 싶습니다
로또 가격 이상의 금액이 남아있음을 검증하는건 Cash#pay 에서 이미 검증을 하기도하고, 이건 도메인쪽에서 검증하는게 더 나아보입니다. 
또한 올바르지 않은 자료형이 들어오는건 그냥 exception이 발생하게 둬도 괜찮을것같습니다

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/model/ticket/LottoNumber.java
> +    }
@Eithea LottoNumber 미리생성 good!

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/model/prize/Prize.java
>      LOSING("", 0L),
@Eithea 긴 숫자들은 언더바로 구분지어주실수도 있습니다 ex) 2_000_000_000

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/model/service/TradingCalculator.java
> +public class TradingCalculator {
@Eithea static 메소드만 제공하는 유틸성 클래스는 명시적으로 생성자를 private 하게 선언하고 throw 하도록 해서 인스턴스를 생성할 필요가 없음을 드러내는 편이 좋습니다

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/model/service/TicketGenerator.java
> +    }
@Eithea generateTicket()은 랜덤 로또티켓을, generateTicket(numbers)는 전달한 숫자로 로또티켓을 만들어내는데요,
내부 구현을 보지 않더라도 네이밍으로 랜덤한 로또티켓을 생성하겠구나 라는걸 유추할 수 있어야 좋다고 생각합니다
아니면 TicketGenerator 자체를 자동/수동 generator로 분리할수도 있구요

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +        }
@Eithea 그냥 list를 toSet하고, length가 6인지만 체크하면 길이 유효성  체크가 더 간단해지지 않을까 싶습니다!

2023-01-09 04:00 UTC, kakao-ocean-world commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +    private HashSet<LottoNumber> getValidNumbers(List<LottoNumber> numbers) {
@Eithea validation check가 2단계인데, 메소드 분리해주시면 더 좋을것 같습니다.

2023-01-09 04:57 UTC, Eithea commented on src/main/java/lotto/model/prize/Prize.java
>      LOSING("", 0L),
오 이런 기능이 있네요 고맙습니다

2023-01-09 05:07 UTC, Eithea commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +        }
이런 간단한 방법이 있었네요ㅎㅎ😆

2023-01-09 08:26 UTC, Eithea commented
리뷰 적용해서 커밋했습니다!

리뷰중에 TicketGenerator 분리 관련해서 지난번 racingcar처럼 인터페이스 + 전략 패턴를 써서 로또 발매 자동/수동을 구현해봤는데, 궁금한 점이 있습니다.
`generate ticket`이라는 같은 역할의 메서드라도 자동은 parameter가 없고 수동은 있어서 하나의 인터페이스에 담기가 힘들었는데, 이를 해결할 방법이 크게 두가지가 생각이 납니다.

1. interface의 메서드 인자를 가변으로 정의 -> 자동로또에서는 가변인자로 빈 값을 전달하고, 수동로또에서는 가변인자에서 번호를 받아오기
2. interface의 메서드를 인자 있는것 없는것 모두 정의(오버로딩) -> 자동/수동 모두 필요한 쪽만 쓰고 안 쓰는 쪽은 비워두기

어느 쪽이 더 나은 방법일까요?
혹은 이렇게 같은 역할을 하는 parameter가 다른 메서드들을 하나의 인터페이스에 묶기 위한 다른 방법이 있을까요?

2023-01-10 16:07 UTC, KakaoOceanWorld commented
> 리뷰 적용해서 커밋했습니다!
> 
> 리뷰중에 TicketGenerator 분리 관련해서 지난번 racingcar처럼 인터페이스 + 전략 패턴를 써서 로또 발매 자동/수동을 구현해봤는데, 궁금한 점이 있습니다. `generate ticket`이라는 같은 역할의 메서드라도 자동은 parameter가 없고 수동은 있어서 하나의 인터페이스에 담기가 힘들었는데, 이를 해결할 방법이 크게 두가지가 생각이 납니다.
> 
> 1. interface의 메서드 인자를 가변으로 정의 -> 자동로또에서는 가변인자로 빈 값을 전달하고, 수동로또에서는 가변인자에서 번호를 받아오기
> 2. interface의 메서드를 인자 있는것 없는것 모두 정의(오버로딩) -> 자동/수동 모두 필요한 쪽만 쓰고 안 쓰는 쪽은 비워두기
> 
> 일단 커밋에서는 전자로 구현했는데, 어느 쪽이 더 나은 방법일까요? 혹은 이렇게 같은 역할을 하지만 parameter 유무가 다른 메서드들을 하나의 인터페이스에 묶기 위한 다른 방법이 있을까요?

@Eithea 제안주신 두 방법 모두 뭔가 찜찜한 부분이 있긴 할것같습니다. 
저라면 인터페이스를 generate() 로 정의하고, ManualTicketingStrategy에는 생성자에서 수동으로 넣어줄 로또번호들을 집어넣게 할 것 같습니다

각 구현체들이 구현해야할 메소드들의 형태는 통일해야 인터페이스를 정의하는 의미가 있을것 같습니다. 
만약 그게 어렵다면 그냥 인터페이스없이 각각 따로 정의하는게 낫겠죠. 패턴은 패턴일뿐 거기에 얽매일 필요는 없으니까요

2023-01-13 18:53 UTC, Eithea commented
추천해주신 방법대로 구현해봤는데요, Strategy에 로또번호를 주입하는 역할을 수행하는 클래스가 자동/수동 메서드가 분기하는 계층이어야 두 메서드가 대칭적으로 동작할 수 있었습니다.
그런데 이럴 경우 `TicketGenerator`가 그냥 들어오는 번호대로(자동인지 수동인지는 무관심하게) 티켓을 발행하는 역할을 하면 충분하고, 두 종류 Strategy을 구분하는게 무의미하게 되었네요...

그래서 불필요하게 깊은 계층을 다 삭제하고, 자동/수동 메서드에서 직접 `TicketGenerator`에 번호를 주입하도록 수정했습니다.
이것저것 시도해봤는데, 맞지 않는 인터페이스에 억지로 끼워넣었던 건지 결국 인터페이스를 다시 없애는 방향으로 갔네요😂

답변 고맙습니다. 월요일 오전에 교육과정 홈페이지에서 머지 신청할게요!

2023-01-16 00:15 UTC, KakaoOceanWorld approved these changes
@Eithea 충분히 고민하신게 느껴집니다!
고생많으셨습니다 로또미션은 여기서 마무리하겠습니다 :)

2023-01-16 00:15 UTC, merged